import {
  Season,
  LeagueConfig,
  SeasonTierRewardMatrix,
  LeaderboardStandingEntry,
  CohortGroup,
  AnomalyViolation,
} from './types';

export const INITIAL_SEASONS: Season[] = [
  {
    id: 'sea-2026-w37',
    code: 'SEASON_2026_W37',
    name: 'Mùa 37: Bứt Phá Cùng Snapy',
    description: 'Chiến dịch bảng xếp hạng hàng tuần toàn hệ thống SnapVocab. Top 5 mỗi cohort thăng hạng, Top 1 nhận cúp vinh danh.',
    cycleType: 'weekly',
    theme: 'Snapy Autumn Blaze',
    status: 'active',
    startDate: '2026-09-07T00:00:00+07:00',
    endDate: '2026-09-13T23:59:59+07:00',
    timeZone: 'Asia/Ho_Chi_Minh (GMT+7)',
    totalParticipants: 14820,
    totalCohorts: 494,
    totalXpAccumulated: 18920400,
    createdBy: 'Hệ Thống Tự Động (Cron)',
    auditNotes: 'Khởi tạo tự động lúc 00:00 Thứ 2 ngày 07/09/2026.',
  },
  {
    id: 'sea-2026-w38',
    code: 'SEASON_2026_W38',
    name: 'Mùa 38: Chinh Phục Cột Mốc',
    description: 'Mùa giải tuần tiếp theo chuẩn bị mở cửa lúc 00:00 Thứ 2 tuần sau.',
    cycleType: 'weekly',
    theme: 'Neon Cyber Sprint',
    status: 'upcoming',
    startDate: '2026-09-14T00:00:00+07:00',
    endDate: '2026-09-20T23:59:59+07:00',
    timeZone: 'Asia/Ho_Chi_Minh (GMT+7)',
    totalParticipants: 0,
    totalCohorts: 0,
    totalXpAccumulated: 0,
    createdBy: 'Hoà Nguyễn (Super Admin)',
    auditNotes: 'Đã lập lịch cấu hình sẵn sàng.',
  },
  {
    id: 'sea-2026-autumn',
    code: 'SEASON_AUTUMN_2026',
    name: 'Lễ Hội Mùa Thu: Thợ Săn Từ Vựng',
    description: 'Mùa giải đặc biệt kéo dài 1 tháng với phần thưởng giới hạn Avatar Frame Lá Phong và Danh Hiệu Mùa Thu Vàng.',
    cycleType: 'special_event',
    theme: 'Golden Harvest & Maple Leaf',
    status: 'upcoming',
    startDate: '2026-10-01T00:00:00+07:00',
    endDate: '2026-10-31T23:59:59+07:00',
    timeZone: 'Asia/Ho_Chi_Minh (GMT+7)',
    totalParticipants: 0,
    totalCohorts: 0,
    totalXpAccumulated: 0,
    createdBy: 'Mai Linh (LiveOps Manager)',
    auditNotes: 'Cấu hình phần thưởng sự kiện tháng 10.',
  },
  {
    id: 'sea-2026-w36',
    code: 'SEASON_2026_W36',
    name: 'Mùa 36: Khởi Động Tháng Chín',
    description: 'Mùa giải tuần trước đã kết thúc trọn vẹn và hoàn tất trả thưởng.',
    cycleType: 'weekly',
    theme: 'Emerald Forest',
    status: 'completed',
    startDate: '2026-08-31T00:00:00+07:00',
    endDate: '2026-09-06T23:59:59+07:00',
    timeZone: 'Asia/Ho_Chi_Minh (GMT+7)',
    totalParticipants: 14120,
    totalCohorts: 471,
    totalXpAccumulated: 17840100,
    lastSettledAt: '2026-09-07T00:15:22+07:00',
    createdBy: 'Hệ Thống Tự Động (Cron)',
    auditNotes: 'Đã hoàn tất kết toán 471 cohorts. 2,355 học viên thăng hạng.',
  },
  {
    id: 'sea-2026-w35',
    code: 'SEASON_2026_W35',
    name: 'Mùa 35: Chặng Đua Cuối Hè',
    description: 'Mùa giải tuần 35 đã lưu trữ kết quả vào Hall of Fame.',
    cycleType: 'weekly',
    theme: 'Summer Heatwave',
    status: 'completed',
    startDate: '2026-08-24T00:00:00+07:00',
    endDate: '2026-08-30T23:59:59+07:00',
    timeZone: 'Asia/Ho_Chi_Minh (GMT+7)',
    totalParticipants: 13950,
    totalCohorts: 465,
    totalXpAccumulated: 16990300,
    lastSettledAt: '2026-08-31T00:14:10+07:00',
    createdBy: 'Hệ Thống Tự Động (Cron)',
    auditNotes: 'Đã giải quyết 2 trường hợp báo lỗi xếp hạng qua Ticket #LEAD-882.',
  },
];

export const INITIAL_LEAGUES: LeagueConfig[] = [
  {
    id: 'bronze',
    name: 'Hạng Đồng (Bronze)',
    tierOrder: 1,
    icon: '🥉',
    accentColor: '#B45309',
    badgeBgColor: 'bg-amber-50 text-amber-800 border-amber-200',
    cohortSize: 30,
    canDemote: false,
    promotionRule: {
      promotionRankMax: 5,
      safeRankMax: 30,
      demotionRankMin: 31,
      minXpToPromote: 100,
    },
    activeLearnersCount: 6669,
    totalCohortsCount: 222,
    learnerPercentage: 45,
  },
  {
    id: 'silver',
    name: 'Hạng Bạc (Silver)',
    tierOrder: 2,
    icon: '🥈',
    accentColor: '#64748B',
    badgeBgColor: 'bg-slate-100 text-slate-700 border-slate-200',
    cohortSize: 30,
    canDemote: true,
    promotionRule: {
      promotionRankMax: 5,
      safeRankMax: 20,
      demotionRankMin: 21,
      minXpToPromote: 150,
    },
    activeLearnersCount: 3705,
    totalCohortsCount: 124,
    learnerPercentage: 25,
  },
  {
    id: 'gold',
    name: 'Hạng Vàng (Gold)',
    tierOrder: 3,
    icon: '🥇',
    accentColor: '#E0AB26',
    badgeBgColor: 'bg-yellow-50 text-amber-800 border-yellow-300',
    cohortSize: 30,
    canDemote: true,
    promotionRule: {
      promotionRankMax: 5,
      safeRankMax: 20,
      demotionRankMin: 21,
      minXpToPromote: 250,
    },
    activeLearnersCount: 2223,
    totalCohortsCount: 74,
    learnerPercentage: 15,
  },
  {
    id: 'platinum',
    name: 'Bạch Kim (Platinum)',
    tierOrder: 4,
    icon: '💠',
    accentColor: '#0EA5E9',
    badgeBgColor: 'bg-sky-50 text-sky-700 border-sky-200',
    cohortSize: 30,
    canDemote: true,
    promotionRule: {
      promotionRankMax: 5,
      safeRankMax: 20,
      demotionRankMin: 21,
      minXpToPromote: 400,
    },
    activeLearnersCount: 1185,
    totalCohortsCount: 40,
    learnerPercentage: 8,
  },
  {
    id: 'ruby',
    name: 'Hồng Ngọc (Ruby)',
    tierOrder: 5,
    icon: '💎',
    accentColor: '#E11D48',
    badgeBgColor: 'bg-rose-50 text-rose-700 border-rose-200',
    cohortSize: 30,
    canDemote: true,
    promotionRule: {
      promotionRankMax: 5,
      safeRankMax: 20,
      demotionRankMin: 21,
      minXpToPromote: 600,
    },
    activeLearnersCount: 741,
    totalCohortsCount: 25,
    learnerPercentage: 5,
  },
  {
    id: 'diamond',
    name: 'Kim Cương (Diamond)',
    tierOrder: 6,
    icon: '👑',
    accentColor: '#8B5CF6',
    badgeBgColor: 'bg-purple-50 text-purple-700 border-purple-200',
    cohortSize: 30,
    canDemote: true,
    promotionRule: {
      promotionRankMax: 5,
      safeRankMax: 20,
      demotionRankMin: 21,
      minXpToPromote: 800,
    },
    activeLearnersCount: 297,
    totalCohortsCount: 10,
    learnerPercentage: 2,
  },
];

export const INITIAL_REWARD_MATRICES: SeasonTierRewardMatrix[] = [
  {
    leagueId: 'diamond',
    top1Reward: {
      coins: 500,
      gems: 50,
      badgeId: 'bdg-champ-01',
      badgeName: 'Bá Chủ Kim Cương',
      titleId: 'ttl-champ-01',
      titleName: 'Quán Quân Kim Cương',
      exclusiveFrame: 'Diamond Crown 3D',
    },
    top2_3Reward: {
      coins: 350,
      gems: 30,
      badgeName: 'Top 3 Vinh Quang',
    },
    top4_5Reward: {
      coins: 200,
      gems: 15,
    },
    safeZoneReward: {
      coins: 80,
      gems: 5,
    },
    demotionZoneReward: {
      coins: 20,
      gems: 0,
    },
  },
  {
    leagueId: 'ruby',
    top1Reward: {
      coins: 400,
      gems: 35,
      badgeName: 'Quán Quân Hồng Ngọc',
      titleName: 'Chiến Tướng Ruby',
    },
    top2_3Reward: {
      coins: 250,
      gems: 20,
    },
    top4_5Reward: {
      coins: 150,
      gems: 10,
    },
    safeZoneReward: {
      coins: 60,
      gems: 2,
    },
    demotionZoneReward: {
      coins: 15,
      gems: 0,
    },
  },
  {
    leagueId: 'platinum',
    top1Reward: {
      coins: 300,
      gems: 25,
      badgeName: 'Quán Quân Bạch Kim',
      titleName: 'Học Giả Platinum',
    },
    top2_3Reward: {
      coins: 180,
      gems: 15,
    },
    top4_5Reward: {
      coins: 100,
      gems: 8,
    },
    safeZoneReward: {
      coins: 50,
      gems: 0,
    },
    demotionZoneReward: {
      coins: 10,
      gems: 0,
    },
  },
  {
    leagueId: 'gold',
    top1Reward: {
      coins: 220,
      gems: 18,
      badgeName: 'Quán Quân Hạng Vàng',
    },
    top2_3Reward: {
      coins: 130,
      gems: 10,
    },
    top4_5Reward: {
      coins: 70,
      gems: 5,
    },
    safeZoneReward: {
      coins: 35,
      gems: 0,
    },
    demotionZoneReward: {
      coins: 10,
      gems: 0,
    },
  },
  {
    leagueId: 'silver',
    top1Reward: {
      coins: 150,
      gems: 12,
      badgeName: 'Quán Quân Hạng Bạc',
    },
    top2_3Reward: {
      coins: 90,
      gems: 6,
    },
    top4_5Reward: {
      coins: 50,
      gems: 3,
    },
    safeZoneReward: {
      coins: 25,
      gems: 0,
    },
    demotionZoneReward: {
      coins: 5,
      gems: 0,
    },
  },
  {
    leagueId: 'bronze',
    top1Reward: {
      coins: 100,
      gems: 8,
      badgeName: 'Tân Binh Xuất Sắc',
    },
    top2_3Reward: {
      coins: 60,
      gems: 4,
    },
    top4_5Reward: {
      coins: 35,
      gems: 2,
    },
    safeZoneReward: {
      coins: 15,
      gems: 0,
    },
    demotionZoneReward: {
      coins: 0,
      gems: 0,
    },
  },
];

export const INITIAL_COHORTS: CohortGroup[] = [
  {
    id: 'COHORT-DIA-08',
    leagueId: 'diamond',
    name: 'Bảng Kim Cương #08 (Miền Bắc & Quốc Tế)',
    seasonId: 'sea-2026-w37',
    totalMembers: 30,
    averageXp: 1145,
    top1Xp: 2150,
    cutoffPromotionXp: 1420,
    cutoffDemotionXp: 790,
  },
  {
    id: 'COHORT-DIA-01',
    leagueId: 'diamond',
    name: 'Bảng Kim Cương #01 (Chuyên Anh & Du Học)',
    seasonId: 'sea-2026-w37',
    totalMembers: 30,
    averageXp: 1320,
    top1Xp: 2480,
    cutoffPromotionXp: 1610,
    cutoffDemotionXp: 910,
  },
  {
    id: 'COHORT-RUB-03',
    leagueId: 'ruby',
    name: 'Bảng Hồng Ngọc #03',
    seasonId: 'sea-2026-w37',
    totalMembers: 30,
    averageXp: 890,
    top1Xp: 1720,
    cutoffPromotionXp: 1150,
    cutoffDemotionXp: 610,
  },
  {
    id: 'COHORT-GLD-12',
    leagueId: 'gold',
    name: 'Bảng Vàng #12',
    seasonId: 'sea-2026-w37',
    totalMembers: 30,
    averageXp: 580,
    top1Xp: 1180,
    cutoffPromotionXp: 750,
    cutoffDemotionXp: 340,
  },
  {
    id: 'COHORT-BRZ-45',
    leagueId: 'bronze',
    name: 'Bảng Đồng #45',
    seasonId: 'sea-2026-w37',
    totalMembers: 30,
    averageXp: 310,
    top1Xp: 820,
    cutoffPromotionXp: 410,
    cutoffDemotionXp: 0,
  },
];

// 30 participants for COHORT-DIA-08
export const INITIAL_STANDINGS: LeaderboardStandingEntry[] = [
  {
    id: 'std-dia-01',
    rank: 1,
    previousRank: 2,
    movement: 'up',
    movementDiff: 1,
    weeklyXp: 2150,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'promotion',
    learner: {
      id: 'usr-001',
      name: 'Minh Triết',
      email: 'triet.minh@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
      currentStreak: 128,
      equippedTitle: 'Bậc Thầy Scan',
      levelCefr: 'C1',
    },
    activityStats: {
      scansCount: 42,
      srsReviewsCount: 165,
      quizPerfectCount: 12,
      lastActiveMinutesAgo: 14,
    },
  },
  {
    id: 'std-dia-02',
    rank: 2,
    previousRank: 1,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 1980,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'promotion',
    learner: {
      id: 'usr-002',
      name: 'Khánh Vy',
      email: 'vy.khanh@outlook.com',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
      currentStreak: 84,
      equippedTitle: 'Học Giả C1',
      levelCefr: 'C1',
    },
    activityStats: {
      scansCount: 38,
      srsReviewsCount: 140,
      quizPerfectCount: 15,
      lastActiveMinutesAgo: 32,
    },
  },
  {
    id: 'std-dia-03',
    rank: 3,
    previousRank: 4,
    movement: 'up',
    movementDiff: 1,
    weeklyXp: 1820,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'promotion',
    learner: {
      id: 'usr-003',
      name: 'Tuấn Anh',
      email: 'tuan.anh99@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80',
      currentStreak: 45,
      equippedTitle: 'Chiến Thần Flashcard',
      levelCefr: 'B2',
    },
    activityStats: {
      scansCount: 25,
      srsReviewsCount: 190,
      quizPerfectCount: 8,
      lastActiveMinutesAgo: 45,
    },
  },
  {
    id: 'std-dia-04',
    rank: 4,
    previousRank: 3,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 1510,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'promotion',
    learner: {
      id: 'usr-004',
      name: 'Lan Anh',
      email: 'lananh.edu@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
      currentStreak: 62,
      equippedTitle: 'Thợ Săn Từ Mới',
      levelCefr: 'B2',
    },
    activityStats: {
      scansCount: 31,
      srsReviewsCount: 95,
      quizPerfectCount: 7,
      lastActiveMinutesAgo: 120,
    },
  },
  {
    id: 'std-dia-05',
    rank: 5,
    previousRank: 6,
    movement: 'up',
    movementDiff: 1,
    weeklyXp: 1420,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'promotion',
    learner: {
      id: 'usr-005',
      name: 'Quốc Bảo',
      email: 'bao.quoc@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
      currentStreak: 31,
      levelCefr: 'B1',
    },
    activityStats: {
      scansCount: 20,
      srsReviewsCount: 110,
      quizPerfectCount: 6,
      lastActiveMinutesAgo: 210,
    },
  },
  {
    id: 'std-dia-06',
    rank: 6,
    previousRank: 5,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 1390,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-006',
      name: 'Thu Hương',
      email: 'huong.thu@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
      currentStreak: 55,
      levelCefr: 'B2',
    },
    activityStats: {
      scansCount: 18,
      srsReviewsCount: 105,
      quizPerfectCount: 5,
      lastActiveMinutesAgo: 15,
    },
  },
  {
    id: 'std-dia-07',
    rank: 7,
    previousRank: 7,
    movement: 'same',
    movementDiff: 0,
    weeklyXp: 1250,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-curr',
      name: 'Hoà Nguyễn (Bạn)',
      email: 'hoa.nguyen@snapvocab.ai',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
      currentStreak: 14,
      equippedTitle: 'Bậc Thầy Scan',
      levelCefr: 'B2',
      isCurrentUser: true,
    },
    activityStats: {
      scansCount: 22,
      srsReviewsCount: 88,
      quizPerfectCount: 4,
      lastActiveMinutesAgo: 5,
    },
  },
  {
    id: 'std-dia-08',
    rank: 8,
    previousRank: 9,
    movement: 'up',
    movementDiff: 1,
    weeklyXp: 1210,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-008',
      name: 'Hoàng Nam',
      email: 'nam.hoang@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
      currentStreak: 21,
      levelCefr: 'B1',
    },
    activityStats: {
      scansCount: 14,
      srsReviewsCount: 92,
      quizPerfectCount: 3,
      lastActiveMinutesAgo: 60,
    },
  },
  {
    id: 'std-dia-09',
    rank: 9,
    previousRank: 8,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 1180,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-009',
      name: 'Bích Ngọc',
      email: 'ngoc.bich@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
      currentStreak: 19,
      levelCefr: 'B1',
    },
    activityStats: {
      scansCount: 12,
      srsReviewsCount: 85,
      quizPerfectCount: 4,
      lastActiveMinutesAgo: 90,
    },
  },
  {
    id: 'std-dia-10',
    rank: 10,
    previousRank: 12,
    movement: 'up',
    movementDiff: 2,
    weeklyXp: 1140,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-010',
      name: 'Thanh Tùng',
      email: 'tung.tt@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
      currentStreak: 29,
      levelCefr: 'A2',
    },
    activityStats: {
      scansCount: 16,
      srsReviewsCount: 75,
      quizPerfectCount: 2,
      lastActiveMinutesAgo: 30,
    },
  },
  {
    id: 'std-dia-11',
    rank: 11,
    previousRank: 10,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 1120,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-011',
      name: 'Phương Thảo',
      email: 'thao.pt@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=120&auto=format&fit=crop&q=80',
      currentStreak: 41,
      levelCefr: 'B1',
    },
    activityStats: {
      scansCount: 15,
      srsReviewsCount: 80,
      quizPerfectCount: 3,
      lastActiveMinutesAgo: 400,
    },
  },
  {
    id: 'std-dia-12',
    rank: 12,
    previousRank: 11,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 1090,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-012',
      name: 'Hải Đăng',
      email: 'dang.hai@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
      currentStreak: 16,
      levelCefr: 'B2',
    },
    activityStats: {
      scansCount: 10,
      srsReviewsCount: 82,
      quizPerfectCount: 2,
      lastActiveMinutesAgo: 180,
    },
  },
  {
    id: 'std-dia-13',
    rank: 13,
    previousRank: 13,
    movement: 'same',
    movementDiff: 0,
    weeklyXp: 1060,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-013',
      name: 'Vân Anh',
      email: 'vananh.le@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
      currentStreak: 35,
      levelCefr: 'B1',
    },
    activityStats: {
      scansCount: 11,
      srsReviewsCount: 78,
      quizPerfectCount: 3,
      lastActiveMinutesAgo: 240,
    },
  },
  {
    id: 'std-dia-14',
    rank: 14,
    previousRank: 16,
    movement: 'up',
    movementDiff: 2,
    weeklyXp: 1030,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-014',
      name: 'Trọng Hiếu',
      email: 'hieu.trong@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
      currentStreak: 12,
      levelCefr: 'A2',
    },
    activityStats: {
      scansCount: 8,
      srsReviewsCount: 72,
      quizPerfectCount: 2,
      lastActiveMinutesAgo: 50,
    },
  },
  {
    id: 'std-dia-15',
    rank: 15,
    previousRank: 14,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 1010,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-015',
      name: 'Diệu Linh',
      email: 'linh.dieu@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=120&auto=format&fit=crop&q=80',
      currentStreak: 25,
      levelCefr: 'B1',
    },
    activityStats: {
      scansCount: 9,
      srsReviewsCount: 70,
      quizPerfectCount: 1,
      lastActiveMinutesAgo: 320,
    },
  },
  {
    id: 'std-dia-16',
    rank: 16,
    previousRank: 15,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 980,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-016',
      name: 'Văn Quyết',
      email: 'quyet.van@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80',
      currentStreak: 18,
      levelCefr: 'B1',
    },
    activityStats: {
      scansCount: 7,
      srsReviewsCount: 68,
      quizPerfectCount: 2,
      lastActiveMinutesAgo: 190,
    },
  },
  {
    id: 'std-dia-17',
    rank: 17,
    previousRank: 18,
    movement: 'up',
    movementDiff: 1,
    weeklyXp: 950,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-017',
      name: 'Thúy Hằng',
      email: 'hang.thuy@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=120&auto=format&fit=crop&q=80',
      currentStreak: 30,
      levelCefr: 'A2',
    },
    activityStats: {
      scansCount: 6,
      srsReviewsCount: 65,
      quizPerfectCount: 1,
      lastActiveMinutesAgo: 450,
    },
  },
  {
    id: 'std-dia-18',
    rank: 18,
    previousRank: 17,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 920,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-018',
      name: 'Đình Trọng',
      email: 'trong.dinh@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=120&auto=format&fit=crop&q=80',
      currentStreak: 8,
      levelCefr: 'B1',
    },
    activityStats: {
      scansCount: 5,
      srsReviewsCount: 64,
      quizPerfectCount: 1,
      lastActiveMinutesAgo: 110,
    },
  },
  {
    id: 'std-dia-19',
    rank: 19,
    previousRank: 20,
    movement: 'up',
    movementDiff: 1,
    weeklyXp: 890,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-019',
      name: 'Mai Hoa',
      email: 'hoa.mai@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=120&auto=format&fit=crop&q=80',
      currentStreak: 22,
      levelCefr: 'B1',
    },
    activityStats: {
      scansCount: 5,
      srsReviewsCount: 60,
      quizPerfectCount: 1,
      lastActiveMinutesAgo: 600,
    },
  },
  {
    id: 'std-dia-20',
    rank: 20,
    previousRank: 19,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 860,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'safe',
    learner: {
      id: 'usr-020',
      name: 'Vũ Đức',
      email: 'duc.vu@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
      currentStreak: 15,
      levelCefr: 'A2',
    },
    activityStats: {
      scansCount: 4,
      srsReviewsCount: 58,
      quizPerfectCount: 1,
      lastActiveMinutesAgo: 280,
    },
  },
  // Demotion zone starts here (Rank 21 - 30)
  {
    id: 'std-dia-21',
    rank: 21,
    previousRank: 21,
    movement: 'same',
    movementDiff: 0,
    weeklyXp: 810,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'demotion',
    learner: {
      id: 'usr-021',
      name: 'Kim Ngân',
      email: 'ngan.kim@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
      currentStreak: 7,
      levelCefr: 'A2',
    },
    activityStats: {
      scansCount: 3,
      srsReviewsCount: 50,
      quizPerfectCount: 1,
      lastActiveMinutesAgo: 720,
    },
  },
  {
    id: 'std-dia-22',
    rank: 22,
    previousRank: 28,
    movement: 'up',
    movementDiff: 6,
    weeklyXp: 790,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'flagged',
    learner: {
      id: 'usr-022',
      name: 'Hoàng Long (Anomaly Flag)',
      email: 'long.hoang.bot@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
      currentStreak: 3,
      levelCefr: 'A1',
    },
    activityStats: {
      scansCount: 45,
      srsReviewsCount: 180,
      quizPerfectCount: 35,
      lastActiveMinutesAgo: 2,
    },
    anomalyFlag: {
      type: 'velocity_spike',
      detectedAt: '2026-09-10T14:45:10+07:00',
      xpSurge: 2450,
      severity: 'critical',
      details: 'Tăng 2,450 XP trong vòng 8 phút qua bài nộp Quiz tốc độ 1.2 giây/bài.',
    },
  },
  {
    id: 'std-dia-23',
    rank: 23,
    previousRank: 22,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 740,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'demotion',
    learner: {
      id: 'usr-023',
      name: 'Thanh Hà',
      email: 'ha.thanh@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
      currentStreak: 5,
      levelCefr: 'A2',
    },
    activityStats: {
      scansCount: 2,
      srsReviewsCount: 45,
      quizPerfectCount: 0,
      lastActiveMinutesAgo: 1400,
    },
  },
  {
    id: 'std-dia-24',
    rank: 24,
    previousRank: 23,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 680,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'demotion',
    learner: {
      id: 'usr-024',
      name: 'Phúc Khang',
      email: 'khang.phuc@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
      currentStreak: 4,
      levelCefr: 'A2',
    },
    activityStats: {
      scansCount: 2,
      srsReviewsCount: 40,
      quizPerfectCount: 0,
      lastActiveMinutesAgo: 850,
    },
  },
  {
    id: 'std-dia-25',
    rank: 25,
    previousRank: 24,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 620,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'demotion',
    learner: {
      id: 'usr-025',
      name: 'Yến Nhi',
      email: 'nhi.yen@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
      currentStreak: 6,
      levelCefr: 'A1',
    },
    activityStats: {
      scansCount: 1,
      srsReviewsCount: 38,
      quizPerfectCount: 0,
      lastActiveMinutesAgo: 1600,
    },
  },
  {
    id: 'std-dia-26',
    rank: 26,
    previousRank: 25,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 540,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'demotion',
    learner: {
      id: 'usr-026',
      name: 'Đăng Khoa',
      email: 'khoa.dang@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
      currentStreak: 2,
      levelCefr: 'A2',
    },
    activityStats: {
      scansCount: 1,
      srsReviewsCount: 30,
      quizPerfectCount: 0,
      lastActiveMinutesAgo: 2100,
    },
  },
  {
    id: 'std-dia-27',
    rank: 27,
    previousRank: 26,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 480,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'demotion',
    learner: {
      id: 'usr-027',
      name: 'Hồng Nhung',
      email: 'nhung.hong@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
      currentStreak: 1,
      levelCefr: 'A1',
    },
    activityStats: {
      scansCount: 1,
      srsReviewsCount: 25,
      quizPerfectCount: 0,
      lastActiveMinutesAgo: 2400,
    },
  },
  {
    id: 'std-dia-28',
    rank: 28,
    previousRank: 27,
    movement: 'down',
    movementDiff: 1,
    weeklyXp: 350,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'demotion',
    learner: {
      id: 'usr-028',
      name: 'Gia Huy',
      email: 'huy.gia@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
      currentStreak: 0,
      levelCefr: 'A1',
    },
    activityStats: {
      scansCount: 0,
      srsReviewsCount: 20,
      quizPerfectCount: 0,
      lastActiveMinutesAgo: 3200,
    },
  },
  {
    id: 'std-dia-29',
    rank: 29,
    previousRank: 29,
    movement: 'same',
    movementDiff: 0,
    weeklyXp: 210,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'demotion',
    learner: {
      id: 'usr-029',
      name: 'Thảo My',
      email: 'my.thao@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=120&auto=format&fit=crop&q=80',
      currentStreak: 0,
      levelCefr: 'A1',
    },
    activityStats: {
      scansCount: 0,
      srsReviewsCount: 12,
      quizPerfectCount: 0,
      lastActiveMinutesAgo: 4500,
    },
  },
  {
    id: 'std-dia-30',
    rank: 30,
    previousRank: 30,
    movement: 'same',
    movementDiff: 0,
    weeklyXp: 90,
    leagueId: 'diamond',
    cohortId: 'COHORT-DIA-08',
    status: 'demotion',
    learner: {
      id: 'usr-030',
      name: 'Bảo Long',
      email: 'long.bao@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
      currentStreak: 0,
      levelCefr: 'A1',
    },
    activityStats: {
      scansCount: 0,
      srsReviewsCount: 5,
      quizPerfectCount: 0,
      lastActiveMinutesAgo: 5100,
    },
  },
];

export const INITIAL_ANOMALIES: AnomalyViolation[] = [
  {
    id: 'anm-001',
    learnerId: 'usr-022',
    learnerName: 'Hoàng Long',
    learnerAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    cohortId: 'COHORT-DIA-08',
    leagueId: 'diamond',
    detectedAt: '2026-09-10T14:45:10+07:00',
    anomalyType: 'velocity_spike',
    xpDelta: 2450,
    timeWindowSeconds: 480,
    status: 'pending_review',
  },
  {
    id: 'anm-002',
    learnerId: 'usr-bot-99',
    learnerName: 'Nguyễn Tùng Bot',
    learnerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    cohortId: 'COHORT-RUB-03',
    leagueId: 'ruby',
    detectedAt: '2026-09-10T11:20:00+07:00',
    anomalyType: 'suspicious_script',
    xpDelta: 3100,
    timeWindowSeconds: 300,
    status: 'deducted',
    actionTaken: 'Đã trừ 2,500 XP gian lận và cảnh báo lần 1',
    actionBy: 'Hoà Nguyễn (Super Admin)',
    actionAt: '2026-09-10T11:35:12+07:00',
    auditReason: 'Phát hiện click tự động curl request vào endpoint /quiz/submit. Ticket #CHEAT-102.',
  },
  {
    id: 'anm-003',
    learnerId: 'usr-spm-41',
    learnerName: 'FastLearner_Auto',
    learnerAvatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=120&auto=format&fit=crop&q=80',
    cohortId: 'COHORT-GLD-12',
    leagueId: 'gold',
    detectedAt: '2026-09-09T18:05:30+07:00',
    anomalyType: 'packet_injection',
    xpDelta: 4500,
    timeWindowSeconds: 120,
    status: 'disqualified',
    actionTaken: 'Truất quyền thi đấu Mùa 37 & Khóa tài khoản 7 ngày',
    actionBy: 'Mai Linh (LiveOps Manager)',
    actionAt: '2026-09-09T18:22:45+07:00',
    auditReason: 'Lặp lại hành vi gian lận sau khi đã bị trừ điểm ở Mùa 36. Ticket #SECURITY-409.',
  },
];
