// ====================================================
// SNAPVOCAB ISSUE REPORTS MOCK DATA
// Source of Truth: docs/design/design.md & docs/spec/
// ====================================================

import { IssueReportItem } from './types';

export const INITIAL_ISSUE_REPORTS: IssueReportItem[] = [
  // ==========================================================
  // 1. P1 ACTIVE LEARNING (AI CAMERA SCAN ISSUES) — 3 ITEMS
  // ==========================================================
  {
    id: 'ISS-9812',
    ticketId: 'TK-2026-8910',
    category: 'AI_SCAN',
    subCategory: 'MISIDENTIFIED_OBJECT',
    priority: 'P1',
    status: 'PENDING',
    reportedAt: '2026-09-11T07:35:00Z',
    slaDeadline: '2026-09-11T09:35:00Z', // 2 hours SLA for P1
    slaRemainingMinutes: 42,
    title: 'Nhận diện sai: Chụp bình giữ nhiệt (thermos) nhưng đoán coffee cup',
    description:
      'Học viên báo cáo: "Tôi chụp bình giữ nhiệt bằng thép không gỉ đặt trên bàn học, nhưng AI lại nhận diện là coffee cup thông thường với độ tin cậy thấp 58%. Mong ban quản trị cập nhật từ thermos vào từ điển giúp tôi."',
    targetWord: 'thermos',
    suggestedWord: 'thermos',
    targetCefr: 'B1',
    learner: {
      id: 'USR-10824',
      fullName: 'Nguyễn Quang Minh',
      email: 'minh.nguyen@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'B2',
      streakDays: 56,
      league: 'Diamond',
      coins: 3420,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 15 Pro',
      appVersion: 'v1.4.2',
      osVersion: 'iOS 17.5.1',
      locale: 'vi-VN',
    },
    scanData: {
      scanId: 'SCN-9812',
      requestId: 'req-scan-9812',
      thumbnailUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&auto=format&fit=crop&q=80',
      originalImageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=90',
      cropUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=400&auto=format&fit=crop&q=80',
      predictedLabel: 'coffee cup',
      suggestedLabel: 'thermos',
      confidence: 0.58,
      clipScore: 0.25,
      boundingBox: [210, 320, 780, 680],
      pushedToFineTuning: false,
    },
  },
  {
    id: 'ISS-9804',
    ticketId: 'TK-2026-8911',
    category: 'AI_SCAN',
    subCategory: 'MISIDENTIFIED_OBJECT',
    priority: 'P1',
    status: 'PENDING',
    reportedAt: '2026-09-11T07:15:00Z',
    slaDeadline: '2026-09-11T09:15:00Z',
    slaRemainingMinutes: 22,
    title: 'Nhận diện sai: Sách bài tập (workbook) bị đoán nhầm thành textbook',
    description:
      'Học viên báo cáo: "Đây là cuốn sách bài tập ngữ pháp bài test IELTS, có nhiều bài tập điền từ chứ không phải giáo trình lý thuyết textbook."',
    targetWord: 'workbook',
    suggestedWord: 'workbook',
    targetCefr: 'B1',
    learner: {
      id: 'USR-10829',
      fullName: 'Đặng Phương Thảo',
      email: 'phuong.thao.dang@techcorp.io',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'C1',
      streakDays: 45,
      league: 'Ruby',
      coins: 4890,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 14',
      appVersion: 'v1.4.2',
      osVersion: 'iOS 17.4',
      locale: 'vi-VN',
    },
    scanData: {
      scanId: 'SCN-9804',
      requestId: 'req-scan-9804',
      thumbnailUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
      originalImageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=90',
      cropUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
      predictedLabel: 'textbook',
      suggestedLabel: 'workbook',
      confidence: 0.62,
      clipScore: 0.24,
      boundingBox: [150, 220, 810, 790],
      pushedToFineTuning: false,
    },
  },
  {
    id: 'ISS-9788',
    ticketId: 'TK-2026-8912',
    category: 'AI_SCAN',
    subCategory: 'LOW_CONFIDENCE_ERROR',
    priority: 'P1',
    status: 'PENDING',
    reportedAt: '2026-09-11T06:40:00Z',
    slaDeadline: '2026-09-11T08:40:00Z',
    slaRemainingMinutes: 8,
    title: 'Nhận diện sai: Kính cận thường bị gán thành kính râm (sunglasses)',
    description:
      'Học viên báo cáo: "Kính gọng kim loại cận thị trong suốt (eyeglasses / reading glasses), camera AI lại đoán thành sunglasses với độ tin cậy 54%."',
    targetWord: 'eyeglasses',
    suggestedWord: 'reading glasses',
    targetCefr: 'A2',
    learner: {
      id: 'USR-10830',
      fullName: 'Võ Tuấn Kiệt',
      email: 'tuan.kiet@vnn.vn',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'B1',
      streakDays: 14,
      league: 'Sapphire',
      coins: 1820,
    },
    deviceInfo: {
      platform: 'android',
      deviceModel: 'Samsung Galaxy S23',
      appVersion: 'v1.4.1',
      osVersion: 'Android 14',
      locale: 'vi-VN',
    },
    scanData: {
      scanId: 'SCN-9788',
      requestId: 'req-scan-9788',
      thumbnailUrl: 'https://images.unsplash.com/photo-1584905066893-7d5c142ba4e1?w=400&auto=format&fit=crop&q=80',
      originalImageUrl: 'https://images.unsplash.com/photo-1584905066893-7d5c142ba4e1?w=800&auto=format&fit=crop&q=90',
      cropUrl: 'https://images.unsplash.com/photo-1584905066893-7d5c142ba4e1?w=400&auto=format&fit=crop&q=80',
      predictedLabel: 'sunglasses',
      suggestedLabel: 'reading glasses',
      confidence: 0.54,
      clipScore: 0.22,
      boundingBox: [300, 200, 650, 800],
      pushedToFineTuning: false,
    },
  },

  // ==========================================================
  // 2. VOCABULARY & CONTENT ISSUES (MH-ADM-06 & FR-03.09) — 6 ITEMS
  // ==========================================================
  {
    id: 'ISS-9770',
    ticketId: 'TK-2026-8845',
    category: 'VOCABULARY',
    subCategory: 'WRONG_MEANING',
    priority: 'P2',
    status: 'INVESTIGATING',
    reportedAt: '2026-09-10T14:30:00Z',
    slaDeadline: '2026-09-11T14:30:00Z',
    slaRemainingMinutes: 350,
    title: 'Sai nghĩa từ vựng: "resilient" bị dịch thành "co giãn vật lý"',
    description:
      'Người học phản ánh: Nghĩa của từ resilient trong ngữ cảnh con người/tinh thần nên là "kiên cường, có khả năng phục hồi nhanh", không nên dùng nghĩa máy móc "có tính co giãn vật lý".',
    targetWord: 'resilient',
    targetCefr: 'C1',
    learner: {
      id: 'USR-10827',
      fullName: 'Lê Thu Hà',
      email: 'thuha.le@fintech.vn',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'C1',
      streakDays: 82,
      league: 'Diamond',
      coins: 6150,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 15 Pro Max',
      appVersion: 'v1.4.2',
      osVersion: 'iOS 17.5',
      locale: 'vi-VN',
    },
    vocabData: {
      wordId: 'w-resilient-c1',
      targetWord: 'resilient',
      partOfSpeech: 'adjective',
      currentMeaningVi: 'có tính đàn hồi, co giãn vật lý khi chịu lực nén',
      suggestedMeaningVi: 'kiên cường, có khả năng phục hồi nhanh chóng sau biến cố',
      currentIpa: '/rɪˈzɪl.jənt/',
      suggestedIpa: '/rɪˈzɪl.jənt/',
      currentExampleEn: 'He is resilient and never gives up despite difficult times.',
      currentExampleVi: 'Anh ấy có tính co giãn và không bao giờ bỏ cuộc.',
      suggestedExampleVi: 'Anh ấy rất kiên cường và không bao giờ bỏ cuộc dù gặp nghịch cảnh.',
    },
  },
  {
    id: 'ISS-9765',
    ticketId: 'TK-2026-8832',
    category: 'VOCABULARY',
    subCategory: 'WRONG_IPA',
    priority: 'P2',
    status: 'PENDING',
    reportedAt: '2026-09-10T16:10:00Z',
    slaDeadline: '2026-09-11T16:10:00Z',
    slaRemainingMinutes: 440,
    title: 'Sai phiên âm IPA: "meticulous" bị thiếu dấu trọng âm chính',
    description:
      'Từ "meticulous" hiện hiển thị phiên âm /mɪtɪkjʊləs/ thiếu dấu trọng âm âm tiết 2 (/mɪˈtɪk.jə.ləs/). Giọng đọc phát âm cũng bị nhấn nhầm âm 1.',
    targetWord: 'meticulous',
    targetCefr: 'B2',
    learner: {
      id: 'USR-10825',
      fullName: 'Trần Bảo Ngọc',
      email: 'ngoc.tran@designstudio.co',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'B1',
      streakDays: 24,
      league: 'Gold',
      coins: 2150,
    },
    deviceInfo: {
      platform: 'android',
      deviceModel: 'Xiaomi 13T',
      appVersion: 'v1.4.1',
      osVersion: 'Android 13',
      locale: 'vi-VN',
    },
    vocabData: {
      wordId: 'w-meticulous-b2',
      targetWord: 'meticulous',
      partOfSpeech: 'adjective',
      currentMeaningVi: 'tỉ mỉ, kỹ lưỡng, chăm chút từng chi tiết nhỏ',
      suggestedMeaningVi: 'tỉ mỉ, kỹ lưỡng, cẩn thận từng chi tiết nhỏ',
      currentIpa: '/mɪtɪkjʊləs/',
      suggestedIpa: '/mɪˈtɪk.jə.ləs/',
      currentExampleEn: 'She was meticulous about keeping her vocabulary notes clean.',
      currentExampleVi: 'Cô ấy rất tỉ mỉ trong việc giữ sổ từ vựng sạch sẽ.',
    },
  },
  {
    id: 'ISS-9760',
    ticketId: 'TK-2026-8819',
    category: 'VOCABULARY',
    subCategory: 'MISSING_WORD_ENTRY',
    priority: 'P2',
    status: 'PENDING',
    reportedAt: '2026-09-10T18:00:00Z',
    slaDeadline: '2026-09-11T18:00:00Z',
    slaRemainingMinutes: 520,
    title: 'Báo từ thiếu (MH-ADM-06): Chụp tai nghe bluetooth "airpods" chưa có trong từ điển',
    description:
      'Học viên chụp hộp tai nghe không dây, hệ thống báo "Chưa có từ vựng tương ứng trong từ điển". Xin Admin bổ sung từ "earbuds" hoặc "airpods" vào chủ đề Công Nghệ (Technology).',
    targetWord: 'earbuds',
    suggestedWord: 'earbuds',
    targetCefr: 'A2',
    learner: {
      id: 'USR-10826',
      fullName: 'Phạm Hoàng Long',
      email: 'long.pham@fpt.edu.vn',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'A2',
      streakDays: 12,
      league: 'Silver',
      coins: 980,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 13',
      appVersion: 'v1.4.2',
      osVersion: 'iOS 17.3',
      locale: 'vi-VN',
    },
    vocabData: {
      targetWord: 'earbuds',
      partOfSpeech: 'noun (plural)',
      currentMeaningVi: 'Chưa có trong từ điển',
      suggestedMeaningVi: 'tai nghe nhét tai nhỏ, tai nghe không dây bluetooth',
      currentIpa: 'Chưa có',
      suggestedIpa: '/ˈɪr.bʌdz/',
    },
  },
  {
    id: 'ISS-9755',
    ticketId: 'TK-2026-8805',
    category: 'VOCABULARY',
    subCategory: 'AUDIO_PRONUNCIATION_GLITCH',
    priority: 'P2',
    status: 'INVESTIGATING',
    reportedAt: '2026-09-09T20:20:00Z',
    slaDeadline: '2026-09-10T20:20:00Z',
    slaRemainingMinutes: -120, // Overdue SLA
    title: 'Lỗi phát âm TTS: "lead" (danh từ kim loại chì) đọc nhầm thành /liːd/',
    description:
      'Trong thẻ từ loại danh từ (kim loại chì), âm thanh Web Speech TTS tự động đọc là /liːd/ (của động từ dẫn dắt) thay vì đọc chuẩn /led/. Cần chỉ định audio .mp3 thu âm riêng cho từ đồng âm dị nghĩa này.',
    targetWord: 'lead',
    targetCefr: 'B1',
    learner: {
      id: 'USR-10831',
      fullName: 'Hoàng Đức Nam',
      email: 'nam.hoang@vnu.edu.vn',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'B2',
      streakDays: 31,
      league: 'Sapphire',
      coins: 2450,
    },
    deviceInfo: {
      platform: 'android',
      deviceModel: 'Samsung Galaxy A54',
      appVersion: 'v1.4.0',
      osVersion: 'Android 14',
      locale: 'vi-VN',
    },
    vocabData: {
      wordId: 'w-lead-metal',
      targetWord: 'lead',
      partOfSpeech: 'noun [uncountable]',
      currentMeaningVi: 'chì (kim loại mềm màu xám đen)',
      suggestedMeaningVi: 'kim loại chì (nguyên tố hóa học Pb)',
      currentIpa: '/led/',
      suggestedIpa: '/led/',
      currentExampleEn: 'Lead pipes are no longer used in modern construction.',
      currentExampleVi: 'Ống dẫn chì không còn được sử dụng trong xây dựng hiện đại.',
    },
  },
  {
    id: 'ISS-9750',
    ticketId: 'TK-2026-8790',
    category: 'VOCABULARY',
    subCategory: 'INCORRECT_EXAMPLE',
    priority: 'P3',
    status: 'PENDING',
    reportedAt: '2026-09-09T15:10:00Z',
    slaDeadline: '2026-09-11T15:10:00Z',
    slaRemainingMinutes: 380,
    title: 'Thiếu câu dịch tiếng Việt cho ví dụ của từ "diligent"',
    description:
      'Thẻ từ vựng "diligent" có câu ví dụ tiếng Anh rất hay nhưng phần dịch tiếng Việt đang hiển thị trống "---".',
    targetWord: 'diligent',
    targetCefr: 'B1',
    learner: {
      id: 'USR-10833',
      fullName: 'Bùi Gia Huy',
      email: 'huy.bui@fastmail.com',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'A2',
      streakDays: 9,
      league: 'Bronze',
      coins: 450,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 12',
      appVersion: 'v1.4.2',
      osVersion: 'iOS 17.2',
      locale: 'vi-VN',
    },
    vocabData: {
      wordId: 'w-diligent-b1',
      targetWord: 'diligent',
      partOfSpeech: 'adjective',
      currentMeaningVi: 'siêng năng, cần cù, chăm chỉ',
      suggestedMeaningVi: 'siêng năng, cần cù, chăm chỉ',
      currentIpa: '/ˈdɪl.ə.dʒənt/',
      currentExampleEn: 'He made diligent efforts to master 500 flashcards.',
      currentExampleVi: '---',
      suggestedExampleVi: 'Cậu ấy đã nỗ lực chăm chỉ để thuộc lòng 500 thẻ từ vựng.',
    },
  },
  {
    id: 'ISS-9748',
    ticketId: 'TK-2026-8772',
    category: 'VOCABULARY',
    subCategory: 'SPELLING_TYPO',
    priority: 'P3',
    status: 'PENDING',
    reportedAt: '2026-09-09T11:00:00Z',
    slaDeadline: '2026-09-11T11:00:00Z',
    slaRemainingMinutes: 120,
    title: 'Gán nhầm cấp độ CEFR: "cucumber" (dưa chuột) bị gán nhãn C1',
    description:
      'Từ "cucumber" (quả dưa leo/dưa chuột) là từ vựng rất thông dụng thuộc trình độ A1, nhưng hệ thống lại gán nhãn tím C1 gây khó cho người mới bắt đầu.',
    targetWord: 'cucumber',
    targetCefr: 'A1',
    learner: {
      id: 'USR-10834',
      fullName: 'Đỗ Thảo Vy',
      email: 'vy.do@hust.edu.vn',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'A1',
      streakDays: 5,
      league: 'Bronze',
      coins: 310,
    },
    deviceInfo: {
      platform: 'android',
      deviceModel: 'Oppo Reno 10',
      appVersion: 'v1.4.1',
      osVersion: 'Android 13',
      locale: 'vi-VN',
    },
    vocabData: {
      wordId: 'w-cucumber-a1',
      targetWord: 'cucumber',
      partOfSpeech: 'noun',
      currentMeaningVi: 'quả dưa chuột, quả dưa leo',
      suggestedMeaningVi: 'quả dưa chuột, quả dưa leo',
      currentIpa: '/ˈkjuː.kʌm.bər/',
    },
  },

  // ==========================================================
  // 3. LIVEOPS & ACCOUNT GLITCHES (LIVEOPS GUARDRAILS §7.3) — 3 ITEMS
  // ==========================================================
  {
    id: 'ISS-9745',
    ticketId: 'TK-2026-7731',
    category: 'LIVEOPS_ACCOUNT',
    subCategory: 'STREAK_UNJUSTLY_LOST',
    priority: 'P1',
    status: 'INVESTIGATING',
    reportedAt: '2026-09-11T06:10:00Z',
    slaDeadline: '2026-09-11T08:10:00Z',
    slaRemainingMinutes: 15,
    title: 'Mất chuỗi Streak 14 ngày do máy chủ bảo trì R2/S3 lúc 23:30',
    description:
      'Thời điểm 23:30 máy chủ bảo trì mạng thanh toán và kho lưu trữ R2 trả mã 502 Bad Gateway trong 45 phút, không thể kết nối sync flashcard review log khiến chuỗi học 14 ngày bị về 0.',
    learner: {
      id: 'USR-10830',
      fullName: 'Võ Tuấn Kiệt',
      email: 'tuan.kiet@vnn.vn',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'B1',
      streakDays: 0,
      league: 'Sapphire',
      coins: 1820,
    },
    deviceInfo: {
      platform: 'android',
      deviceModel: 'Samsung Galaxy S23',
      appVersion: 'v1.4.1',
      osVersion: 'Android 14',
      locale: 'vi-VN',
    },
  },
  {
    id: 'ISS-9740',
    ticketId: 'TK-2026-7712',
    category: 'LIVEOPS_ACCOUNT',
    subCategory: 'REWARD_NOT_CREDITED',
    priority: 'P2',
    status: 'PENDING',
    reportedAt: '2026-09-10T19:40:00Z',
    slaDeadline: '2026-09-11T19:40:00Z',
    slaRemainingMinutes: 620,
    title: 'Hoàn thành nhiệm vụ tuần "Master 50 Cards" nhưng chưa nhận được 100 Gems',
    description:
      'Học viên đã học thuộc đủ 50 thẻ FSRS vào chiều thứ Năm, thanh tiến độ nhiệm vụ hiển thị 50/50 nhưng khi bấm Nhận Thưởng thì bị lỗi mạng "Network Timeout" và số Gems không tăng.',
    learner: {
      id: 'USR-10825',
      fullName: 'Trần Bảo Ngọc',
      email: 'ngoc.tran@designstudio.co',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'B1',
      streakDays: 24,
      league: 'Gold',
      coins: 2150,
    },
    deviceInfo: {
      platform: 'android',
      deviceModel: 'Xiaomi 13T',
      appVersion: 'v1.4.1',
      osVersion: 'Android 13',
      locale: 'vi-VN',
    },
  },
  {
    id: 'ISS-9735',
    ticketId: 'TK-2026-7690',
    category: 'LIVEOPS_ACCOUNT',
    subCategory: 'PURCHASE_DOUBLE_CHARGED',
    priority: 'P2',
    status: 'INVESTIGATING',
    reportedAt: '2026-09-10T11:25:00Z',
    slaDeadline: '2026-09-11T11:25:00Z',
    slaRemainingMinutes: 180,
    title: 'Mua vật phẩm "Streak Freeze Chest" bị trừ Coins 2 lần do mạng chập chờn',
    description:
      'Học viên bấm mua 1 rương đóng băng chuỗi giá 300 Coins, app xoay loading lâu rồi trừ 600 Coins nhưng kho đồ chỉ nhận 1 rương duy nhất.',
    learner: {
      id: 'USR-10832',
      fullName: 'Nguyễn Duy Khang',
      email: 'khang.nguyen@vti.com.vn',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'B2',
      streakDays: 38,
      league: 'Diamond',
      coins: 890,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 14 Pro',
      appVersion: 'v1.4.2',
      osVersion: 'iOS 17.4',
      locale: 'vi-VN',
    },
  },

  // ==========================================================
  // 4. TECHNICAL & STABILITY ISSUES — 2 ITEMS
  // ==========================================================
  {
    id: 'ISS-9720',
    ticketId: 'TK-2026-6640',
    category: 'TECHNICAL_APP',
    subCategory: 'APP_CRASH_SRS',
    priority: 'P3',
    status: 'PENDING',
    reportedAt: '2026-09-09T08:15:00Z',
    slaDeadline: '2026-09-11T08:15:00Z',
    slaRemainingMinutes: 45,
    title: 'Ứng dụng văng màn hình chính khi lật thẻ thứ 25 trong phiên ôn bài',
    description:
      'Gặp crash đột ngột trên phiên bản iOS v1.4.2 khi đang ôn tập chế độ lật thẻ nhanh 3D Flip, đã xảy ra 2 lần.',
    learner: {
      id: 'USR-10824',
      fullName: 'Nguyễn Quang Minh',
      email: 'minh.nguyen@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'B2',
      streakDays: 56,
      league: 'Diamond',
      coins: 3420,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 15 Pro',
      appVersion: 'v1.4.2',
      osVersion: 'iOS 17.5.1',
      locale: 'vi-VN',
    },
  },
  {
    id: 'ISS-9715',
    ticketId: 'TK-2026-6612',
    category: 'TECHNICAL_APP',
    subCategory: 'CAMERA_PERMISSION_DENIED',
    priority: 'P3',
    status: 'PENDING',
    reportedAt: '2026-09-08T14:10:00Z',
    slaDeadline: '2026-09-10T14:10:00Z',
    slaRemainingMinutes: -1400,
    title: 'Không cấp được quyền Camera trên Android 14 khi ấn nút Scan',
    description:
      'Người dùng từ chối quyền lần đầu, sau đó vào cài đặt bật quyền nhưng app vẫn hiện màn hình đen "Permission Denied" mà không tự refresh.',
    learner: {
      id: 'USR-10830',
      fullName: 'Võ Tuấn Kiệt',
      email: 'tuan.kiet@vnn.vn',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'B1',
      streakDays: 14,
      league: 'Sapphire',
      coins: 1820,
    },
    deviceInfo: {
      platform: 'android',
      deviceModel: 'Samsung Galaxy S23',
      appVersion: 'v1.4.1',
      osVersion: 'Android 14',
      locale: 'vi-VN',
    },
  },

  // ==========================================================
  // 5. RESOLVED HISTORICAL RECORDS (FOR RESOLUTION & AUDIT LEDGER) — 4 ITEMS
  // ==========================================================
  {
    id: 'ISS-9690',
    ticketId: 'TK-2026-5501',
    category: 'AI_SCAN',
    subCategory: 'MISIDENTIFIED_OBJECT',
    priority: 'P1',
    status: 'RESOLVED',
    reportedAt: '2026-09-08T09:00:00Z',
    slaDeadline: '2026-09-08T11:00:00Z',
    slaRemainingMinutes: 0,
    title: 'Chụp balo du lịch (backpack) bị nhầm thành handbag',
    description: 'Học viên chụp balo leo núi chống nước nhưng AI đoán handbag.',
    targetWord: 'backpack',
    suggestedWord: 'backpack',
    targetCefr: 'A1',
    learner: {
      id: 'USR-10829',
      fullName: 'Đặng Phương Thảo',
      email: 'phuong.thao.dang@techcorp.io',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'C1',
      streakDays: 45,
      coins: 4890,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 14',
      appVersion: 'v1.4.2',
      osVersion: 'iOS 17.4',
      locale: 'vi-VN',
    },
    scanData: {
      scanId: 'SCN-9690',
      thumbnailUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&auto=format&fit=crop&q=80',
      originalImageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=90',
      predictedLabel: 'handbag',
      suggestedLabel: 'backpack',
      confidence: 0.68,
      pushedToFineTuning: true,
    },
    resolution: {
      resolvedAt: '2026-09-08T09:42:00Z',
      resolvedBy: 'Admin Duyệt Viên',
      actionTaken: 'LABEL_CORRECTED_AND_DATASET_SAVED',
      resolutionNotes:
        'Đã kiểm tra ảnh thực tế: Balo leo núi quai to rõ ràng. Đã sửa nhãn "backpack" A1, thêm vào từ điển và xuất mẫu vào Gemini Vision dataset.',
      compensationCoins: 20,
      pushNotificationSent: true,
      notificationTitle: 'Báo cáo nhận diện AI đã được duyệt! 🦊',
      notificationBody: 'Từ "backpack" đã được cập nhật chuẩn xác. Bạn được tặng +20 Coins cảm ơn vì đóng góp!',
    },
  },
  {
    id: 'ISS-9685',
    ticketId: 'TK-2026-5488',
    category: 'VOCABULARY',
    subCategory: 'WRONG_MEANING',
    priority: 'P2',
    status: 'RESOLVED',
    reportedAt: '2026-09-07T14:15:00Z',
    slaDeadline: '2026-09-08T14:15:00Z',
    slaRemainingMinutes: 0,
    title: 'Từ "ubiquitous" bị thiếu nghĩa bóng trong ngữ cảnh công nghệ',
    description: 'Bổ sung nghĩa "phổ biến khắp nơi, nhan nhản, có mặt ở mọi ngóc ngách".',
    targetWord: 'ubiquitous',
    targetCefr: 'C1',
    learner: {
      id: 'USR-10827',
      fullName: 'Lê Thu Hà',
      email: 'thuha.le@fintech.vn',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'C1',
      streakDays: 82,
      coins: 6150,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 15 Pro Max',
      appVersion: 'v1.4.2',
      osVersion: 'iOS 17.5',
      locale: 'vi-VN',
    },
    vocabData: {
      wordId: 'w-ubiquitous-c1',
      targetWord: 'ubiquitous',
      partOfSpeech: 'adjective',
      currentMeaningVi: 'có mặt ở khắp nơi',
      suggestedMeaningVi: 'phổ biến khắp nơi, nhan nhản, hiện diện mọi lúc mọi nơi',
      currentIpa: '/juːˈbɪk.wə.təs/',
    },
    resolution: {
      resolvedAt: '2026-09-07T16:30:00Z',
      resolvedBy: 'Lead Content Admin',
      actionTaken: 'OPENED_IN_CONTENT_STUDIO',
      resolutionNotes:
        'Đã mở Content Studio, cập nhật thêm nghĩa phụ và câu ví dụ công nghệ (smartphone is ubiquitous). Đã xuất bản lên hệ thống.',
      compensationCoins: 20,
      pushNotificationSent: true,
      notificationTitle: 'Nội dung từ vựng đã được hoàn thiện! 📚',
      notificationBody: 'Góp ý cho từ "ubiquitous" của bạn đã được áp dụng vào từ điển SnapVocab.',
    },
  },
  {
    id: 'ISS-9670',
    ticketId: 'TK-2026-5320',
    category: 'LIVEOPS_ACCOUNT',
    subCategory: 'STREAK_UNJUSTLY_LOST',
    priority: 'P1',
    status: 'RESOLVED',
    reportedAt: '2026-09-06T08:00:00Z',
    slaDeadline: '2026-09-06T10:00:00Z',
    slaRemainingMinutes: 0,
    title: 'Khôi phục Streak 45 ngày bị mất do đổi múi giờ khi bay sang Nhật Bản',
    description: 'Học viên bay sang Tokyo (UTC+9), chênh lệch 2 tiếng khiến app khóa phiên ngày trước.',
    learner: {
      id: 'USR-10829',
      fullName: 'Đặng Phương Thảo',
      email: 'phuong.thao.dang@techcorp.io',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'C1',
      streakDays: 45,
      coins: 4890,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 14',
      appVersion: 'v1.4.2',
      osVersion: 'iOS 17.4',
      locale: 'ja-JP',
    },
    resolution: {
      resolvedAt: '2026-09-06T08:45:00Z',
      resolvedBy: 'Support Agent Anh',
      actionTaken: 'STREAK_RESTORED',
      resolutionNotes:
        'Xác nhận log GPS và timezone nhảy UTC+7 sang UTC+9. Đã kích hoạt Streak Recovery Tool khôi phục chuỗi 45 ngày.',
      compensationCoins: 50,
      pushNotificationSent: true,
      notificationTitle: 'Chuỗi Streak của bạn đã được hồi sinh! 🔥',
      notificationBody: 'Hệ thống đã bù lại chuỗi 45 ngày học liên tục cho bạn. Tiếp tục phát huy nhé!',
    },
  },
  {
    id: 'ISS-9650',
    ticketId: 'TK-2026-5100',
    category: 'TECHNICAL_APP',
    subCategory: 'APP_CRASH_SRS',
    priority: 'P3',
    status: 'DISMISSED',
    reportedAt: '2026-09-05T12:00:00Z',
    slaDeadline: '2026-09-07T12:00:00Z',
    slaRemainingMinutes: 0,
    title: 'Báo lỗi không nghe được audio khi điện thoại bật chế độ im lặng',
    description: 'Người dùng bật công tắc gạt Silent Mode trên iPhone nên ứng dụng không phát loa ngoài.',
    learner: {
      id: 'USR-10834',
      fullName: 'Đỗ Thảo Vy',
      email: 'vy.do@hust.edu.vn',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      cefrLevel: 'A1',
      streakDays: 5,
      coins: 310,
    },
    deviceInfo: {
      platform: 'ios',
      deviceModel: 'iPhone 11',
      appVersion: 'v1.4.0',
      osVersion: 'iOS 16.5',
      locale: 'vi-VN',
    },
    resolution: {
      resolvedAt: '2026-09-05T13:10:00Z',
      resolvedBy: 'Admin Duyệt Viên',
      actionTaken: 'DISMISSED_INVALID',
      resolutionNotes:
        'Hệ thống âm thanh tuân thủ cấu hình AudioSession của iOS; máy ở chế độ Silent Switch sẽ không phát loa nếu không cắm tai nghe. Đã phản hồi hướng dẫn cho học viên.',
      pushNotificationSent: true,
      notificationTitle: 'Hướng dẫn sử dụng âm thanh trên iOS 🔊',
      notificationBody: 'Vui lòng gạt công tắc rung sang chuông hoặc cắm tai nghe để nghe phát âm.',
    },
  },
];
