import { CardViewModel } from '../flashcard/types';

export const INITIAL_VOCABULARY: CardViewModel[] = [
  {
    id: 'vocab-001',
    word: 'apple',
    phonetic: '/ˈæp.əl/',
    partOfSpeech: 'noun',
    cefr: 'A1',
    status: 'published',
    source: 'DICT',
    topicId: 'topic-food',
    topicName: 'Food & Nutrition',
    tags: ['fruit', 'daily', 'basic', 'kitchen'],
    lastUpdated: '2026-09-08T14:20:00Z',
    media: {
      imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop&q=80',
    },
    audio: {
      sourceType: 'tts',
      voice: 'en-US',
      speed: 1.0,
      pitch: 1.0,
    },
    meanings: [
      {
        id: 'm-001',
        partOfSpeech: 'noun',
        definitionVi: 'quả táo (trái cây vỏ đỏ hoặc xanh, cùi giòn, vị ngọt hoặc chua)',
        definitionEn: 'a round fruit with firm, white flesh and a green, red, or yellow skin',
        examples: [
          {
            id: 'ex-1',
            en: 'She peeled an apple and sliced it into pieces.',
            vi: 'Cô ấy gọt vỏ một quả táo rồi cắt thành từng miếng nhỏ.',
          },
          {
            id: 'ex-2',
            en: 'An apple a day keeps the doctor away.',
            vi: 'Mỗi ngày một quả táo giúp tránh xa bác sĩ.',
          },
        ],
      },
    ],
    auditHistory: [
      {
        id: 'aud-1',
        timestamp: '2026-09-01T08:00:00Z',
        action: 'CREATE',
        changedBy: 'Admin (System)',
        reason: 'Khởi tạo từ bộ từ điển cơ bản Oxford 3000',
        previousStatus: 'draft',
        nextStatus: 'published',
      },
    ],
  },
  {
    id: 'vocab-002',
    word: 'resilient',
    phonetic: '/rɪˈzɪl.jənt/',
    partOfSpeech: 'adjective',
    cefr: 'C1',
    status: 'review',
    source: 'AI',
    topicId: 'topic-personality',
    topicName: 'Mindset & Psychology',
    tags: ['mindset', 'advanced', 'toefl', 'ielts'],
    lastUpdated: '2026-09-09T18:45:00Z',
    media: {
      imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80',
    },
    audio: {
      sourceType: 'tts',
      voice: 'en-US',
      speed: 0.95,
      pitch: 1.0,
    },
    meanings: [
      {
        id: 'm-002',
        partOfSpeech: 'adjective',
        definitionVi: 'kiên cường, bất khuất; có khả năng phục hồi nhanh sau khó khăn',
        definitionEn: 'able to quickly become healthy, happy, or strong again after an illness, problem, or other difficult situation',
        examples: [
          {
            id: 'ex-3',
            en: 'Local businesses have been remarkably resilient despite economic hardship.',
            vi: 'Các doanh nghiệp địa phương đã phục hồi một cách phi thường bất chấp khó khăn kinh tế.',
          },
          {
            id: 'ex-4',
            en: 'Children are often more resilient than adults give them credit for.',
            vi: 'Trẻ em thường kiên cường hơn những gì người lớn đánh giá.',
          },
        ],
      },
    ],
    auditHistory: [
      {
        id: 'aud-2',
        timestamp: '2026-09-09T18:45:00Z',
        action: 'SUBMIT_FOR_REVIEW',
        changedBy: 'Content Bot (AI Generator)',
        reason: 'Sinh tự động từ chủ đề Advanced Mindset, chờ kiểm duyệt phiên âm & ví dụ',
        previousStatus: 'draft',
        nextStatus: 'review',
      },
    ],
  },
  {
    id: 'vocab-003',
    word: 'thermos',
    phonetic: '/ˈθɜː.məs/',
    partOfSpeech: 'noun',
    cefr: 'B1',
    status: 'review',
    source: 'SCAN',
    topicId: 'topic-daily',
    topicName: 'Daily Essentials',
    tags: ['kitchen', 'office', 'ai-scan-corrected'],
    lastUpdated: '2026-09-10T02:15:00Z',
    media: {
      imageUrl: 'https://images.unsplash.com/photo-1570857502809-08184874388e?w=600&auto=format&fit=crop&q=80',
      aiConfidence: 0.94,
    },
    audio: {
      sourceType: 'tts',
      voice: 'en-US',
      speed: 1.0,
      pitch: 1.0,
    },
    meanings: [
      {
        id: 'm-003',
        partOfSpeech: 'noun',
        definitionVi: 'bình giữ nhiệt (dùng để giữ nước nóng hoặc lạnh trong thời gian dài)',
        definitionEn: 'a container that keeps liquids hot or cold',
        examples: [
          {
            id: 'ex-5',
            en: 'I always bring a thermos of hot green tea on winter camping trips.',
            vi: 'Tôi luôn mang theo một bình giữ nhiệt trà xanh nóng trong những chuyến cắm trại mùa đông.',
          },
        ],
      },
    ],
    auditHistory: [
      {
        id: 'aud-3',
        timestamp: '2026-09-10T02:15:00Z',
        action: 'CORRECTION',
        changedBy: 'Lead Operator',
        reason: 'Sửa lỗi nhận diện từ user report: AI ban đầu quét nhầm là beer bottle',
        previousStatus: 'draft',
        nextStatus: 'review',
      },
    ],
  },
  {
    id: 'vocab-004',
    word: 'abandon',
    phonetic: '/əˈbæn.dən/',
    partOfSpeech: 'verb',
    cefr: 'B1',
    status: 'published',
    source: 'DICT',
    topicId: 'topic-general',
    topicName: 'Core Verbs',
    tags: ['verbs', 'toeic', 'b1-verbs'],
    lastUpdated: '2026-09-05T10:11:00Z',
    audio: {
      sourceType: 'tts',
      voice: 'en-US',
      speed: 1.0,
      pitch: 1.0,
    },
    meanings: [
      {
        id: 'm-004',
        partOfSpeech: 'verb',
        definitionVi: 'từ bỏ, ruồng bỏ, bỏ hoang',
        definitionEn: 'to leave a place, thing, or person, usually for ever',
        examples: [
          {
            id: 'ex-6',
            en: 'They had to abandon their car when the road flooded.',
            vi: 'Họ đã phải bỏ lại chiếc xe ô tô khi con đường bị ngập lụt.',
          },
        ],
      },
    ],
    auditHistory: [],
  },
  {
    id: 'vocab-005',
    word: 'curious',
    phonetic: '/ˈkjʊə.ri.əs/',
    partOfSpeech: 'adjective',
    cefr: 'A2',
    status: 'draft',
    source: 'TOPIC',
    topicId: 'topic-personality',
    topicName: 'Mindset & Psychology',
    tags: ['curiosity', 'feelings'],
    lastUpdated: '2026-09-09T11:00:00Z',
    audio: {
      sourceType: 'tts',
      voice: 'en-US',
      speed: 1.0,
      pitch: 1.0,
    },
    meanings: [
      {
        id: 'm-005',
        partOfSpeech: 'adjective',
        definitionVi: 'tò mò, hiếu kỳ; muốn tìm hiểu mọi thứ',
        definitionEn: 'interested in learning about people or things around you',
        examples: [
          {
            id: 'ex-7',
            en: 'Babies are naturally curious about everything around them.',
            vi: 'Trẻ sơ sinh tự nhiên luôn tò mò về mọi thứ xung quanh chúng.',
          },
        ],
      },
    ],
    auditHistory: [],
  },
  {
    id: 'vocab-006',
    word: 'serendipity',
    phonetic: '/ˌser.ənˈdɪp.ə.ti/',
    partOfSpeech: 'noun',
    cefr: 'C2',
    status: 'draft',
    source: 'DICT',
    topicId: 'topic-advanced',
    topicName: 'Literary & Nuanced English',
    tags: ['c2-advanced', 'poetic', 'fortune'],
    lastUpdated: '2026-09-10T01:00:00Z',
    audio: {
      sourceType: 'tts',
      voice: 'en-GB',
      speed: 0.9,
      pitch: 1.0,
    },
    meanings: [
      {
        id: 'm-006',
        partOfSpeech: 'noun',
        definitionVi: 'sự tình cờ may mắn; sự khám phá bất ngờ và thú vị',
        definitionEn: 'the fact of finding interesting or valuable things by chance',
        examples: [
          {
            id: 'ex-8',
            en: 'Finding my favorite vintage book in that quaint little shop was pure serendipity.',
            vi: 'Tìm thấy cuốn sách cổ điển yêu thích trong tiệm nhỏ kỳ lạ đó là sự tình cờ may mắn thuần túy.',
          },
        ],
      },
    ],
    auditHistory: [],
  },
];
