import {
  Badge,
  HonoraryTitle,
  LearnerBadgeRecord,
} from './types';

// ====================================================
// INITIAL BADGES REPOSITORY (18+ ITEMS)
// ====================================================

export const INITIAL_BADGES: Badge[] = [
  // 1. STREAK CHAIN
  {
    id: 'bdg-strk-01',
    code: 'BDG-STRK-07',
    name: 'Ngọn Lửa Khởi Đầu',
    description: 'Duy trì chuỗi học liên tục trong 7 ngày không gián đoạn.',
    category: 'streak',
    tier: 'bronze',
    icon: '🔥',
    unlockMetric: 'STREAK_DAYS',
    targetValue: 7,
    targetUnit: 'ngày liên tục',
    reward: { xp: 100, coins: 150 },
    status: 'active',
    seriesId: 'streak-series',
    seriesLevel: 1,
    totalEarners: 14820,
    unlockRate: 64.5,
    createdDate: '2026-01-10',
    lastUpdated: '2026-08-15',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-strk-02',
    code: 'BDG-STRK-30',
    name: 'Thói Quen Vàng',
    description: 'Duy trì chuỗi học liên tục suốt 30 ngày. Khẳng định tính kỷ luật vượt trội!',
    category: 'streak',
    tier: 'silver',
    icon: '⚡',
    unlockMetric: 'STREAK_DAYS',
    targetValue: 30,
    targetUnit: 'ngày liên tục',
    reward: { xp: 350, coins: 500, gems: 20 },
    status: 'active',
    seriesId: 'streak-series',
    seriesLevel: 2,
    totalEarners: 4920,
    unlockRate: 21.4,
    createdDate: '2026-01-10',
    lastUpdated: '2026-08-15',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-strk-03',
    code: 'BDG-STRK-100',
    name: 'Chiến Thần Kỷ Luật',
    description: 'Bền bỉ đạt cột mốc 100 ngày streak liên tục. Mở khóa danh hiệu [Bất Diệt 100 Ngày]!',
    category: 'streak',
    tier: 'gold',
    icon: '👑',
    unlockMetric: 'STREAK_DAYS',
    targetValue: 100,
    targetUnit: 'ngày liên tục',
    reward: {
      xp: 1200,
      coins: 1500,
      gems: 80,
      titleId: 'ttl-strk-100',
      titleName: '[Bất Diệt 100 Ngày]',
    },
    status: 'active',
    seriesId: 'streak-series',
    seriesLevel: 3,
    totalEarners: 1140,
    unlockRate: 4.9,
    createdDate: '2026-01-10',
    lastUpdated: '2026-09-01',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-strk-04',
    code: 'BDG-STRK-365',
    name: 'Huyền Thoại Bất Tử',
    description: 'Hoàn thành 365 ngày học tập liên tục cùng Snapy. Một kỳ tích phi thường!',
    category: 'streak',
    tier: 'diamond',
    icon: '💎',
    unlockMetric: 'STREAK_DAYS',
    targetValue: 365,
    targetUnit: 'ngày liên tục',
    reward: {
      xp: 5000,
      coins: 5000,
      gems: 300,
      titleId: 'ttl-strk-365',
      titleName: '[Kỷ Luật Tối Thượng]',
    },
    status: 'active',
    seriesId: 'streak-series',
    seriesLevel: 4,
    totalEarners: 86,
    unlockRate: 0.38,
    createdDate: '2026-01-10',
    lastUpdated: '2026-09-01',
    updatedBy: 'Super Admin',
  },

  // 2. AI CAMERA SCAN
  {
    id: 'bdg-scan-01',
    code: 'BDG-SCAN-10',
    name: 'Thợ Săn Ống Kính',
    description: 'Quét và lưu thành công 10 đồ vật thực tế qua AI Camera Scan.',
    category: 'scan',
    tier: 'bronze',
    icon: '📷',
    unlockMetric: 'AI_SCAN_SAVED',
    targetValue: 10,
    targetUnit: 'từ scan thành công',
    reward: { xp: 80, coins: 120 },
    status: 'active',
    seriesId: 'scan-series',
    seriesLevel: 1,
    totalEarners: 12450,
    unlockRate: 54.2,
    createdDate: '2026-02-01',
    lastUpdated: '2026-08-20',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-scan-02',
    code: 'BDG-SCAN-50',
    name: 'Mắt Đại Bàng AI',
    description: 'Nhận diện và phân loại thành công 50 đồ vật phong phú trong đời sống.',
    category: 'scan',
    tier: 'silver',
    icon: '🦅',
    unlockMetric: 'AI_SCAN_SAVED',
    targetValue: 50,
    targetUnit: 'từ scan thành công',
    reward: { xp: 250, coins: 400, gems: 15 },
    status: 'active',
    seriesId: 'scan-series',
    seriesLevel: 2,
    totalEarners: 3870,
    unlockRate: 16.8,
    createdDate: '2026-02-01',
    lastUpdated: '2026-08-20',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-scan-03',
    code: 'BDG-SCAN-100',
    name: 'Thần Đèn Nhận Diện',
    description: 'Đạt 100 lần quét vật thể có lưu thẻ học. Mở khóa danh hiệu [Thần Đèn Scan]!',
    category: 'scan',
    tier: 'gold',
    icon: '✨',
    unlockMetric: 'AI_SCAN_SAVED',
    targetValue: 100,
    targetUnit: 'từ scan thành công',
    reward: {
      xp: 800,
      coins: 1000,
      gems: 50,
      titleId: 'ttl-scan-01',
      titleName: '[Thần Đèn Scan]',
    },
    status: 'active',
    seriesId: 'scan-series',
    seriesLevel: 3,
    totalEarners: 1320,
    unlockRate: 5.7,
    createdDate: '2026-02-01',
    lastUpdated: '2026-09-05',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-scan-04',
    code: 'BDG-SCAN-500',
    name: 'Thị Giác Siêu Phàm',
    description: 'Đạt 500 lần nhận diện chính xác vật thể xung quanh không gian sống.',
    category: 'scan',
    tier: 'platinum',
    icon: '🔮',
    unlockMetric: 'AI_SCAN_SAVED',
    targetValue: 500,
    targetUnit: 'từ scan thành công',
    reward: { xp: 2000, coins: 2500, gems: 120 },
    status: 'active',
    seriesId: 'scan-series',
    seriesLevel: 4,
    totalEarners: 215,
    unlockRate: 0.94,
    createdDate: '2026-02-01',
    lastUpdated: '2026-09-05',
    updatedBy: 'Super Admin',
  },

  // 3. VOCABULARY & SRS MASTERY
  {
    id: 'bdg-voc-01',
    code: 'BDG-VOC-50',
    name: 'Vốn Từ Khởi Sắc',
    description: 'Thành thạo vĩnh viễn 50 thẻ từ vựng đầu tiên trong thuật toán SRS.',
    category: 'vocabulary',
    tier: 'bronze',
    icon: '🌱',
    unlockMetric: 'SRS_MASTERED',
    targetValue: 50,
    targetUnit: 'thẻ SRS thành thạo',
    reward: { xp: 120, coins: 180 },
    status: 'active',
    seriesId: 'vocab-series',
    seriesLevel: 1,
    totalEarners: 10240,
    unlockRate: 44.5,
    createdDate: '2026-01-15',
    lastUpdated: '2026-08-10',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-voc-02',
    code: 'BDG-VOC-200',
    name: 'Bách Khoa Nền Tảng',
    description: 'Nắm vững 200 từ vựng cốt lõi chuẩn CEFR A1 - B1.',
    category: 'vocabulary',
    tier: 'silver',
    icon: '📚',
    unlockMetric: 'SRS_MASTERED',
    targetValue: 200,
    targetUnit: 'thẻ SRS thành thạo',
    reward: { xp: 400, coins: 600, gems: 25 },
    status: 'active',
    seriesId: 'vocab-series',
    seriesLevel: 2,
    totalEarners: 3240,
    unlockRate: 14.1,
    createdDate: '2026-01-15',
    lastUpdated: '2026-08-10',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-voc-03',
    code: 'BDG-VOC-500',
    name: 'Nhà Ngôn Ngữ Học',
    description: 'Làm chủ 500 thẻ từ vựng nâng cao. Đạt cấp độ thông thạo C1.',
    category: 'vocabulary',
    tier: 'gold',
    icon: '🎓',
    unlockMetric: 'SRS_MASTERED',
    targetValue: 500,
    targetUnit: 'thẻ SRS thành thạo',
    reward: {
      xp: 1500,
      coins: 1800,
      gems: 90,
      titleId: 'ttl-c1-master',
      titleName: '[Học Giả C1]',
    },
    status: 'active',
    seriesId: 'vocab-series',
    seriesLevel: 3,
    totalEarners: 860,
    unlockRate: 3.74,
    createdDate: '2026-01-15',
    lastUpdated: '2026-09-02',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-voc-04',
    code: 'BDG-VOC-1000',
    name: 'Đại Từ Điển Sống',
    description: 'Thuần thục 1,000 thẻ từ vựng mọi trình độ. Đỉnh cao trí tuệ ngôn ngữ!',
    category: 'vocabulary',
    tier: 'diamond',
    icon: '🏆',
    unlockMetric: 'SRS_MASTERED',
    targetValue: 1000,
    targetUnit: 'thẻ SRS thành thạo',
    reward: {
      xp: 6000,
      coins: 6000,
      gems: 400,
      titleId: 'ttl-lexicon-king',
      titleName: '[Đại Từ Điển Sống]',
    },
    status: 'active',
    seriesId: 'vocab-series',
    seriesLevel: 4,
    totalEarners: 104,
    unlockRate: 0.45,
    createdDate: '2026-01-15',
    lastUpdated: '2026-09-02',
    updatedBy: 'Super Admin',
  },

  // 4. QUIZ & ACCURACY
  {
    id: 'bdg-quiz-01',
    code: 'BDG-QUIZ-10',
    name: 'Thiện Xạ Trắc Nghiệm',
    description: 'Hoàn thành 10 bài kiểm tra trắc nghiệm từ vựng đạt tuyệt đối 100%.',
    category: 'quiz',
    tier: 'silver',
    icon: '🎯',
    unlockMetric: 'PERFECT_QUIZ',
    targetValue: 10,
    targetUnit: 'bài Quiz 100%',
    reward: { xp: 300, coins: 450, gems: 20 },
    status: 'active',
    totalEarners: 4120,
    unlockRate: 17.9,
    createdDate: '2026-02-15',
    lastUpdated: '2026-08-25',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-quiz-02',
    code: 'BDG-QUIZ-50',
    name: 'Bất Bại Phản Xạ',
    description: 'Hoàn thành 50 bài kiểm tra điểm tuyệt đối mà không phạm một lỗi sai nào!',
    category: 'quiz',
    tier: 'platinum',
    icon: '⚡',
    unlockMetric: 'PERFECT_QUIZ',
    targetValue: 50,
    targetUnit: 'bài Quiz 100%',
    reward: {
      xp: 1800,
      coins: 2200,
      gems: 100,
      titleId: 'ttl-quiz-god',
      titleName: '[Bất Bại Phản Xạ]',
    },
    status: 'active',
    totalEarners: 340,
    unlockRate: 1.48,
    createdDate: '2026-02-15',
    lastUpdated: '2026-08-25',
    updatedBy: 'Super Admin',
  },

  // 5. LEAGUE & SOCIAL
  {
    id: 'bdg-leag-01',
    code: 'BDG-LEAG-01',
    name: 'Đỉnh Cao Vinh Quang',
    description: 'Giành ngôi vị Quán Quân hạng 1 trong Bảng Xếp Hạng giải đấu tuần.',
    category: 'league',
    tier: 'diamond',
    icon: '👑',
    unlockMetric: 'LEADERBOARD_RANK',
    targetValue: 1,
    targetUnit: 'lần đạt Hạng 1 tuần',
    reward: {
      xp: 3000,
      coins: 4000,
      gems: 250,
      titleId: 'ttl-diamond',
      titleName: '[Bá Chủ Kim Cương]',
    },
    status: 'active',
    totalEarners: 285,
    unlockRate: 1.24,
    createdDate: '2026-03-01',
    lastUpdated: '2026-09-08',
    updatedBy: 'Lead Admin Hoà',
  },

  // 6. SECRET & EASTER EGG
  {
    id: 'bdg-sec-01',
    code: 'BDG-NIGHT-01',
    name: 'Cú Đêm Chăm Chỉ',
    description: 'Hoàn thành bài học hoàn chỉnh vào khung giờ bí mật từ 01:00 đến 04:00 sáng.',
    category: 'special_event',
    tier: 'gold',
    icon: '🦉',
    unlockMetric: 'STREAK_DAYS',
    targetValue: 1,
    targetUnit: 'lượt học đêm khuya',
    reward: { xp: 500, coins: 800, gems: 40 },
    status: 'secret',
    isSecret: true,
    secretHint: 'Thử mở app và vượt qua một bài kiểm tra khi cả thành phố đã chìm vào giấc ngủ...',
    totalEarners: 720,
    unlockRate: 3.13,
    createdDate: '2026-04-01',
    lastUpdated: '2026-08-29',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-sec-02',
    code: 'BDG-DEV-01',
    name: 'Mật Mã Snapy',
    description: 'Gõ liên tục 10 lần vào biểu tượng Snapy trên màn hình để mở khóa bí mật.',
    category: 'special_event',
    tier: 'platinum',
    icon: '🦊',
    unlockMetric: 'TOPICS_COMPLETED',
    targetValue: 1,
    targetUnit: 'lần giải mã',
    reward: { xp: 777, coins: 777, gems: 77 },
    status: 'secret',
    isSecret: true,
    secretHint: 'Chú cáo Snapy rất thích được người học gõ đầu đùa nghịch...',
    totalEarners: 195,
    unlockRate: 0.85,
    createdDate: '2026-04-01',
    lastUpdated: '2026-08-29',
    updatedBy: 'Super Admin',
  },

  // 7. DRAFT & ARCHIVED
  {
    id: 'bdg-draft-01',
    code: 'BDG-SP-OCT',
    name: 'Phù Thủy Halloween',
    description: 'Hoàn thành chủ đề Ma Quái trong chuỗi sự kiện Halloween tháng 10.',
    category: 'special_event',
    tier: 'gold',
    icon: '🎃',
    unlockMetric: 'TOPICS_COMPLETED',
    targetValue: 1,
    targetUnit: 'chủ đề sự kiện',
    reward: { xp: 600, coins: 900, gems: 50 },
    status: 'draft',
    totalEarners: 0,
    unlockRate: 0,
    createdDate: '2026-09-01',
    lastUpdated: '2026-09-08',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'bdg-arch-01',
    code: 'BDG-BETA-01',
    name: 'Nhà Thám Hiểm Tiên Phong',
    description: 'Dành riêng cho những người học tham gia giai đoạn Closed Beta 2025.',
    category: 'special_event',
    tier: 'silver',
    icon: '🚀',
    unlockMetric: 'TOPICS_COMPLETED',
    targetValue: 1,
    targetUnit: 'tài khoản beta',
    reward: { xp: 200, coins: 500 },
    status: 'archived',
    totalEarners: 650,
    unlockRate: 2.82,
    createdDate: '2025-10-01',
    lastUpdated: '2026-01-01',
    updatedBy: 'Super Admin',
    auditNotes: 'Đã đóng cấp phát sau khi kết thúc chương trình Closed Beta.',
  },
];

// ====================================================
// HONORARY TITLES REPOSITORY (8 ITEMS)
// ====================================================

export const INITIAL_TITLES: HonoraryTitle[] = [
  {
    id: 'ttl-scan-01',
    code: 'TTL-SCAN-01',
    name: '[Thần Đèn Scan]',
    description: 'Dành cho bậc thầy nhận diện vật thể camera AI qua 100 lần thành công.',
    rarity: 'gold',
    flairTheme: 'neon',
    requiredBadgeId: 'bdg-scan-03',
    requiredBadgeName: 'Thần Đèn Nhận Diện',
    totalEquipped: 890,
    equipRate: 67.4,
    status: 'active',
    createdDate: '2026-02-01',
  },
  {
    id: 'ttl-strk-100',
    code: 'TTL-STRK-100',
    name: '[Bất Diệt 100 Ngày]',
    description: 'Biểu tượng của sự kiên trì vô song qua 100 ngày học liên tiếp.',
    rarity: 'gold',
    flairTheme: 'fire',
    requiredBadgeId: 'bdg-strk-03',
    requiredBadgeName: 'Chiến Thần Kỷ Luật',
    totalEquipped: 980,
    equipRate: 85.9,
    status: 'active',
    createdDate: '2026-01-10',
  },
  {
    id: 'ttl-c1-master',
    code: 'TTL-C1-MASTER',
    name: '[Học Giả C1]',
    description: 'Chứng nhận năng lực nắm vững 500 từ vựng học thuật cao cấp.',
    rarity: 'gold',
    flairTheme: 'emerald',
    requiredBadgeId: 'bdg-voc-03',
    requiredBadgeName: 'Nhà Ngôn Ngữ Học',
    totalEquipped: 520,
    equipRate: 60.5,
    status: 'active',
    createdDate: '2026-01-15',
  },
  {
    id: 'ttl-diamond',
    code: 'TTL-DIAMOND',
    name: '[Bá Chủ Kim Cương]',
    description: 'Vinh quang của nhà vô địch giải đấu Leaderboard hàng tuần.',
    rarity: 'diamond',
    flairTheme: 'royal',
    requiredBadgeId: 'bdg-leag-01',
    requiredBadgeName: 'Đỉnh Cao Vinh Quang',
    totalEquipped: 245,
    equipRate: 86.0,
    status: 'active',
    createdDate: '2026-03-01',
  },
  {
    id: 'ttl-quiz-god',
    code: 'TTL-QUIZ-GOD',
    name: '[Bất Bại Phản Xạ]',
    description: 'Chinh phục 50 bài kiểm tra trắc nghiệm điểm số tuyệt đối.',
    rarity: 'platinum',
    flairTheme: 'gold',
    requiredBadgeId: 'bdg-quiz-02',
    requiredBadgeName: 'Bất Bại Phản Xạ',
    totalEquipped: 260,
    equipRate: 76.5,
    status: 'active',
    createdDate: '2026-02-15',
  },
  {
    id: 'ttl-strk-365',
    code: 'TTL-STRK-365',
    name: '[Kỷ Luật Tối Thượng]',
    description: 'Vương miện 365 ngày streak liên tiếp không bỏ lỡ một ngày.',
    rarity: 'diamond',
    flairTheme: 'fire',
    requiredBadgeId: 'bdg-strk-04',
    requiredBadgeName: 'Huyền Thoại Bất Tử',
    totalEquipped: 82,
    equipRate: 95.3,
    status: 'active',
    createdDate: '2026-01-10',
  },
  {
    id: 'ttl-lexicon-king',
    code: 'TTL-LEXICON-KING',
    name: '[Đại Từ Điển Sống]',
    description: 'Vốn từ vựng đồ sộ với 1,000 thẻ thành thạo vĩnh viễn.',
    rarity: 'diamond',
    flairTheme: 'royal',
    requiredBadgeId: 'bdg-voc-04',
    requiredBadgeName: 'Đại Từ Điển Sống',
    totalEquipped: 96,
    equipRate: 92.3,
    status: 'active',
    createdDate: '2026-01-15',
  },
  {
    id: 'ttl-starter',
    code: 'TTL-STARTER',
    name: '[Tân Binh Cần Mẫn]',
    description: 'Khởi đầu hành trình học tập cùng Snapy.',
    rarity: 'bronze',
    flairTheme: 'emerald',
    totalEquipped: 4320,
    equipRate: 42.1,
    status: 'active',
    createdDate: '2026-01-01',
  },
];

// ====================================================
// RECENT LEARNER BADGE UNLOCK LOGS (12 SAMPLES)
// ====================================================

export const INITIAL_LEARNER_RECORDS: LearnerBadgeRecord[] = [
  {
    id: 'rec-001',
    learnerId: 'lrn-10294',
    learnerName: 'Nguyễn Văn Hoà',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&h=120&fit=crop',
    email: 'hoa.nguyen@example.com',
    badgeId: 'bdg-strk-03',
    badgeCode: 'BDG-STRK-100',
    badgeName: 'Chiến Thần Kỷ Luật',
    badgeTier: 'gold',
    badgeIcon: '👑',
    earnedAt: '10 phút trước',
    idempotencyKey: 'EVT-STRK100-LRN10294-20260910',
    isEquippedFeatured: true,
    status: 'valid',
  },
  {
    id: 'rec-002',
    learnerId: 'lrn-20811',
    learnerName: 'Trần Thị Mai',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop',
    email: 'mai.tran@example.com',
    badgeId: 'bdg-scan-03',
    badgeCode: 'BDG-SCAN-100',
    badgeName: 'Thần Đèn Nhận Diện',
    badgeTier: 'gold',
    badgeIcon: '✨',
    earnedAt: '24 phút trước',
    idempotencyKey: 'EVT-SCAN100-LRN20811-20260910',
    isEquippedFeatured: true,
    status: 'valid',
  },
  {
    id: 'rec-003',
    learnerId: 'lrn-38491',
    learnerName: 'Lê Minh Khang',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&h=120&fit=crop',
    email: 'khang.le@example.com',
    badgeId: 'bdg-quiz-01',
    badgeCode: 'BDG-QUIZ-10',
    badgeName: 'Thiện Xạ Trắc Nghiệm',
    badgeTier: 'silver',
    badgeIcon: '🎯',
    earnedAt: '48 phút trước',
    idempotencyKey: 'EVT-QUIZ10-LRN38491-20260910',
    isEquippedFeatured: false,
    status: 'valid',
  },
  {
    id: 'rec-004',
    learnerId: 'lrn-49201',
    learnerName: 'Phạm Hồng Nhung',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&h=120&fit=crop',
    email: 'nhung.pham@example.com',
    badgeId: 'bdg-sec-01',
    badgeCode: 'BDG-NIGHT-01',
    badgeName: 'Cú Đêm Chăm Chỉ',
    badgeTier: 'gold',
    badgeIcon: '🦉',
    earnedAt: '02:14 sáng hôm nay',
    idempotencyKey: 'EVT-NIGHT01-LRN49201-20260910',
    isEquippedFeatured: true,
    status: 'valid',
  },
  {
    id: 'rec-005',
    learnerId: 'lrn-55209',
    learnerName: 'Đặng Tuấn Kiệt',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop',
    email: 'kiet.dang@example.com',
    badgeId: 'bdg-leag-01',
    badgeCode: 'BDG-LEAG-01',
    badgeName: 'Đỉnh Cao Vinh Quang',
    badgeTier: 'diamond',
    badgeIcon: '👑',
    earnedAt: 'Hôm qua, 23:59',
    idempotencyKey: 'EVT-LEAG01-LRN55209-20260909',
    isEquippedFeatured: true,
    status: 'valid',
  },
  {
    id: 'rec-006',
    learnerId: 'lrn-66381',
    learnerName: 'Bùi Thảo Vy',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&h=120&fit=crop',
    email: 'vy.bui@example.com',
    badgeId: 'bdg-strk-02',
    badgeCode: 'BDG-STRK-30',
    badgeName: 'Thói Quen Vàng',
    badgeTier: 'silver',
    badgeIcon: '⚡',
    earnedAt: 'Hôm qua, 18:30',
    idempotencyKey: 'EVT-STRK30-LRN66381-20260909',
    isEquippedFeatured: true,
    status: 'valid',
  },
  {
    id: 'rec-007',
    learnerId: 'lrn-77412',
    learnerName: 'Hoàng Quốc Bảo',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop',
    email: 'bao.hoang@example.com',
    badgeId: 'bdg-voc-01',
    badgeCode: 'BDG-VOC-50',
    badgeName: 'Vốn Từ Khởi Sắc',
    badgeTier: 'bronze',
    badgeIcon: '🌱',
    earnedAt: 'Hôm qua, 14:15',
    idempotencyKey: 'EVT-VOC50-LRN77412-20260909',
    isEquippedFeatured: false,
    status: 'valid',
  },
  {
    id: 'rec-008',
    learnerId: 'lrn-99882',
    learnerName: 'Vũ Đức Thịnh (Nghi vấn)',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop',
    email: 'thinh.vu@cheat.bot',
    badgeId: 'bdg-strk-04',
    badgeCode: 'BDG-STRK-365',
    badgeName: 'Huyền Thoại Bất Tử',
    badgeTier: 'diamond',
    badgeIcon: '💎',
    earnedAt: '2 ngày trước',
    idempotencyKey: 'EVT-CHEAT-LRN99882-20260908',
    isEquippedFeatured: false,
    status: 'revoked',
    revokedReason: 'Phát hiện can thiệp đồng hồ hệ thống trên thiết bị di động (Anti-Cheat Revocation)',
  },
];
