// ====================================================
// SNAPVOCAB LEARNERS MOCK DATA
// Source of Truth: docs/design/design.md & docs/spec/
// ====================================================

import {
  LearnerProfile,
  StreakRecoveryRequest,
  LearnerAuditLogEntry,
} from './types';

export const INITIAL_LEARNERS: LearnerProfile[] = [
  {
    id: 'USR-10824',
    email: 'minh.nguyen@gmail.com',
    fullName: 'Nguyễn Quang Minh',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'active',
    cefrLevel: 'B2',
    joinedAt: '2025-11-12T08:30:00Z',
    lastActiveAt: '2026-09-11T07:45:00Z',
    appVersion: 'v1.4.2',
    devicePlatform: 'ios',
    deviceModel: 'iPhone 15 Pro',
    fsrs: {
      totalDecks: 8,
      totalNotes: 384,
      totalCards: 768,
      cardsNew: 42,
      cardsLearning: 96,
      cardsReview: 210,
      cardsMastered: 420,
      dueCardsToday: 28,
      retentionRate: 91.5,
      avgStabilityDays: 34.2,
      streakDaysConsistent: 56,
    },
    streak: {
      currentStreak: 56,
      maxStreak: 56,
      streakShields: 2,
      isFrozenToday: false,
      lastActiveDate: '2026-09-11',
      isAtRisk: false,
      recoveredCount: 0,
    },
    economy: {
      coins: 3420,
      gems: 185,
      totalXp: 18450,
      weeklyXp: 1240,
      league: 'diamond',
      leagueRank: 2,
      cohortId: 'COHORT-DIA-08',
      equippedTitle: '[Chiến Thần FSRS]',
      unlockedBadgesCount: 14,
      equippedBadgeIcons: ['🔥', '💎', '📚'],
      dailyScanQuota: 20,
      scansUsedToday: 8,
    },
    recentScans: [
      {
        id: 'SCN-991',
        imageUrl: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=200&auto=format&fit=crop&q=80',
        detectedObject: 'coffee cup',
        mappedWord: 'mug',
        confidenceScore: 0.96,
        timestamp: '2026-09-11T07:32:00Z',
        isSavedToDeck: true,
        status: 'SUCCESS',
      },
      {
        id: 'SCN-990',
        imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=200&auto=format&fit=crop&q=80',
        detectedObject: 'laptop keyboard',
        mappedWord: 'keyboard',
        confidenceScore: 0.94,
        timestamp: '2026-09-10T14:15:00Z',
        isSavedToDeck: true,
        status: 'SUCCESS',
      },
    ],
    recentReviews: [
      {
        id: 'REV-401',
        word: 'resilient',
        cefr: 'C1',
        rating: 3,
        ratingLabel: 'Good',
        reviewedAt: '2026-09-11T07:40:00Z',
        intervalDays: 14,
        stabilityScore: 18.4,
      },
      {
        id: 'REV-400',
        word: 'meticulous',
        cefr: 'B2',
        rating: 4,
        ratingLabel: 'Easy',
        reviewedAt: '2026-09-11T07:38:00Z',
        intervalDays: 28,
        stabilityScore: 35.1,
      },
    ],
    auditHistory: [
      {
        id: 'AUD-001',
        learnerId: 'USR-10824',
        learnerName: 'Nguyễn Quang Minh',
        action: 'QUOTA_ADJUSTED',
        operatorName: 'Admin Duyệt Viên',
        ticketId: 'TK-2026-1002',
        timestamp: '2026-09-01T10:00:00Z',
        details: 'Cấp thêm 5 lượt AI Scan trong ngày sự kiện Back to School',
        previousValue: '20 lượt',
        newValue: '25 lượt',
        reason: 'Khuyến khích học viên tích cực tham gia sự kiện',
      },
    ],
  },
  {
    id: 'USR-10825',
    email: 'lan.hoang@outlook.com',
    fullName: 'Hoàng Thị Lan',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'active',
    cefrLevel: 'C1',
    joinedAt: '2025-08-20T14:10:00Z',
    lastActiveAt: '2026-09-10T22:15:00Z',
    appVersion: 'v1.4.2',
    devicePlatform: 'ios',
    deviceModel: 'iPhone 14',
    fsrs: {
      totalDecks: 12,
      totalNotes: 620,
      totalCards: 1240,
      cardsNew: 20,
      cardsLearning: 110,
      cardsReview: 310,
      cardsMastered: 800,
      dueCardsToday: 45,
      retentionRate: 94.8,
      avgStabilityDays: 48.6,
      streakDaysConsistent: 142,
    },
    streak: {
      currentStreak: 142,
      maxStreak: 142,
      streakShields: 3,
      isFrozenToday: false,
      lastActiveDate: '2026-09-10',
      isAtRisk: true, // Chưa học hôm nay
      recoveredCount: 0,
    },
    economy: {
      coins: 8950,
      gems: 410,
      totalXp: 42300,
      weeklyXp: 860,
      league: 'diamond',
      leagueRank: 5,
      cohortId: 'COHORT-DIA-08',
      equippedTitle: '[Bậc Thầy Scan]',
      unlockedBadgesCount: 22,
      equippedBadgeIcons: ['👑', '⚡', '🦉'],
      dailyScanQuota: 20,
      scansUsedToday: 0,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [],
  },
  {
    id: 'USR-10826',
    email: 'ducanh.tran@gmail.com',
    fullName: 'Trần Đức Anh',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'active',
    cefrLevel: 'B1',
    joinedAt: '2026-01-05T09:00:00Z',
    lastActiveAt: '2026-09-09T18:20:00Z',
    appVersion: 'v1.4.1',
    devicePlatform: 'android',
    deviceModel: 'Xiaomi Redmi Note 13',
    fsrs: {
      totalDecks: 4,
      totalNotes: 140,
      totalCards: 280,
      cardsNew: 30,
      cardsLearning: 70,
      cardsReview: 90,
      cardsMastered: 90,
      dueCardsToday: 18,
      retentionRate: 83.2,
      avgStabilityDays: 16.8,
      streakDaysConsistent: 0,
    },
    streak: {
      currentStreak: 0, // Vừa đứt streak 38 ngày
      maxStreak: 38,
      streakShields: 0,
      isFrozenToday: false,
      lastActiveDate: '2026-09-09',
      isAtRisk: false,
      recoveredCount: 0,
    },
    economy: {
      coins: 1200,
      gems: 45,
      totalXp: 6800,
      weeklyXp: 180,
      league: 'gold',
      leagueRank: 19,
      cohortId: 'COHORT-GLD-12',
      equippedTitle: undefined,
      unlockedBadgesCount: 7,
      equippedBadgeIcons: ['⭐'],
      dailyScanQuota: 20,
      scansUsedToday: 0,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [],
  },
  {
    id: 'USR-10827',
    email: 'thu.ha.le@edu.vn',
    fullName: 'Lê Thu Hà',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'suspended',
    cefrLevel: 'A2',
    joinedAt: '2026-04-18T11:20:00Z',
    lastActiveAt: '2026-09-08T03:12:00Z',
    appVersion: 'v1.4.0',
    devicePlatform: 'android',
    deviceModel: 'Samsung Galaxy A54',
    fsrs: {
      totalDecks: 2,
      totalNotes: 65,
      totalCards: 130,
      cardsNew: 10,
      cardsLearning: 40,
      cardsReview: 50,
      cardsMastered: 30,
      dueCardsToday: 0,
      retentionRate: 72.1,
      avgStabilityDays: 9.4,
      streakDaysConsistent: 0,
    },
    streak: {
      currentStreak: 0,
      maxStreak: 12,
      streakShields: 0,
      isFrozenToday: false,
      lastActiveDate: '2026-09-08',
      isAtRisk: false,
      recoveredCount: 0,
    },
    economy: {
      coins: 250,
      gems: 5,
      totalXp: 2100,
      weeklyXp: 0,
      league: 'silver',
      leagueRank: 28,
      cohortId: 'COHORT-SLV-04',
      equippedTitle: undefined,
      unlockedBadgesCount: 3,
      equippedBadgeIcons: [],
      dailyScanQuota: 20,
      scansUsedToday: 0,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [
      {
        id: 'AUD-002',
        learnerId: 'USR-10827',
        learnerName: 'Lê Thu Hà',
        action: 'ACCOUNT_BANNED',
        operatorName: 'Bảo Mật Hệ Thống',
        ticketId: 'TK-2026-8812',
        timestamp: '2026-09-08T04:00:00Z',
        details: 'Khóa tài khoản 30 ngày do sử dụng script tự động giải Flashcard',
        previousValue: 'active',
        newValue: 'suspended',
        reason: 'Phát hiện macro giải 200 thẻ trong 12 giây, bất thường tốc độ',
      },
    ],
    banInfo: {
      bannedAt: '2026-09-08T04:00:00Z',
      bannedBy: 'Security Audit Bot',
      reason: 'Lạm dụng công cụ tự động (Botting / Macro) cày XP giải đấu',
      banDuration: '30d',
    },
  },
  {
    id: 'USR-10828',
    email: 'tuan.kiet@vnn.vn',
    fullName: 'Võ Tuấn Kiệt',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'active',
    cefrLevel: 'A1',
    joinedAt: '2026-08-25T16:40:00Z',
    lastActiveAt: '2026-09-11T06:50:00Z',
    appVersion: 'v1.4.2',
    devicePlatform: 'android',
    deviceModel: 'Oppo Reno 10',
    fsrs: {
      totalDecks: 2,
      totalNotes: 45,
      totalCards: 90,
      cardsNew: 15,
      cardsLearning: 35,
      cardsReview: 25,
      cardsMastered: 15,
      dueCardsToday: 12,
      retentionRate: 88.0,
      avgStabilityDays: 7.2,
      streakDaysConsistent: 14,
    },
    streak: {
      currentStreak: 14,
      maxStreak: 14,
      streakShields: 1,
      isFrozenToday: false,
      lastActiveDate: '2026-09-11',
      isAtRisk: false,
      recoveredCount: 0,
    },
    economy: {
      coins: 820,
      gems: 30,
      totalXp: 1650,
      weeklyXp: 420,
      league: 'silver',
      leagueRank: 6,
      cohortId: 'COHORT-SLV-04',
      equippedTitle: undefined,
      unlockedBadgesCount: 4,
      equippedBadgeIcons: ['🌱'],
      dailyScanQuota: 20,
      scansUsedToday: 15,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [],
  },
  {
    id: 'USR-10829',
    email: 'phuong.thao.dang@techcorp.io',
    fullName: 'Đặng Phương Thảo',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'active',
    cefrLevel: 'B2',
    joinedAt: '2025-10-02T07:15:00Z',
    lastActiveAt: '2026-09-11T08:00:00Z',
    appVersion: 'v1.4.2',
    devicePlatform: 'ios',
    deviceModel: 'iPhone 13 mini',
    fsrs: {
      totalDecks: 6,
      totalNotes: 310,
      totalCards: 620,
      cardsNew: 25,
      cardsLearning: 85,
      cardsReview: 160,
      cardsMastered: 350,
      dueCardsToday: 22,
      retentionRate: 92.4,
      avgStabilityDays: 31.0,
      streakDaysConsistent: 78,
    },
    streak: {
      currentStreak: 78,
      maxStreak: 78,
      streakShields: 2,
      isFrozenToday: false,
      lastActiveDate: '2026-09-11',
      isAtRisk: false,
      recoveredCount: 1,
    },
    economy: {
      coins: 4600,
      gems: 230,
      totalXp: 24800,
      weeklyXp: 1100,
      league: 'ruby',
      leagueRank: 3,
      cohortId: 'COHORT-RBY-02',
      equippedTitle: '[Thợ Săn Từ Vựng]',
      unlockedBadgesCount: 16,
      equippedBadgeIcons: ['🏹', '🦊', '⭐'],
      dailyScanQuota: 20,
      scansUsedToday: 6,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [
      {
        id: 'AUD-003',
        learnerId: 'USR-10829',
        learnerName: 'Đặng Phương Thảo',
        action: 'STREAK_RECOVERED',
        operatorName: 'Support Agent Anh',
        ticketId: 'TK-2026-7731',
        timestamp: '2026-07-20T14:30:00Z',
        details: 'Khôi phục chuỗi Streak từ 0 lên 45 ngày do lỗi máy chủ',
        previousValue: '0 ngày',
        newValue: '45 ngày',
        reason: 'Sự cố mất điện trung tâm dữ liệu gây ngắt phiên học lúc 23:50',
      },
    ],
  },
  {
    id: 'USR-10830',
    email: 'huy.hoang.it@gmail.com',
    fullName: 'Hoàng Quốc Huy',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'unverified',
    cefrLevel: 'A1',
    joinedAt: '2026-09-10T19:22:00Z',
    lastActiveAt: '2026-09-10T19:25:00Z',
    appVersion: 'v1.4.2',
    devicePlatform: 'android',
    deviceModel: 'Samsung Galaxy S22',
    fsrs: {
      totalDecks: 1,
      totalNotes: 5,
      totalCards: 10,
      cardsNew: 10,
      cardsLearning: 0,
      cardsReview: 0,
      cardsMastered: 0,
      dueCardsToday: 5,
      retentionRate: 0,
      avgStabilityDays: 1.0,
      streakDaysConsistent: 0,
    },
    streak: {
      currentStreak: 0,
      maxStreak: 0,
      streakShields: 0,
      isFrozenToday: false,
      lastActiveDate: '2026-09-10',
      isAtRisk: false,
      recoveredCount: 0,
    },
    economy: {
      coins: 50,
      gems: 0,
      totalXp: 50,
      weeklyXp: 50,
      league: 'bronze',
      leagueRank: 24,
      cohortId: 'COHORT-BRZ-19',
      equippedTitle: undefined,
      unlockedBadgesCount: 1,
      equippedBadgeIcons: [],
      dailyScanQuota: 20,
      scansUsedToday: 1,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [],
  },
  {
    id: 'USR-10831',
    email: 'thanh.truc.vu@gmail.com',
    fullName: 'Vũ Thanh Trúc',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'active',
    cefrLevel: 'B1',
    joinedAt: '2026-02-14T10:05:00Z',
    lastActiveAt: '2026-09-11T07:10:00Z',
    appVersion: 'v1.4.2',
    devicePlatform: 'ios',
    deviceModel: 'iPhone 12',
    fsrs: {
      totalDecks: 5,
      totalNotes: 190,
      totalCards: 380,
      cardsNew: 20,
      cardsLearning: 60,
      cardsReview: 100,
      cardsMastered: 200,
      dueCardsToday: 16,
      retentionRate: 87.6,
      avgStabilityDays: 22.4,
      streakDaysConsistent: 29,
    },
    streak: {
      currentStreak: 29,
      maxStreak: 29,
      streakShields: 1,
      isFrozenToday: false,
      lastActiveDate: '2026-09-11',
      isAtRisk: false,
      recoveredCount: 0,
    },
    economy: {
      coins: 2150,
      gems: 90,
      totalXp: 9800,
      weeklyXp: 670,
      league: 'platinum',
      leagueRank: 8,
      cohortId: 'COHORT-PLT-07',
      equippedTitle: '[Chiến Binh Kiên Trì]',
      unlockedBadgesCount: 9,
      equippedBadgeIcons: ['🛡️', '✨'],
      dailyScanQuota: 20,
      scansUsedToday: 4,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [],
  },
  {
    id: 'USR-10832',
    email: 'khang.nguyen.dev@gmail.com',
    fullName: 'Nguyễn Duy Khang',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'active',
    cefrLevel: 'C2',
    joinedAt: '2025-07-01T12:00:00Z',
    lastActiveAt: '2026-09-11T01:30:00Z',
    appVersion: 'v1.4.2',
    devicePlatform: 'ios',
    deviceModel: 'iPhone 15 Pro Max',
    fsrs: {
      totalDecks: 15,
      totalNotes: 1150,
      totalCards: 2300,
      cardsNew: 50,
      cardsLearning: 150,
      cardsReview: 400,
      cardsMastered: 1700,
      dueCardsToday: 34,
      retentionRate: 96.2,
      avgStabilityDays: 62.5,
      streakDaysConsistent: 184,
    },
    streak: {
      currentStreak: 184,
      maxStreak: 184,
      streakShields: 3,
      isFrozenToday: false,
      lastActiveDate: '2026-09-11',
      isAtRisk: false,
      recoveredCount: 0,
    },
    economy: {
      coins: 16800,
      gems: 890,
      totalXp: 78900,
      weeklyXp: 2150,
      league: 'diamond',
      leagueRank: 1,
      cohortId: 'COHORT-DIA-08',
      equippedTitle: '[Huyền Thoại Từ Vựng]',
      unlockedBadgesCount: 26,
      equippedBadgeIcons: ['🏆', '🌌', '⚡'],
      dailyScanQuota: 25,
      scansUsedToday: 18,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [],
  },
  {
    id: 'USR-10833',
    email: 'mai.anh.tran@gmail.com',
    fullName: 'Trần Mai Anh',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'active',
    cefrLevel: 'A2',
    joinedAt: '2026-05-10T14:30:00Z',
    lastActiveAt: '2026-09-10T11:45:00Z',
    appVersion: 'v1.4.1',
    devicePlatform: 'android',
    deviceModel: 'Samsung Galaxy A34',
    fsrs: {
      totalDecks: 3,
      totalNotes: 85,
      totalCards: 170,
      cardsNew: 20,
      cardsLearning: 50,
      cardsReview: 60,
      cardsMastered: 40,
      dueCardsToday: 14,
      retentionRate: 84.5,
      avgStabilityDays: 11.2,
      streakDaysConsistent: 21,
    },
    streak: {
      currentStreak: 21,
      maxStreak: 21,
      streakShields: 1,
      isFrozenToday: false,
      lastActiveDate: '2026-09-10',
      isAtRisk: true, // Cảnh báo nguy cơ đứt streak hôm nay
      recoveredCount: 0,
    },
    economy: {
      coins: 1450,
      gems: 60,
      totalXp: 4100,
      weeklyXp: 390,
      league: 'silver',
      leagueRank: 14,
      cohortId: 'COHORT-SLV-04',
      equippedTitle: undefined,
      unlockedBadgesCount: 5,
      equippedBadgeIcons: ['🌱', '📚'],
      dailyScanQuota: 20,
      scansUsedToday: 3,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [],
  },
  {
    id: 'USR-10834',
    email: 'gia.bao.pham@yahoo.com',
    fullName: 'Phạm Gia Bảo',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'active',
    cefrLevel: 'B2',
    joinedAt: '2025-12-01T08:00:00Z',
    lastActiveAt: '2026-09-11T05:20:00Z',
    appVersion: 'v1.4.2',
    devicePlatform: 'ios',
    deviceModel: 'iPhone 14 Pro',
    fsrs: {
      totalDecks: 7,
      totalNotes: 410,
      totalCards: 820,
      cardsNew: 30,
      cardsLearning: 90,
      cardsReview: 220,
      cardsMastered: 480,
      dueCardsToday: 26,
      retentionRate: 90.8,
      avgStabilityDays: 32.0,
      streakDaysConsistent: 64,
    },
    streak: {
      currentStreak: 64,
      maxStreak: 64,
      streakShields: 2,
      isFrozenToday: false,
      lastActiveDate: '2026-09-11',
      isAtRisk: false,
      recoveredCount: 0,
    },
    economy: {
      coins: 3900,
      gems: 210,
      totalXp: 21400,
      weeklyXp: 980,
      league: 'ruby',
      leagueRank: 4,
      cohortId: 'COHORT-RBY-02',
      equippedTitle: '[Cao Thủ Thẻ Nhớ]',
      unlockedBadgesCount: 15,
      equippedBadgeIcons: ['🔥', '✨'],
      dailyScanQuota: 20,
      scansUsedToday: 9,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [],
  },
  {
    id: 'USR-10835',
    email: 'yen.nhi.ngo@gmail.com',
    fullName: 'Ngô Yến Nhi',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    role: 'ROLE_LEARNER',
    status: 'suspended',
    cefrLevel: 'B1',
    joinedAt: '2026-03-22T09:40:00Z',
    lastActiveAt: '2026-09-07T14:10:00Z',
    appVersion: 'v1.4.1',
    devicePlatform: 'android',
    deviceModel: 'Realme 11',
    fsrs: {
      totalDecks: 4,
      totalNotes: 160,
      totalCards: 320,
      cardsNew: 20,
      cardsLearning: 60,
      cardsReview: 90,
      cardsMastered: 150,
      dueCardsToday: 0,
      retentionRate: 81.0,
      avgStabilityDays: 14.5,
      streakDaysConsistent: 0,
    },
    streak: {
      currentStreak: 0,
      maxStreak: 34,
      streakShields: 0,
      isFrozenToday: false,
      lastActiveDate: '2026-09-07',
      isAtRisk: false,
      recoveredCount: 0,
    },
    economy: {
      coins: 1600,
      gems: 40,
      totalXp: 7100,
      weeklyXp: 0,
      league: 'gold',
      leagueRank: 30,
      cohortId: 'COHORT-GLD-12',
      equippedTitle: undefined,
      unlockedBadgesCount: 8,
      equippedBadgeIcons: [],
      dailyScanQuota: 20,
      scansUsedToday: 0,
    },
    recentScans: [],
    recentReviews: [],
    auditHistory: [
      {
        id: 'AUD-004',
        learnerId: 'USR-10835',
        learnerName: 'Ngô Yến Nhi',
        action: 'ACCOUNT_BANNED',
        operatorName: 'Admin Duyệt Viên',
        ticketId: 'TK-2026-8902',
        timestamp: '2026-09-07T15:00:00Z',
        details: 'Khóa tài khoản 7 ngày do spam liên tục 50 báo cáo lỗi sai sự thật',
        previousValue: 'active',
        newValue: 'suspended',
        reason: 'Lạm dụng tính năng báo cáo AI scan để gây nghẽn hàng đợi kiểm duyệt',
      },
    ],
    banInfo: {
      bannedAt: '2026-09-07T15:00:00Z',
      bannedBy: 'Admin Duyệt Viên',
      reason: 'Spam báo cáo sai sự thật làm tắc nghẽn Feedback Queue P1',
      banDuration: '7d',
    },
  },
];

// ====================================================
// INITIAL PENDING & RESOLVED STREAK RECOVERY TICKETS
// ====================================================

export const INITIAL_STREAK_REQUESTS: StreakRecoveryRequest[] = [
  {
    id: 'REQ-STRK-101',
    ticketId: 'TK-2026-8941',
    learnerId: 'USR-10826',
    learnerName: 'Trần Đức Anh',
    learnerEmail: 'ducanh.tran@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    lostStreakDays: 38,
    targetStreakDays: 39,
    lossReason: 'app_crash',
    lossReasonLabel: 'Lỗi văng ứng dụng khi cập nhật v1.4.2',
    proofNote: 'Học viên học lúc 23:45 ngày 09/09, sau khi bấm nút Good ở thẻ cuối thì app bị crash liên tục, không gửi được log lên máy chủ.',
    status: 'pending',
    requestedAt: '2026-09-10T08:15:00Z',
  },
  {
    id: 'REQ-STRK-102',
    ticketId: 'TK-2026-9012',
    learnerId: 'USR-10833',
    learnerName: 'Trần Mai Anh',
    learnerEmail: 'mai.anh.tran@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80',
    lostStreakDays: 21,
    targetStreakDays: 22,
    lossReason: 'timezone_bug',
    lossReasonLabel: 'Lệch múi giờ chuyến bay Hà Nội - Tokyo',
    proofNote: 'Bay từ Hà Nội (GMT+7) sang Tokyo (GMT+9), điện thoại tự động nhảy giờ sang ngày mới trước khi kịp làm bài ôn tập 10 phút cuối ngày.',
    status: 'pending',
    requestedAt: '2026-09-10T14:30:00Z',
  },
  {
    id: 'REQ-STRK-103',
    ticketId: 'TK-2026-9140',
    learnerId: 'USR-10828',
    learnerName: 'Võ Tuấn Kiệt',
    learnerEmail: 'tuan.kiet@vnn.vn',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    lostStreakDays: 14,
    targetStreakDays: 15,
    lossReason: 'server_downtime',
    lossReasonLabel: 'Máy chủ bảo trì mạng thanh toán R2/S3',
    proofNote: 'Thời điểm 23:30 máy chủ trả mã lỗi 502 Bad Gateway trong 45 phút, không thể kết nối sync flashcard review log.',
    status: 'pending',
    requestedAt: '2026-09-11T06:10:00Z',
  },
  {
    id: 'REQ-STRK-098',
    ticketId: 'TK-2026-7731',
    learnerId: 'USR-10829',
    learnerName: 'Đặng Phương Thảo',
    learnerEmail: 'phuong.thao.dang@techcorp.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    lostStreakDays: 45,
    targetStreakDays: 46,
    lossReason: 'server_downtime',
    lossReasonLabel: 'Sự cố mất điện trung tâm dữ liệu',
    proofNote: 'Đã xác minh qua log hệ thống: phiên học bị ngắt kết nối lúc 23:50.',
    status: 'approved',
    requestedAt: '2026-07-20T10:00:00Z',
    resolvedAt: '2026-07-20T14:30:00Z',
    resolvedBy: 'Support Agent Anh',
    resolutionReason: 'Sự cố hạ tầng máy chủ được xác nhận, khôi phục chuỗi 45 ngày.',
  },
];

// ====================================================
// INITIAL MASTER AUDIT LEDGER
// ====================================================

export const INITIAL_AUDIT_LOGS: LearnerAuditLogEntry[] = [
  {
    id: 'AUD-901',
    learnerId: 'USR-10829',
    learnerName: 'Đặng Phương Thảo',
    action: 'STREAK_RECOVERED',
    operatorName: 'Support Agent Anh',
    ticketId: 'TK-2026-7731',
    timestamp: '2026-07-20T14:30:00Z',
    details: 'Khôi phục chuỗi Streak từ 0 lên 45 ngày',
    previousValue: '0 ngày',
    newValue: '45 ngày',
    reason: 'Sự cố mất điện trung tâm dữ liệu gây ngắt phiên học lúc 23:50',
  },
  {
    id: 'AUD-902',
    learnerId: 'USR-10827',
    learnerName: 'Lê Thu Hà',
    action: 'ACCOUNT_BANNED',
    operatorName: 'Bảo Mật Hệ Thống',
    ticketId: 'TK-2026-8812',
    timestamp: '2026-09-08T04:00:00Z',
    details: 'Khóa tài khoản 30 ngày',
    previousValue: 'Trạng thái: active',
    newValue: 'Trạng thái: suspended (30d)',
    reason: 'Phát hiện macro giải 200 thẻ trong 12 giây, bất thường tốc độ',
  },
  {
    id: 'AUD-903',
    learnerId: 'USR-10835',
    learnerName: 'Ngô Yến Nhi',
    action: 'ACCOUNT_BANNED',
    operatorName: 'Admin Duyệt Viên',
    ticketId: 'TK-2026-8902',
    timestamp: '2026-09-07T15:00:00Z',
    details: 'Khóa tài khoản 7 ngày',
    previousValue: 'Trạng thái: active',
    newValue: 'Trạng thái: suspended (7d)',
    reason: 'Lạm dụng tính năng báo cáo AI scan để gây nghẽn hàng đợi kiểm duyệt',
  },
  {
    id: 'AUD-904',
    learnerId: 'USR-10824',
    learnerName: 'Nguyễn Quang Minh',
    action: 'QUOTA_ADJUSTED',
    operatorName: 'Admin Duyệt Viên',
    ticketId: 'TK-2026-1002',
    timestamp: '2026-09-01T10:00:00Z',
    details: 'Cấp thêm 5 lượt AI Scan trong ngày',
    previousValue: '20 lượt',
    newValue: '25 lượt',
    reason: 'Khuyến khích học viên tích cực tham gia sự kiện Back to School',
  },
  {
    id: 'AUD-905',
    learnerId: 'USR-10832',
    learnerName: 'Nguyễn Duy Khang',
    action: 'CURRENCY_COMPENSATED',
    operatorName: 'Support Agent Minh',
    ticketId: 'TK-2026-6641',
    timestamp: '2026-08-15T09:20:00Z',
    details: 'Cấp bù 50 Gems do lỗi mua rương báu bị trừ đúp',
    previousValue: '840 gems',
    newValue: '890 gems',
    reason: 'Hệ thống billing trừ 2 lần do mạng lag khi mua Streak Freeze Chest',
  },
];
