import { Collection, Topic, TopicItem, SystemDeck, DeckNote } from './types';

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-toeic',
    name: 'TOEIC 600 Essential Vocabulary',
    nameVi: 'Bộ Từ Vựng TOEIC 600 Điểm Thiết Yếu',
    slug: 'toeic-600-essential',
    description: 'Từ vựng cốt lõi thường xuất hiện trong các bài thi TOEIC Listening & Reading, tập trung vào môi trường làm việc quốc tế.',
    icon: '💼',
    topicCount: 5,
    totalWords: 320,
    status: 'published',
    orderIndex: 1,
    updatedAt: '2026-09-08T10:30:00Z',
  },
  {
    id: 'col-daily',
    name: 'Daily Life & Social Essentials',
    nameVi: 'Giao Tiếp & Đời Sống Hàng Ngày',
    slug: 'daily-life-social',
    description: 'Các từ vựng thông dụng xoay quanh cuộc sống đời thường, mua sắm, ẩm thực, gia đình và phương tiện đi lại.',
    icon: '☕',
    topicCount: 4,
    totalWords: 240,
    status: 'published',
    orderIndex: 2,
    updatedAt: '2026-09-09T14:15:00Z',
  },
  {
    id: 'col-business',
    name: 'Business & Corporate Operations',
    nameVi: 'Thương Mại & Quản Trị Doanh Nghiệp',
    slug: 'business-corporate',
    description: 'Thuật ngữ chuyên sâu trong đàm phán hợp đồng, tài chính kế toán, nhân sự và chiến lược tiếp thị đa kênh.',
    icon: '📊',
    topicCount: 4,
    totalWords: 190,
    status: 'published',
    orderIndex: 3,
    updatedAt: '2026-09-07T09:00:00Z',
  },
  {
    id: 'col-academic',
    name: 'IELTS Academic & Critical Mindset',
    nameVi: 'IELTS Học Thuật & Tư Duy Phản Biện',
    slug: 'ielts-academic',
    description: 'Từ vựng cấp độ B2-C1 phục vụ viết luận IELTS Writing Task 2, thảo luận học thuật và diễn giải số liệu.',
    icon: '🎓',
    topicCount: 3,
    totalWords: 150,
    status: 'published',
    orderIndex: 4,
    updatedAt: '2026-09-06T16:40:00Z',
  },
  {
    id: 'col-travel',
    name: 'Travel, Culture & Hospitality',
    nameVi: 'Du Lịch, Khách Sạn & Văn Hóa',
    slug: 'travel-hospitality',
    description: 'Chủ đề phục vụ du lịch quốc tế, đặt vé máy bay, nhận phòng khách sạn, giao lưu văn hóa và xử lý tình huống khẩn cấp.',
    icon: '✈️',
    topicCount: 3,
    totalWords: 110,
    status: 'draft',
    orderIndex: 5,
    updatedAt: '2026-09-05T11:20:00Z',
  },
];

export const INITIAL_TOPICS: Topic[] = [
  // Topics under col-toeic
  {
    id: 'top-toeic-office',
    collectionId: 'col-toeic',
    collectionName: 'TOEIC 600 Essential Vocabulary',
    name: 'Office & Workplace Communication',
    nameVi: 'Giao Tiếp & Văn Hóa Công Sở',
    slug: 'office-workplace',
    description: 'Từ vựng diễn tả hoạt động công sở, giao tiếp đồng nghiệp và sắp xếp công việc hành chính.',
    targetCefr: 'B1',
    icon: '🏢',
    wordCount: 85,
    activeLearnersCount: 3420,
    status: 'published',
    orderIndex: 1,
  },
  {
    id: 'top-toeic-meetings',
    collectionId: 'col-toeic',
    collectionName: 'TOEIC 600 Essential Vocabulary',
    parentId: 'top-toeic-office',
    name: 'Meetings & Presentations',
    nameVi: 'Họp Hành & Thuyết Trình Dự Án',
    slug: 'meetings-presentations',
    description: 'Thuật ngữ điều phối cuộc họp, biểu quyết, trình bày slide và giải đáp thắc mắc của đối tác.',
    targetCefr: 'B1',
    icon: '📽️',
    wordCount: 32,
    activeLearnersCount: 2890,
    status: 'published',
    orderIndex: 2,
  },
  {
    id: 'top-toeic-contracts',
    collectionId: 'col-toeic',
    collectionName: 'TOEIC 600 Essential Vocabulary',
    parentId: 'top-toeic-office',
    name: 'Contracts & Negotiations',
    nameVi: 'Hợp Đồng & Đàm Phán Thương Lượng',
    slug: 'contracts-negotiations',
    description: 'Các điều khoản hợp đồng, thỏa thuận bảo mật, bồi thường thiệt hại và gia hạn ký kết.',
    targetCefr: 'B2',
    icon: '📝',
    wordCount: 28,
    activeLearnersCount: 2150,
    status: 'published',
    orderIndex: 3,
  },
  {
    id: 'top-toeic-equipment',
    collectionId: 'col-toeic',
    collectionName: 'TOEIC 600 Essential Vocabulary',
    parentId: 'top-toeic-office',
    name: 'Office Tech & Supplies',
    nameVi: 'Thiết Bị Văn Phòng & Vật Tư',
    slug: 'office-tech-supplies',
    description: 'Máy móc in ấn, thiết bị mạng, đồ dùng văn phòng và xử lý sự cố thiết bị.',
    targetCefr: 'A2',
    icon: '🖨️',
    wordCount: 25,
    activeLearnersCount: 1840,
    status: 'published',
    orderIndex: 4,
  },
  {
    id: 'top-toeic-finance',
    collectionId: 'col-toeic',
    collectionName: 'TOEIC 600 Essential Vocabulary',
    name: 'Corporate Finance & Banking',
    nameVi: 'Tài Chính Doanh Nghiệp & Ngân Hàng',
    slug: 'finance-banking',
    description: 'Báo cáo doanh thu, ngân sách quý, hóa đơn thuế và giao dịch chuyển khoản tín dụng.',
    targetCefr: 'B2',
    icon: '💳',
    wordCount: 65,
    activeLearnersCount: 1950,
    status: 'published',
    orderIndex: 5,
  },

  // Topics under col-daily
  {
    id: 'top-daily-dining',
    collectionId: 'col-daily',
    collectionName: 'Daily Life & Social Essentials',
    name: 'Dining & Food Culture',
    nameVi: 'Ăn Uống & Văn Hóa Ẩm Thực',
    slug: 'dining-food-culture',
    description: 'Tên món ăn, dụng cụ nhà bếp, gia vị và cách giao tiếp khi đi ăn tại nhà hàng quán ăn.',
    targetCefr: 'A2',
    icon: '🍽️',
    wordCount: 75,
    activeLearnersCount: 4200,
    status: 'published',
    orderIndex: 1,
  },
  {
    id: 'top-daily-restaurant',
    collectionId: 'col-daily',
    collectionName: 'Daily Life & Social Essentials',
    parentId: 'top-daily-dining',
    name: 'Restaurant & Ordering',
    nameVi: 'Nhà Hàng & Gọi Món',
    slug: 'restaurant-ordering',
    description: 'Đặt bàn trước, gọi món ăn kèm, yêu cầu hóa đơn và phản hồi về chất lượng phục vụ.',
    targetCefr: 'A2',
    icon: '🛎️',
    wordCount: 38,
    activeLearnersCount: 3850,
    status: 'published',
    orderIndex: 2,
  },
  {
    id: 'top-daily-kitchen',
    collectionId: 'col-daily',
    collectionName: 'Daily Life & Social Essentials',
    parentId: 'top-daily-dining',
    name: 'Kitchenware & Utensils',
    nameVi: 'Đồ Dùng & Dụng Cụ Bếp',
    slug: 'kitchenware-utensils',
    description: 'Vật dụng nấu nướng, đồ gia dụng thường ngày như bình giữ nhiệt, dao gọt, chảo chiên.',
    targetCefr: 'A1',
    icon: '🍳',
    wordCount: 37,
    activeLearnersCount: 3210,
    status: 'published',
    orderIndex: 3,
  },
  {
    id: 'top-daily-wellness',
    collectionId: 'col-daily',
    collectionName: 'Daily Life & Social Essentials',
    name: 'Health & Daily Wellness',
    nameVi: 'Sức Khỏe & Thể Chất Hàng Ngày',
    slug: 'health-wellness',
    description: 'Triệu chứng bệnh thông thường, thói quen rèn luyện thể thao và dinh dưỡng lành mạnh.',
    targetCefr: 'B1',
    icon: '🧘',
    wordCount: 60,
    activeLearnersCount: 2640,
    status: 'published',
    orderIndex: 4,
  },

  // Topics under col-business
  {
    id: 'top-biz-hr',
    collectionId: 'col-business',
    collectionName: 'Business & Corporate Operations',
    name: 'HR & Talent Acquisition',
    nameVi: 'Tuyển Dụng & Phát Triển Nhân Tài',
    slug: 'hr-talent-acquisition',
    description: 'Phỏng vấn ứng viên, đánh giá KPI, chính sách đãi ngộ và đào tạo hội nhập nhân viên mới.',
    targetCefr: 'B2',
    icon: '👥',
    wordCount: 55,
    activeLearnersCount: 1680,
    status: 'published',
    orderIndex: 1,
  },
  {
    id: 'top-biz-marketing',
    collectionId: 'col-business',
    collectionName: 'Business & Corporate Operations',
    name: 'Brand & Digital Marketing',
    nameVi: 'Thương Hiệu & Tiếp Thị Số',
    slug: 'brand-digital-marketing',
    description: 'Chỉ số chuyển đổi ROI, chiến dịch quảng cáo mạng xã hội và định vị thương hiệu.',
    targetCefr: 'C1',
    icon: '📣',
    wordCount: 50,
    activeLearnersCount: 1420,
    status: 'review',
    orderIndex: 2,
  },

  // Topics under col-academic
  {
    id: 'top-acad-mindset',
    collectionId: 'col-academic',
    collectionName: 'IELTS Academic & Critical Mindset',
    name: 'Psychology & Mental Resilience',
    nameVi: 'Tâm Lý Học & Sự Kiên Cường',
    slug: 'psychology-resilience',
    description: 'Các từ vựng mô tả hành vi tâm lý, khả năng phục hồi tinh thần và nhận thức cảm xúc.',
    targetCefr: 'C1',
    icon: '🧠',
    wordCount: 45,
    activeLearnersCount: 1890,
    status: 'published',
    orderIndex: 1,
  },
  {
    id: 'top-acad-literature',
    collectionId: 'col-academic',
    collectionName: 'IELTS Academic & Critical Mindset',
    name: 'Literary & Nuanced English',
    nameVi: 'Văn Phong & Tiếng Anh Tinh Tế',
    slug: 'literary-nuanced-english',
    description: 'Từ ngữ hàm súc, giàu hình tượng và biểu cảm cao độ trong các tác phẩm văn học.',
    targetCefr: 'C2',
    icon: '📜',
    wordCount: 40,
    activeLearnersCount: 1120,
    status: 'draft',
    orderIndex: 2,
  },
];

export const INITIAL_TOPIC_ITEMS: TopicItem[] = [
  // Meetings & Presentations (top-toeic-meetings)
  {
    id: 'ti-001',
    topicId: 'top-toeic-meetings',
    topicName: 'Meetings & Presentations',
    word: 'agenda',
    phonetic: '/əˈdʒen.də/',
    partOfSpeech: 'noun',
    cefr: 'B1',
    definitionVi: 'chương trình nghị sự, lịch trình các nội dung cần bàn bạc trong cuộc họp',
    definitionEn: 'a list of matters to be discussed at a meeting',
    exampleEn: 'The first item on the agenda is the quarterly financial review.',
    exampleVi: 'Mục đầu tiên trong chương trình nghị sự là đánh giá tài chính quý.',
    audioUrl: 'https://actions.google.com/sounds/v1/speech/agenda.mp3',
    status: 'published',
    source: 'DICT',
    tags: ['meeting', 'schedule', 'office'],
    addedAt: '2026-09-08T11:00:00Z',
    orderIndex: 1,
  },
  {
    id: 'ti-002',
    topicId: 'top-toeic-meetings',
    topicName: 'Meetings & Presentations',
    word: 'collaborate',
    phonetic: '/kəˈlæb.ə.reɪt/',
    partOfSpeech: 'verb',
    cefr: 'B2',
    definitionVi: 'hợp tác, phối hợp làm việc cùng người khác hoặc phòng ban khác để đạt mục tiêu',
    definitionEn: 'to work with someone else for a special purpose',
    exampleEn: 'Two research teams decided to collaborate on the AI translation initiative.',
    exampleVi: 'Hai nhóm nghiên cứu đã quyết định phối hợp trong sáng kiến dịch thuật AI.',
    status: 'published',
    source: 'DICT',
    tags: ['teamwork', 'cooperation'],
    addedAt: '2026-09-08T11:05:00Z',
    orderIndex: 2,
  },
  {
    id: 'ti-003',
    topicId: 'top-toeic-meetings',
    topicName: 'Meetings & Presentations',
    word: 'consensus',
    phonetic: '/kənˈsen.səs/',
    partOfSpeech: 'noun',
    cefr: 'C1',
    definitionVi: 'sự đồng thuận, nhất trí ý kiến chung giữa các thành viên',
    definitionEn: 'a generally accepted opinion or decision among a group of people',
    exampleEn: 'The board finally reached a consensus after hours of vigorous debate.',
    exampleVi: 'Hội đồng quản trị cuối cùng đã đạt được sự đồng thuận sau nhiều giờ tranh luận sôi nổi.',
    status: 'published',
    source: 'TOPIC',
    tags: ['decision', 'formal'],
    addedAt: '2026-09-08T11:10:00Z',
    orderIndex: 3,
  },
  {
    id: 'ti-004',
    topicId: 'top-toeic-meetings',
    topicName: 'Meetings & Presentations',
    word: 'minutes',
    phonetic: '/ˈmɪn.ɪts/',
    partOfSpeech: 'noun',
    cefr: 'B1',
    definitionVi: 'biên bản cuộc họp (bản ghi chép chính thức các quyết định được thông qua)',
    definitionEn: 'the written record of what was said at a meeting',
    exampleEn: 'Will someone volunteer to take the minutes for today’s sprint planning?',
    exampleVi: 'Có ai xung phong ghi biên bản cho buổi lập kế hoạch sprint hôm nay không?',
    status: 'published',
    source: 'DICT',
    tags: ['office', 'document'],
    addedAt: '2026-09-08T11:15:00Z',
    orderIndex: 4,
  },
  {
    id: 'ti-005',
    topicId: 'top-toeic-meetings',
    topicName: 'Meetings & Presentations',
    word: 'adjourn',
    phonetic: '/əˈdʒɜːn/',
    partOfSpeech: 'verb',
    cefr: 'B2',
    definitionVi: 'hoãn lại, tạm ngừng cuộc họp để tiếp tục vào thời điểm khác',
    definitionEn: 'to have a pause or rest during a formal meeting or trial',
    exampleEn: 'The chairman proposed to adjourn the meeting until Friday morning.',
    exampleVi: 'Chủ tọa đề xuất tạm hoãn cuộc họp cho đến sáng thứ Sáu.',
    status: 'review',
    source: 'DICT',
    tags: ['formal', 'procedural'],
    addedAt: '2026-09-09T09:20:00Z',
    orderIndex: 5,
  },

  // Contracts & Negotiations (top-toeic-contracts)
  {
    id: 'ti-006',
    topicId: 'top-toeic-contracts',
    topicName: 'Contracts & Negotiations',
    word: 'negotiate',
    phonetic: '/nəˈɡəʊ.ʃi.eɪt/',
    partOfSpeech: 'verb',
    cefr: 'B2',
    definitionVi: 'thương lượng, đàm phán để đạt được thỏa thuận có lợi',
    definitionEn: 'to have formal discussions with someone in order to reach an agreement',
    exampleEn: 'The procurement manager managed to negotiate a 15% discount for bulk orders.',
    exampleVi: 'Trưởng phòng thu mua đã thương lượng thành công mức giảm giá 15% cho đơn hàng lớn.',
    status: 'published',
    source: 'DICT',
    tags: ['business', 'deal'],
    addedAt: '2026-09-07T14:00:00Z',
    orderIndex: 1,
  },
  {
    id: 'ti-007',
    topicId: 'top-toeic-contracts',
    topicName: 'Contracts & Negotiations',
    word: 'clause',
    phonetic: '/klɔːz/',
    partOfSpeech: 'noun',
    cefr: 'B2',
    definitionVi: 'điều khoản, điều mục riêng biệt trong một văn bản pháp lý hoặc hợp đồng',
    definitionEn: 'a particular part of a written legal document',
    exampleEn: 'Please review clause 4.2 carefully before signing the agreement.',
    exampleVi: 'Vui lòng xem lại điều khoản 4.2 thật kỹ trước khi ký kết thỏa thuận.',
    status: 'published',
    source: 'DICT',
    tags: ['legal', 'terms'],
    addedAt: '2026-09-07T14:10:00Z',
    orderIndex: 2,
  },
  {
    id: 'ti-008',
    topicId: 'top-toeic-contracts',
    topicName: 'Contracts & Negotiations',
    word: 'binding',
    phonetic: '/ˈbaɪn.dɪŋ/',
    partOfSpeech: 'adjective',
    cefr: 'B2',
    definitionVi: 'có tính ràng buộc pháp lý (buộc các bên phải tuân thủ nghiêm ngặt)',
    definitionEn: 'that cannot be legally avoided or stopped',
    exampleEn: 'Once signed by both representatives, the contract becomes legally binding.',
    exampleVi: 'Một khi được ký bởi cả hai đại diện, hợp đồng sẽ có tính ràng buộc pháp lý.',
    status: 'published',
    source: 'TOPIC',
    tags: ['legal'],
    addedAt: '2026-09-07T14:15:00Z',
    orderIndex: 3,
  },

  // Kitchenware & Utensils (top-daily-kitchen)
  {
    id: 'ti-009',
    topicId: 'top-daily-kitchen',
    topicName: 'Kitchenware & Utensils',
    word: 'thermos',
    phonetic: '/ˈθɜː.məs/',
    partOfSpeech: 'noun',
    cefr: 'B1',
    definitionVi: 'bình giữ nhiệt (dùng để giữ nước nóng hoặc lạnh trong thời gian dài)',
    definitionEn: 'a container that keeps liquids hot or cold',
    exampleEn: 'I always bring a thermos of hot green tea on winter camping trips.',
    exampleVi: 'Tôi luôn mang theo một bình giữ nhiệt trà xanh nóng trong những chuyến cắm trại mùa đông.',
    imageUrl: 'https://images.unsplash.com/photo-1570857502809-08184874388e?w=600&auto=format&fit=crop&q=80',
    status: 'review',
    source: 'SCAN',
    tags: ['kitchen', 'office', 'ai-scan-corrected'],
    addedAt: '2026-09-10T02:15:00Z',
    orderIndex: 1,
  },
  {
    id: 'ti-010',
    topicId: 'top-daily-kitchen',
    topicName: 'Kitchenware & Utensils',
    word: 'apple',
    phonetic: '/ˈæp.əl/',
    partOfSpeech: 'noun',
    cefr: 'A1',
    definitionVi: 'quả táo (trái cây vỏ đỏ hoặc xanh, cùi giòn, vị ngọt hoặc chua)',
    definitionEn: 'a round fruit with firm, white flesh and a green, red, or yellow skin',
    exampleEn: 'She peeled an apple and sliced it into pieces.',
    exampleVi: 'Cô ấy gọt vỏ một quả táo rồi cắt thành từng miếng nhỏ.',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop&q=80',
    status: 'published',
    source: 'DICT',
    tags: ['fruit', 'daily', 'basic'],
    addedAt: '2026-09-08T14:20:00Z',
    orderIndex: 2,
  },

  // Psychology & Mental Resilience (top-acad-mindset)
  {
    id: 'ti-011',
    topicId: 'top-acad-mindset',
    topicName: 'Psychology & Mental Resilience',
    word: 'resilient',
    phonetic: '/rɪˈzɪl.jənt/',
    partOfSpeech: 'adjective',
    cefr: 'C1',
    definitionVi: 'kiên cường, bất khuất; có khả năng phục hồi nhanh sau khó khăn hay nghịch cảnh',
    definitionEn: 'able to quickly become healthy, happy, or strong again after a difficult situation',
    exampleEn: 'Local businesses have been remarkably resilient despite economic hardship.',
    exampleVi: 'Các doanh nghiệp địa phương đã phục hồi một cách phi thường bất chấp khó khăn kinh tế.',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80',
    status: 'review',
    source: 'AI',
    tags: ['mindset', 'advanced', 'toefl'],
    addedAt: '2026-09-09T18:45:00Z',
    orderIndex: 1,
  },
  {
    id: 'ti-012',
    topicId: 'top-acad-mindset',
    topicName: 'Psychology & Mental Resilience',
    word: 'curious',
    phonetic: '/ˈkjʊə.ri.əs/',
    partOfSpeech: 'adjective',
    cefr: 'A2',
    definitionVi: 'tò mò, hiếu kỳ; mong muốn tìm hiểu và khám phá thế giới xung quanh',
    definitionEn: 'interested in learning about people or things around you',
    exampleEn: 'Babies are naturally curious about everything around them.',
    exampleVi: 'Trẻ sơ sinh tự nhiên luôn tò mò về mọi thứ xung quanh chúng.',
    status: 'draft',
    source: 'TOPIC',
    tags: ['feelings', 'curiosity'],
    addedAt: '2026-09-09T11:00:00Z',
    orderIndex: 2,
  },

  // Literary & Nuanced English (top-acad-literature)
  {
    id: 'ti-013',
    topicId: 'top-acad-literature',
    topicName: 'Literary & Nuanced English',
    word: 'serendipity',
    phonetic: '/ˌser.ənˈdɪp.ə.ti/',
    partOfSpeech: 'noun',
    cefr: 'C2',
    definitionVi: 'sự tình cờ may mắn; sự khám phá bất ngờ và thú vị khi không định trước',
    definitionEn: 'the fact of finding interesting or valuable things by chance',
    exampleEn: 'Finding my favorite vintage book in that quaint little shop was pure serendipity.',
    exampleVi: 'Tìm thấy cuốn sách cổ điển yêu thích trong tiệm nhỏ kỳ lạ đó là sự tình cờ may mắn thuần túy.',
    status: 'draft',
    source: 'DICT',
    tags: ['poetic', 'fortune', 'c2-advanced'],
    addedAt: '2026-09-10T01:00:00Z',
    orderIndex: 1,
  },
  {
    id: 'ti-014',
    topicId: 'top-acad-literature',
    topicName: 'Literary & Nuanced English',
    word: 'ephemeral',
    phonetic: '/ɪˈfem.ər.əl/',
    partOfSpeech: 'adjective',
    cefr: 'C2',
    definitionVi: 'phù du, sớm nở tối tàn, chỉ tồn tại trong một khoảng thời gian rất ngắn',
    definitionEn: 'lasting for only a short time',
    exampleEn: 'Fame in the age of social media can be extraordinarily ephemeral.',
    exampleVi: 'Sự nổi tiếng trong thời đại mạng xã hội có thể hết sức phù du.',
    status: 'published',
    source: 'DICT',
    tags: ['literary', 'poetic'],
    addedAt: '2026-09-05T08:30:00Z',
    orderIndex: 2,
  },
];

export const INITIAL_SYSTEM_DECKS: SystemDeck[] = [
  {
    id: 'deck-toeic-600',
    title: 'TOEIC 600 Core Starter Deck',
    titleVi: 'Bộ Bài Khởi Động TOEIC 600',
    description: 'Bộ thẻ nền tảng gồm các từ vựng công sở xuất hiện trên 80% đề thi TOEIC thực chiến.',
    icon: '💼',
    templateId: 'CLASSIC',
    templateName: 'Classic Flashcard Layout',
    targetCefr: 'B1',
    sourceCollectionId: 'col-toeic',
    sourceCollectionName: 'TOEIC 600 Essential Vocabulary',
    sourceTopicId: 'top-toeic-office',
    sourceTopicName: 'Office & Workplace Communication',
    noteCount: 85,
    activeLearners: 3420,
    completionRate: 76.4,
    isRecommended: true,
    isSystemDefault: true,
    status: 'published',
    lastUpdated: '2026-09-09T08:30:00Z',
  },
  {
    id: 'deck-daily-listening',
    title: 'Daily Audio Reflex & Pronunciation',
    titleVi: 'Phản Xạ Âm Thanh & Phát Âm Đời Sống',
    description: 'Bộ bài chuyên sâu luyện nghe phản xạ với phát âm chuẩn US/UK, ẩn mặt chữ để ép nghe âm thanh.',
    icon: '🎧',
    templateId: 'LISTENING',
    templateName: 'Audio-First Listening Focus',
    targetCefr: 'A2',
    sourceCollectionId: 'col-daily',
    sourceCollectionName: 'Daily Life & Social Essentials',
    sourceTopicId: 'top-daily-dining',
    sourceTopicName: 'Dining & Food Culture',
    noteCount: 75,
    activeLearners: 2890,
    completionRate: 83.1,
    isRecommended: true,
    isSystemDefault: false,
    status: 'published',
    lastUpdated: '2026-09-09T14:15:00Z',
  },
  {
    id: 'deck-visual-essentials',
    title: 'Visual Objects & Camera AI Scan Pack',
    titleVi: 'Đồ Vật Trực Quan & Nhận Diện Camera',
    description: 'Tối ưu cho việc ghi nhớ bằng hình ảnh thực tế từ kho nhận diện AI Scan và đời sống.',
    icon: '📸',
    templateId: 'VISUAL_IMAGE',
    templateName: 'Visual Image Hero Layout',
    targetCefr: 'A1',
    sourceCollectionId: 'col-daily',
    sourceCollectionName: 'Daily Life & Social Essentials',
    sourceTopicId: 'top-daily-kitchen',
    sourceTopicName: 'Kitchenware & Utensils',
    noteCount: 50,
    activeLearners: 4120,
    completionRate: 88.5,
    isRecommended: true,
    isSystemDefault: false,
    status: 'published',
    lastUpdated: '2026-09-10T02:30:00Z',
  },
  {
    id: 'deck-biz-contracts',
    title: 'Corporate Contracts & Negotiation Cloze',
    titleVi: 'Hợp Đồng Thương Mại & Điền Từ Ngữ Cảnh',
    description: 'Rèn luyện khả năng gõ chính xác từ khóa vào văn bản hợp đồng với chế độ điền khuyết Cloze Typing.',
    icon: '📝',
    templateId: 'CLOZE_TYPING',
    templateName: 'Cloze Deletion & Typing Practice',
    targetCefr: 'B2',
    sourceCollectionId: 'col-business',
    sourceCollectionName: 'Business & Corporate Operations',
    sourceTopicId: 'top-toeic-contracts',
    sourceTopicName: 'Contracts & Negotiations',
    noteCount: 45,
    activeLearners: 1450,
    completionRate: 64.8,
    isRecommended: false,
    isSystemDefault: false,
    status: 'published',
    lastUpdated: '2026-09-07T16:00:00Z',
  },
  {
    id: 'deck-academic-mindset',
    title: 'C1-C2 Academic & Critical Lexicon',
    titleVi: 'Từ Vựng Học Thuật C1-C2 & Tư Duy Phản Biện',
    description: 'Thiết kế tối giản, tập trung vào bản chất định nghĩa sâu và ngữ cảnh phản biện cao cấp.',
    icon: '🧠',
    templateId: 'MINIMAL',
    templateName: 'Minimal Zen Reader',
    targetCefr: 'C1',
    sourceCollectionId: 'col-academic',
    sourceCollectionName: 'IELTS Academic & Critical Mindset',
    sourceTopicId: 'top-acad-mindset',
    sourceTopicName: 'Psychology & Mental Resilience',
    noteCount: 40,
    activeLearners: 980,
    completionRate: 58.2,
    isRecommended: false,
    isSystemDefault: false,
    status: 'published',
    lastUpdated: '2026-09-08T19:00:00Z',
  },
];

export const MOCK_DECK_NOTES: DeckNote[] = [
  {
    id: 'dn-001',
    deckId: 'deck-toeic-600',
    word: 'agenda',
    phonetic: '/əˈdʒen.də/',
    partOfSpeech: 'noun',
    cefr: 'B1',
    definitionVi: 'chương trình nghị sự, lịch trình các nội dung cuộc họp',
    exampleEn: 'The first item on the agenda is the quarterly financial review.',
    srsState: 'mastered',
    stability: 28.5,
    dueInDays: 14,
  },
  {
    id: 'dn-002',
    deckId: 'deck-toeic-600',
    word: 'negotiate',
    phonetic: '/nəˈɡəʊ.ʃi.eɪt/',
    partOfSpeech: 'verb',
    cefr: 'B2',
    definitionVi: 'thương lượng, đàm phán hợp đồng',
    exampleEn: 'We will negotiate the payment terms tomorrow.',
    srsState: 'review',
    stability: 6.2,
    dueInDays: 1,
  },
  {
    id: 'dn-003',
    deckId: 'deck-toeic-600',
    word: 'consensus',
    phonetic: '/kənˈsen.səs/',
    partOfSpeech: 'noun',
    cefr: 'C1',
    definitionVi: 'sự đồng thuận, nhất trí giữa các bên',
    exampleEn: 'The committee has finally reached a consensus.',
    srsState: 'learning',
    stability: 2.1,
    dueInDays: 0,
  },
  {
    id: 'dn-004',
    deckId: 'deck-toeic-600',
    word: 'adjourn',
    phonetic: '/əˈdʒɜːn/',
    partOfSpeech: 'verb',
    cefr: 'B2',
    definitionVi: 'hoãn lại, tạm ngừng cuộc họp',
    exampleEn: 'The chair decided to adjourn until next Tuesday.',
    srsState: 'new',
    stability: 0.5,
    dueInDays: 0,
  },
  {
    id: 'dn-005',
    deckId: 'deck-daily-listening',
    word: 'thermos',
    phonetic: '/ˈθɜː.məs/',
    partOfSpeech: 'noun',
    cefr: 'B1',
    definitionVi: 'bình giữ nhiệt nóng lạnh',
    exampleEn: 'I always carry a thermos when going on long drives.',
    srsState: 'mastered',
    stability: 34.0,
    dueInDays: 20,
  },
  {
    id: 'dn-006',
    deckId: 'deck-visual-essentials',
    word: 'apple',
    phonetic: '/ˈæp.əl/',
    partOfSpeech: 'noun',
    cefr: 'A1',
    definitionVi: 'quả táo',
    exampleEn: 'An apple a day keeps the doctor away.',
    srsState: 'mastered',
    stability: 45.0,
    dueInDays: 30,
  },
];
