import {
  CohortRow,
  StreakSurvivalPoint,
  AtRiskSegment,
  LeitnerBoxMetric,
  CefrAccuracyMetric,
  HardestWordMetric,
  ScanFunnelStep,
  AIConfidenceTier,
  AIConfusionItem,
  AIScanPerformance,
  EconomyTrendPoint,
  CurrencySourceSinkItem,
  ShopItemVelocity,
  InflationStatus,
  LearningSourceBreakdown,
} from './types';

export const MOCK_LEARNING_SOURCES: LearningSourceBreakdown[] = [
  { label: 'Camera AI Scan (Snap-to-Learn)', value: 18450, percentage: 45, color: '#FF8A00' },
  { label: 'System Topic Decks (Collections)', value: 14350, percentage: 35, color: '#58CC02' },
  { label: 'Dictionary Search & Lookups', value: 6150, percentage: 15, color: '#1CB0F6' },
  { label: 'AI Adaptive Recommendations', value: 2050, percentage: 5, color: '#8B5CF6' },
];

export const MOCK_COHORT_MATRIX: CohortRow[] = [
  {
    id: 'cohort-w1',
    cohortWeek: 'Tuần 1 (14/07 - 20/07)',
    startDate: '2026-07-14',
    newUsersCount: 2450,
    retentionRates: [100, 68.4, 54.2, 45.1, 39.8, 34.5, 30.2, 28.4],
  },
  {
    id: 'cohort-w2',
    cohortWeek: 'Tuần 2 (21/07 - 27/07)',
    startDate: '2026-07-21',
    newUsersCount: 2680,
    retentionRates: [100, 70.1, 55.6, 46.8, 41.2, 36.1, 31.8],
  },
  {
    id: 'cohort-w3',
    cohortWeek: 'Tuần 3 (28/07 - 03/08)',
    startDate: '2026-07-28',
    newUsersCount: 2890,
    retentionRates: [100, 69.5, 56.2, 47.4, 42.0, 37.4],
  },
  {
    id: 'cohort-w4',
    cohortWeek: 'Tuần 4 (04/08 - 10/08)',
    startDate: '2026-08-04',
    newUsersCount: 3120,
    retentionRates: [100, 72.3, 58.9, 49.2, 43.6],
  },
  {
    id: 'cohort-w5',
    cohortWeek: 'Tuần 5 (11/08 - 17/08)',
    startDate: '2026-08-11',
    newUsersCount: 3340,
    retentionRates: [100, 71.8, 57.5, 48.6],
  },
  {
    id: 'cohort-w6',
    cohortWeek: 'Tuần 6 (18/08 - 24/08)',
    startDate: '2026-08-18',
    newUsersCount: 3450,
    retentionRates: [100, 73.4, 59.8],
  },
  {
    id: 'cohort-w7',
    cohortWeek: 'Tuần 7 (25/08 - 31/08)',
    startDate: '2026-08-25',
    newUsersCount: 3620,
    retentionRates: [100, 74.8],
  },
  {
    id: 'cohort-w8',
    cohortWeek: 'Tuần 8 (01/09 - 07/09)',
    startDate: '2026-09-01',
    newUsersCount: 3840,
    retentionRates: [100],
  },
];

export const MOCK_STREAK_SURVIVAL: StreakSurvivalPoint[] = [
  { day: 1, retentionPercent: 100, dropRatePercent: 0, learnerCount: 14820, isMilestone: true, annotation: 'Kích hoạt ngày đầu' },
  { day: 2, retentionPercent: 82.5, dropRatePercent: 17.5, learnerCount: 12226 },
  { day: 3, retentionPercent: 68.0, dropRatePercent: 14.5, learnerCount: 10077, isMilestone: true, annotation: 'Drop-off Cliff #1 (Vực thẳm ngày 3)' },
  { day: 5, retentionPercent: 53.4, dropRatePercent: 14.6, learnerCount: 7913 },
  { day: 7, retentionPercent: 44.0, dropRatePercent: 9.4, learnerCount: 6520, isMilestone: true, annotation: 'Cột mốc 1 tuần - Nhận thưởng Streak Freeze' },
  { day: 14, retentionPercent: 31.2, dropRatePercent: 12.8, learnerCount: 4623, isMilestone: true, annotation: 'Thói quen học tập định hình' },
  { day: 21, retentionPercent: 24.6, dropRatePercent: 6.6, learnerCount: 3645 },
  { day: 30, retentionPercent: 18.4, dropRatePercent: 6.2, learnerCount: 2726, isMilestone: true, annotation: 'Học viên trung thành cốt lõi (Loyal Core)' },
  { day: 60, retentionPercent: 11.2, dropRatePercent: 7.2, learnerCount: 1659 },
  { day: 90, retentionPercent: 8.5, dropRatePercent: 2.7, learnerCount: 1259, isMilestone: true, annotation: 'Super User / LTV Cao' },
];

export const MOCK_AT_RISK_SEGMENTS: AtRiskSegment[] = [
  {
    id: 'risk-01',
    segmentName: 'Người học vừa đứt chuỗi Streak (24h - 48h qua)',
    userCount: 842,
    riskLevel: 'critical',
    primaryCause: 'Quên giờ ôn tập buổi tối, không có sẵn Streak Freeze trong túi đồ',
    recommendedIntervention: 'Gửi Push Notification kích hoạt 1-Click Streak Recovery với chiết khấu 50% Coin',
    potentialRecoveryRate: 46.5,
  },
  {
    id: 'risk-02',
    segmentName: 'Học viên mới kẹt tại Hộp Leitner 1 (>15 từ dồn ứ)',
    userCount: 1260,
    riskLevel: 'high',
    primaryCause: 'Scan quá nhiều từ vựng mới cùng lúc gây quá tải nhận thức',
    recommendedIntervention: 'Đề xuất chế độ "Micro-Review" chia nhỏ phiên học thành 5 từ/phiên',
    potentialRecoveryRate: 62.0,
  },
  {
    id: 'risk-03',
    segmentName: 'Học viên không mở app sau 3 ngày liên tiếp',
    userCount: 945,
    riskLevel: 'medium',
    primaryCause: 'Thiếu động lực thi đua trên bảng xếp hạng Leaderboard tuần',
    recommendedIntervention: 'Tặng rương chào mừng Welcome Back kèm 200 Coins và 1 lượt X2 XP 15 phút',
    potentialRecoveryRate: 38.2,
  },
];

export const MOCK_LEITNER_BOXES: LeitnerBoxMetric[] = [
  { box: 1, title: 'Hộp 1: Từ mới / Chưa nhớ', intervalDays: 'Hàng ngày', wordCount: 820, percentage: 24.0, color: '#EF4444', accuracyRate: 58.4 },
  { box: 2, title: 'Hộp 2: Bắt đầu quen', intervalDays: 'Mỗi 3 ngày', wordCount: 1060, percentage: 31.0, color: '#F59E0B', accuracyRate: 74.2 },
  { box: 3, title: 'Hộp 3: Ghi nhớ trung hạn', intervalDays: 'Mỗi 7 ngày', wordCount: 752, percentage: 22.0, color: '#1CB0F6', accuracyRate: 86.5 },
  { box: 4, title: 'Hộp 4: Gần thành thạo', intervalDays: 'Mỗi 14 ngày', wordCount: 480, percentage: 14.0, color: '#8B5CF6', accuracyRate: 93.1 },
  { box: 5, title: 'Hộp 5: Trí nhớ vĩnh viễn (Mastered)', intervalDays: 'Mỗi 30 ngày', wordCount: 308, percentage: 9.0, color: '#58CC02', accuracyRate: 98.6 },
];

export const MOCK_CEFR_ACCURACY: CefrAccuracyMetric[] = [
  { level: 'A1', totalWords: 980, masteredWords: 720, accuracyRate: 94.2, avgMasteryDays: 12, reviewVolume: 18400, color: '#10B981' },
  { level: 'A2', totalWords: 820, masteredWords: 560, accuracyRate: 89.5, avgMasteryDays: 16, reviewVolume: 15200, color: '#14B8A6' },
  { level: 'B1', totalWords: 710, masteredWords: 410, accuracyRate: 82.1, avgMasteryDays: 22, reviewVolume: 12800, color: '#F59E0B' },
  { level: 'B2', totalWords: 490, masteredWords: 240, accuracyRate: 74.6, avgMasteryDays: 29, reviewVolume: 8900, color: '#F97316' },
  { level: 'C1', totalWords: 280, masteredWords: 98, accuracyRate: 66.8, avgMasteryDays: 38, reviewVolume: 5100, color: '#8B5CF6' },
  { level: 'C2', totalWords: 140, masteredWords: 32, accuracyRate: 58.2, avgMasteryDays: 45, reviewVolume: 2400, color: '#F43F5E' },
];

export const MOCK_HARDEST_WORDS: HardestWordMetric[] = [
  {
    id: 'hw-01',
    word: 'resilient',
    partOfSpeech: 'adjective',
    cefr: 'C1',
    meaningVi: 'kiên cường, mau hồi phục sau khó khăn',
    totalReviews: 2420,
    failureRate: 44.5,
    retentionScore: 55.5,
    errorStreak: 4,
    lastTested: 'Hôm nay 10:15',
  },
  {
    id: 'hw-02',
    word: 'ubiquitous',
    partOfSpeech: 'adjective',
    cefr: 'C1',
    meaningVi: 'có mặt ở khắp mọi nơi cùng một lúc',
    totalReviews: 1890,
    failureRate: 42.1,
    retentionScore: 57.9,
    errorStreak: 3,
    lastTested: 'Hôm nay 09:40',
  },
  {
    id: 'hw-03',
    word: 'meticulous',
    partOfSpeech: 'adjective',
    cefr: 'B2',
    meaningVi: 'tỉ mỉ, cẩn thận quá mức về từng chi tiết',
    totalReviews: 2150,
    failureRate: 38.6,
    retentionScore: 61.4,
    errorStreak: 2,
    lastTested: 'Hôm nay 08:30',
  },
  {
    id: 'hw-04',
    word: 'precarious',
    partOfSpeech: 'adjective',
    cefr: 'C1',
    meaningVi: 'bấp bênh, không chắc chắn, nguy hiểm',
    totalReviews: 1420,
    failureRate: 37.8,
    retentionScore: 62.2,
    errorStreak: 3,
    lastTested: 'Hôm qua 21:10',
  },
  {
    id: 'hw-05',
    word: 'epiphany',
    partOfSpeech: 'noun',
    cefr: 'C2',
    meaningVi: 'sự thức tỉnh hoặc nhận ngộ đột ngột',
    totalReviews: 980,
    failureRate: 36.4,
    retentionScore: 63.6,
    errorStreak: 2,
    lastTested: 'Hôm qua 18:25',
  },
  {
    id: 'hw-06',
    word: 'ambiguous',
    partOfSpeech: 'adjective',
    cefr: 'B2',
    meaningVi: 'mơ hồ, nhập nhằng, có thể hiểu theo nhiều nghĩa',
    totalReviews: 2310,
    failureRate: 35.2,
    retentionScore: 64.8,
    errorStreak: 2,
    lastTested: 'Hôm qua 16:40',
  },
  {
    id: 'hw-07',
    word: 'serendipity',
    partOfSpeech: 'noun',
    cefr: 'C2',
    meaningVi: 'sự tình cờ may mắn tìm thấy điều quý giá',
    totalReviews: 870,
    failureRate: 34.1,
    retentionScore: 65.9,
    errorStreak: 1,
    lastTested: '08/09/2026',
  },
  {
    id: 'hw-08',
    word: 'tenacious',
    partOfSpeech: 'adjective',
    cefr: 'C1',
    meaningVi: 'ngoan cường, bền bỉ, không chịu từ bỏ',
    totalReviews: 1290,
    failureRate: 33.8,
    retentionScore: 66.2,
    errorStreak: 1,
    lastTested: '08/09/2026',
  },
];

export const MOCK_SCAN_FUNNEL: ScanFunnelStep[] = [
  {
    id: 'step-1',
    step: '1. Kích hoạt Camera AI',
    count: 15200,
    conversionFromStart: 100,
    conversionFromPrev: 100,
    dropOffRate: 0,
    color: '#1CB0F6',
    description: 'Người học bấm icon Snapy Camera tại màn hình chính hoặc Explore tab',
  },
  {
    id: 'step-2',
    step: '2. Chụp & Tải ảnh lên Server',
    count: 13600,
    conversionFromStart: 89.5,
    conversionFromPrev: 89.5,
    dropOffRate: 10.5,
    color: '#3ABAF7',
    description: 'Ảnh được nén chuẩn JPEG tối ưu và gửi đến Cloudflare R2 qua Presigned URL',
  },
  {
    id: 'step-3',
    step: '3. AI Nhận diện Thành công',
    count: 13165,
    conversionFromStart: 86.6,
    conversionFromPrev: 96.8,
    dropOffRate: 3.2,
    color: '#FF8A00',
    description: 'Florence-2 / Gemini Vision gán nhãn đối tượng với thời gian xử lý trung bình 340ms',
  },
  {
    id: 'step-4',
    step: '4. Thêm Thẻ vào Bộ Flashcard',
    count: 10320,
    conversionFromStart: 67.9,
    conversionFromPrev: 78.4,
    dropOffRate: 21.6,
    color: '#7DD634',
    description: 'Người học hài lòng với nhãn từ vựng gợi ý và bấm lưu vào Deck cá nhân',
  },
  {
    id: 'step-5',
    step: '5. Hoàn thành Lượt Học Đầu tiên',
    count: 8580,
    conversionFromStart: 56.4,
    conversionFromPrev: 83.1,
    dropOffRate: 16.9,
    color: '#58CC02',
    description: 'Hoàn tất chu trình Active Learning Loop (Lật thẻ, nghe phát âm TTS và qua Hộp Leitner 1)',
  },
];

export const MOCK_CONFIDENCE_TIERS: AIConfidenceTier[] = [
  {
    tier: 'high',
    label: 'Độ tin cậy cao (High Confidence)',
    count: 11137,
    percentage: 84.6,
    thresholdText: '≥ 90%',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    color: '#58CC02',
  },
  {
    tier: 'medium',
    label: 'Độ tin cậy vừa (Medium Confidence)',
    count: 1685,
    percentage: 12.8,
    thresholdText: '70% – 89%',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
    color: '#F59E0B',
  },
  {
    tier: 'low',
    label: 'Cần Review khẩn cấp (Low Confidence)',
    count: 343,
    percentage: 2.6,
    thresholdText: '< 70%',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200',
    color: '#EF4444',
  },
];

export const MOCK_CONFUSION_ITEMS: AIConfusionItem[] = [
  {
    id: 'conf-01',
    realObject: 'thermos (cốc/bình giữ nhiệt)',
    predictedLabel: 'coffee cup (cốc cà phê thường)',
    occurrences: 142,
    autoFixRate: 88.5,
    suggestedAction: 'Bổ sung prompt phân biệt chất liệu kim loại cách nhiệt vào Florence-2 Vision',
    cefr: 'B1',
    severity: 'high',
  },
  {
    id: 'conf-02',
    realObject: 'notebook / workbook (vở bài tập)',
    predictedLabel: 'textbook (sách giáo khoa)',
    occurrences: 98,
    autoFixRate: 82.0,
    suggestedAction: 'Huấn luyện thêm nhãn spiral notebook và trang kẻ ô',
    cefr: 'A2',
    severity: 'high',
  },
  {
    id: 'conf-03',
    realObject: 'reading glasses (kính đọc sách)',
    predictedLabel: 'sunglasses (kính râm)',
    occurrences: 76,
    autoFixRate: 74.5,
    suggestedAction: 'Kiểm tra tròng kính trong suốt vs tròng kính tối màu',
    cefr: 'A2',
    severity: 'medium',
  },
  {
    id: 'conf-04',
    realObject: 'headset (tai nghe có micro)',
    predictedLabel: 'earphones (tai nghe nhét tai)',
    occurrences: 54,
    autoFixRate: 91.2,
    suggestedAction: 'Tách nhãn over-ear headband và in-ear buds',
    cefr: 'B1',
    severity: 'medium',
  },
  {
    id: 'conf-05',
    realObject: 'potted plant (cây cảnh để bàn)',
    predictedLabel: 'vase (bình cắm hoa)',
    occurrences: 38,
    autoFixRate: 79.0,
    suggestedAction: 'Thêm context nhận diện đất trồng và chậu gốm',
    cefr: 'A1',
    severity: 'low',
  },
];

export const MOCK_AI_PERFORMANCE: AIScanPerformance = {
  p50LatencyMs: 340,
  p95LatencyMs: 820,
  p99LatencyMs: 1420,
  timeoutRatePercent: 0.04,
  quotaExceededToday: 142,
  gpuWorkerCount: 4,
};

export const MOCK_ECONOMY_TREND: EconomyTrendPoint[] = [
  { date: '01/09', coinFaucet: 38400, coinSink: 26800, gemFaucet: 1280, gemSink: 940 },
  { date: '02/09', coinFaucet: 41200, coinSink: 29500, gemFaucet: 1350, gemSink: 1020 },
  { date: '03/09', coinFaucet: 39800, coinSink: 28100, gemFaucet: 1310, gemSink: 980 },
  { date: '04/09', coinFaucet: 43500, coinSink: 31200, gemFaucet: 1420, gemSink: 1080 },
  { date: '05/09', coinFaucet: 45600, coinSink: 33400, gemFaucet: 1540, gemSink: 1190 },
  { date: '06/09', coinFaucet: 48900, coinSink: 36200, gemFaucet: 1680, gemSink: 1320 },
  { date: '07/09', coinFaucet: 52100, coinSink: 38900, gemFaucet: 1790, gemSink: 1410 },
  { date: '08/09', coinFaucet: 49400, coinSink: 35800, gemFaucet: 1640, gemSink: 1280 },
  { date: '09/09', coinFaucet: 51200, coinSink: 37400, gemFaucet: 1710, gemSink: 1340 },
  { date: '10/09', coinFaucet: 54300, coinSink: 39800, gemFaucet: 1850, gemSink: 1460 },
];

export const MOCK_COIN_FAUCETS: CurrencySourceSinkItem[] = [
  { category: 'Hoàn thành lượt học SRS hàng ngày', amount: 539490, percentage: 42.0, color: '#58CC02' },
  { category: 'Phần thưởng Nhiệm vụ Ngày & Tuần', amount: 359660, percentage: 28.0, color: '#FF8A00' },
  { category: 'Duy trì chuỗi Streak & Milestone', amount: 231210, percentage: 18.0, color: '#FFC42E' },
  { category: 'Thăng cấp độ (Level Up Bonus)', amount: 154140, percentage: 12.0, color: '#1CB0F6' },
];

export const MOCK_COIN_SINKS: CurrencySourceSinkItem[] = [
  { category: 'Bảo vệ Streak (Mua Streak Freeze)', amount: 428208, percentage: 48.0, color: '#1CB0F6' },
  { category: 'Mở khóa Chủ đề từ vựng chuyên sâu', amount: 231946, percentage: 26.0, color: '#8B5CF6' },
  { category: 'Skin Mascot Snapy & Khung đại diện', amount: 142736, percentage: 16.0, color: '#FF8A00' },
  { category: 'Rương thần bí ngẫu nhiên (Loot Chest)', amount: 89210, percentage: 10.0, color: '#FFC42E' },
];

export const MOCK_SHOP_VELOCITY: ShopItemVelocity[] = [
  {
    id: 'shop-01',
    name: 'Streak Freeze Shield (Lá chắn chuỗi)',
    category: 'boost',
    currency: 'coins',
    price: 250,
    unitsSold: 1712,
    totalVolume: 428000,
    sinkContributionPercent: 48.0,
    trend: 'up',
  },
  {
    id: 'shop-02',
    name: 'Deck B2-C1 Business Vocabulary (Thương mại)',
    category: 'deck',
    currency: 'coins',
    price: 600,
    unitsSold: 284,
    totalVolume: 170400,
    sinkContributionPercent: 19.1,
    trend: 'up',
  },
  {
    id: 'shop-03',
    name: 'Skin Snapy Phù Thủy Tri Thức (Wizard Outfit)',
    category: 'cosmetic',
    currency: 'gems',
    price: 80,
    unitsSold: 145,
    totalVolume: 11600,
    sinkContributionPercent: 13.0,
    trend: 'stable',
  },
  {
    id: 'shop-04',
    name: 'Rương Hoàng Gia May Mắn (Royal Chest)',
    category: 'chest',
    currency: 'coins',
    price: 350,
    unitsSold: 255,
    totalVolume: 89250,
    sinkContributionPercent: 10.0,
    trend: 'down',
  },
  {
    id: 'shop-05',
    name: 'Thẻ X2 Kinh Nghiệm 30 Phút (Double XP)',
    category: 'boost',
    currency: 'coins',
    price: 150,
    unitsSold: 412,
    totalVolume: 61800,
    sinkContributionPercent: 6.9,
    trend: 'up',
  },
  {
    id: 'shop-06',
    name: 'Khung Thẻ Học Neon Cyberpunk',
    category: 'cosmetic',
    currency: 'gems',
    price: 50,
    unitsSold: 92,
    totalVolume: 4600,
    sinkContributionPercent: 3.0,
    trend: 'stable',
  },
];

export const MOCK_INFLATION_STATUS: InflationStatus = {
  faucetSinkRatio: 1.43,
  status: 'caution',
  circulationCoins: 3924000,
  velocityIndex: 0.28,
  diagnosis: 'Tốc độ bơm Coins qua bài học và streak (+1.28M) đang vượt lượng tiêu thụ Shop (892k), dẫn tới tích lũy thặng dư nhẹ.',
  actionRecommendation: 'Khuyến nghị bổ sung vật phẩm tiêu hao hấp dẫn (chủ đề mới, sự kiện giới hạn) hoặc điều chỉnh nhẹ giá Streak Freeze.',
};
