import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Wifi, Battery, Signal, Smartphone } from 'lucide-react';
import { FlashcardPreview } from './FlashcardPreview';
export const MobileSimulator = ({ card }) => {
    const [activeTab, setActiveTab] = useState('card');
    return (_jsxs("div", { className: "h-full flex flex-col items-center justify-between p-4 bg-surface-subtle/60 border-l border-border select-none", children: [_jsxs("div", { className: "w-full flex items-center justify-between pb-3 border-b border-border/80 text-xs", children: [_jsxs("div", { className: "flex items-center gap-2 text-text font-semibold", children: [_jsx(Smartphone, { size: 15, className: "text-primary" }), _jsx("span", { children: "Mobile Simulator" })] }), _jsxs("div", { className: "flex items-center gap-1 bg-surface border border-border rounded-md p-0.5", children: [_jsx("button", { type: "button", onClick: () => setActiveTab('card'), className: `px-2 py-0.5 rounded text-[11px] font-medium transition-all ${activeTab === 'card'
                                    ? 'bg-primary-light text-primary font-bold'
                                    : 'text-text-muted hover:text-text'}`, children: "Th\u1EBB h\u1ECDc (SRS)" }), _jsx("button", { type: "button", onClick: () => setActiveTab('study'), className: `px-2 py-0.5 rounded text-[11px] font-medium transition-all ${activeTab === 'study'
                                    ? 'bg-primary-light text-primary font-bold'
                                    : 'text-text-muted hover:text-text'}`, children: "T\u1EEB \u0111i\u1EC3n" })] })] }), _jsx("div", { className: "my-auto py-2", children: _jsx("div", { className: "w-[340px] h-[640px] bg-slate-900 rounded-[44px] p-3 shadow-[0_20px_50px_rgba(0,0,0,0.18)] border-4 border-slate-700/60 relative flex flex-col", children: _jsxs("div", { className: "w-full h-full bg-[#F8F9F7] rounded-[34px] overflow-hidden flex flex-col relative border border-slate-800", children: [_jsxs("div", { className: "w-full h-9 pt-2 px-6 flex items-center justify-between text-slate-800 text-[11px] font-semibold select-none z-20", children: [_jsx("span", { children: "09:41" }), _jsx("div", { className: "w-20 h-4 bg-black rounded-full mx-auto" }), _jsxs("div", { className: "flex items-center gap-1.5 text-slate-800", children: [_jsx(Signal, { size: 11 }), _jsx(Wifi, { size: 11 }), _jsx(Battery, { size: 13 })] })] }), _jsxs("div", { className: "px-4 py-2 flex items-center justify-between border-b border-border/40 bg-surface/80 backdrop-blur-sm z-10", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "text-base", children: "\uD83E\uDD8A" }), _jsx("span", { className: "font-extrabold text-xs text-text tracking-tight", children: "SnapVocab" })] }), _jsx("div", { className: "flex items-center gap-1 bg-reward-light text-reward-hover px-2 py-0.5 rounded-full text-[10px] font-bold border border-reward/30", children: _jsx("span", { children: "\uD83D\uDD25 7 days" }) })] }), _jsx("div", { className: "flex-1 overflow-y-auto p-3 flex flex-col justify-center items-center", children: _jsx(FlashcardPreview, { card: card }) }), _jsx("div", { className: "w-full h-5 flex items-center justify-center pb-1", children: _jsx("div", { className: "w-28 h-1 bg-slate-400/50 rounded-full" }) })] }) }) }), _jsxs("div", { className: "w-full text-center text-[11px] text-text-muted pt-2 border-t border-border/80", children: ["\u0110\u1ED3ng b\u1ED9 tr\u1EF1c ti\u1EBFp theo ", _jsx("span", { className: "font-mono text-primary font-bold", children: "CardViewModel" })] })] }));
};
