import {
  LiveOpsEconomyState,
  ShopItem,
  FlashSaleCampaign,
  GuardrailConfig,
  GuardrailViolation,
  EconomyTransaction,
} from './types';

export const MOCK_ECONOMY_STATE: LiveOpsEconomyState = {
  coins: {
    faucet: 1284500, // 1.28M Coins earned
    sink: 892100,    // 892k Coins spent
  },
  gems: {
    faucet: 42500,   // 42.5k Gems earned
    sink: 31200,     // 31.2k Gems spent
  },
  guardrails: {
    maxCoinsCapPerQuest: 1000,
    maxGemsCapPerQuest: 100,
    violationsDetected: 0,
    status: 'healthy',
  },
  streakMetrics: {
    avgStreakDays: 6.8,
    activeStreakLearners: 9420,
    streaksOver7Days: 4120,
    streaksOver30Days: 840,
    pendingRecoveryRequests: 2,
  },
};

export const INITIAL_SHOP_ITEMS: ShopItem[] = [
  {
    id: 'item_streak_freeze',
    sku: 'SKU-BST-FREEZE',
    name: 'Bảo Hiểm Chuỗi (Streak Freeze)',
    description: 'Bảo vệ chuỗi Streak học tập nếu bạn lỡ quên học 1 ngày. Tối đa tích lũy 2 lá chắn.',
    category: 'streak_saver',
    currency: 'coins',
    originalPrice: 400,
    discountPrice: 320,
    rarity: 'rare',
    badge: 'BEST_VALUE',
    icon: '🛡️',
    imageUrl: '/images/shop/icon5_clean.png',
    bgColorClass: 'bg-sky-50',
    previewAsset: '/images/shop/icon5_clean.png',
    status: 'flash_sale',
    stock: undefined,
    purchaseLimitPerUser: 2,
    unitsSold: 1712,
    totalRevenue: 428000,
    sinkPercent: 48.0,
    createdDate: '2026-08-01',
    lastUpdated: '2026-09-08 14:20',
  },
  {
    id: 'item_xp_booster',
    sku: 'SKU-BST-2XP',
    name: 'Nhân Đôi KN (XP Booster)',
    description: 'Nhân đôi điểm kinh nghiệm trong 15 phút ôn tập tiếp theo.',
    category: 'booster',
    currency: 'coins',
    originalPrice: 250,
    discountPrice: 200,
    rarity: 'rare',
    badge: 'HOT',
    icon: '⚡',
    imageUrl: '/images/shop/icon1_clean.png',
    bgColorClass: 'bg-amber-50',
    previewAsset: '/images/shop/icon1_clean.png',
    status: 'flash_sale',
    stock: undefined,
    purchaseLimitPerUser: 5,
    unitsSold: 1240,
    totalRevenue: 248000,
    sinkPercent: 27.8,
    createdDate: '2026-08-01',
    lastUpdated: '2026-09-10 14:20',
  },
  {
    id: 'item_heart_refill',
    sku: 'SKU-BST-HEART',
    name: 'Hồi Phục Tim (Heart Refill)',
    description: 'Làm đầy 5 tim ngay lập tức để tiếp tục các bài kiểm tra flashcard và luyện đề.',
    category: 'booster',
    currency: 'coins',
    originalPrice: 350,
    rarity: 'common',
    icon: '❤️',
    imageUrl: '/images/shop/icon9_clean.png',
    bgColorClass: 'bg-rose-50',
    previewAsset: '/images/shop/icon9_clean.png',
    status: 'active',
    stock: undefined,
    purchaseLimitPerUser: 5,
    unitsSold: 310,
    totalRevenue: 108500,
    sinkPercent: 12.1,
    createdDate: '2026-08-10',
    lastUpdated: '2026-09-07 11:30',
  },
  {
    id: 'item_magnet',
    sku: 'SKU-BST-MAGNET',
    name: 'Nam Châm Xu (Coin Magnet)',
    description: 'Tự động thu hút toàn bộ xu thưởng và nhân thêm Coin trong bài học thực hành.',
    category: 'booster',
    currency: 'coins',
    originalPrice: 300,
    rarity: 'rare',
    icon: '🧲',
    imageUrl: '/images/shop/icon2_clean.png',
    bgColorClass: 'bg-red-50',
    previewAsset: '/images/shop/icon2_clean.png',
    status: 'active',
    stock: undefined,
    purchaseLimitPerUser: 3,
    unitsSold: 185,
    totalRevenue: 55500,
    sinkPercent: 6.2,
    createdDate: '2026-08-12',
    lastUpdated: '2026-09-05 09:15',
  },
  {
    id: 'item_refresh_ticket',
    sku: 'SKU-BST-REFRESH',
    name: 'Vé Đổi Mới (Refresh Ticket)',
    description: 'Tạo mới hoàn toàn bộ câu hỏi ôn tập khi gặp chủ đề quá khó hoặc muốn làm mới SRS.',
    category: 'booster',
    currency: 'coins',
    originalPrice: 100,
    rarity: 'common',
    icon: '🔄',
    imageUrl: '/images/shop/icon6_clean.png',
    bgColorClass: 'bg-blue-50',
    previewAsset: '/images/shop/icon6_clean.png',
    status: 'active',
    stock: undefined,
    purchaseLimitPerUser: 10,
    unitsSold: 420,
    totalRevenue: 42000,
    sinkPercent: 4.7,
    createdDate: '2026-08-15',
    lastUpdated: '2026-09-06 08:30',
  },
  {
    id: 'item_hint_token',
    sku: 'SKU-BST-HINT',
    name: 'Gợi Ý Từ Vựng (Hint Token)',
    description: 'Mở khóa 3 lượt gợi ý từ ngữ và ngữ cảnh trong các bài thi thử TOEIC.',
    category: 'booster',
    currency: 'coins',
    originalPrice: 150,
    rarity: 'common',
    icon: '💡',
    imageUrl: '/images/shop/icon7_clean.png',
    bgColorClass: 'bg-purple-50',
    previewAsset: '/images/shop/icon7_clean.png',
    status: 'active',
    stock: undefined,
    purchaseLimitPerUser: 10,
    unitsSold: 260,
    totalRevenue: 39000,
    sinkPercent: 4.3,
    createdDate: '2026-08-18',
    lastUpdated: '2026-09-04 15:20',
  },
  {
    id: 'item_timer_boost',
    sku: 'SKU-BST-TIMER',
    name: 'Thêm Thời Gian (Timer Boost)',
    description: 'Cộng thêm 60 giây vào bài kiểm tra tính giờ phản xạ từ vựng cấp tốc.',
    category: 'booster',
    currency: 'coins',
    originalPrice: 200,
    rarity: 'common',
    icon: '⏱️',
    imageUrl: '/images/shop/icon8_clean.png',
    bgColorClass: 'bg-orange-50',
    previewAsset: '/images/shop/icon8_clean.png',
    status: 'active',
    stock: undefined,
    purchaseLimitPerUser: 5,
    unitsSold: 140,
    totalRevenue: 28000,
    sinkPercent: 3.1,
    createdDate: '2026-08-20',
    lastUpdated: '2026-09-03 10:00',
  },
  {
    id: 'item_frame_scholar',
    sku: 'SKU-FRM-SCHOLAR',
    name: 'Khung Học Giả (Scholar Frame)',
    description: 'Khung đại diện viền ngọc xanh tôn vinh tinh thần tự học không ngừng nghỉ.',
    category: 'avatar_frame',
    currency: 'coins',
    originalPrice: 500,
    rarity: 'rare',
    icon: '🎓',
    imageUrl: '/images/shop/badge1_clean.png',
    bgColorClass: 'bg-info-50',
    previewAsset: '/images/shop/badge1_clean.png',
    status: 'active',
    stock: undefined,
    purchaseLimitPerUser: 1,
    unitsSold: 96,
    totalRevenue: 48000,
    sinkPercent: 5.4,
    createdDate: '2026-08-22',
    lastUpdated: '2026-09-01 12:00',
  },
  {
    id: 'item_frame_owl',
    sku: 'SKU-FRM-OWL',
    name: 'Khung Cú Đêm (Night Owl)',
    description: 'Khung huyền bí dạ quang tím dành riêng cho những học viên chăm học buổi tối.',
    category: 'avatar_frame',
    currency: 'coins',
    originalPrice: 650,
    rarity: 'rare',
    icon: '🦉',
    imageUrl: '/images/shop/badge2_clean.png',
    bgColorClass: 'bg-indigo-50',
    previewAsset: '/images/shop/badge2_clean.png',
    status: 'active',
    stock: undefined,
    purchaseLimitPerUser: 1,
    unitsSold: 72,
    totalRevenue: 46800,
    sinkPercent: 5.2,
    createdDate: '2026-08-25',
    lastUpdated: '2026-09-05 18:40',
  },
  {
    id: 'item_frame_goldencrown',
    sku: 'SKU-FRM-CROWN',
    name: 'Khung Rồng Vàng (Golden Crown)',
    description: 'Khung vương miện hoàng kim cao cấp lấp lánh trên bảng xếp hạng Leaderboard tuần.',
    category: 'avatar_frame',
    currency: 'gems',
    originalPrice: 90,
    discountPrice: 75,
    rarity: 'epic',
    badge: 'LIMITED',
    icon: '👑',
    imageUrl: '/images/shop/badge11_clean.png',
    bgColorClass: 'bg-yellow-50',
    previewAsset: '/images/shop/badge11_clean.png',
    status: 'flash_sale',
    stock: 150,
    purchaseLimitPerUser: 1,
    unitsSold: 85,
    totalRevenue: 6375,
    sinkPercent: 20.4,
    createdDate: '2026-08-28',
    lastUpdated: '2026-09-09 16:10',
  },
  {
    id: 'item_amulet',
    sku: 'SKU-SPEC-AMULET',
    name: 'Huy Chương Sao (Star Amulet)',
    description: 'Tăng 50% tỉ lệ xuất hiện câu hỏi thưởng Coin trong 24 giờ liên tục.',
    category: 'booster',
    currency: 'coins',
    originalPrice: 800,
    rarity: 'epic',
    badge: 'NEW',
    icon: '⭐',
    imageUrl: '/images/shop/icon3_clean.png',
    bgColorClass: 'bg-emerald-50',
    previewAsset: '/images/shop/icon3_clean.png',
    status: 'active',
    stock: undefined,
    purchaseLimitPerUser: 2,
    unitsSold: 45,
    totalRevenue: 36000,
    sinkPercent: 4.0,
    createdDate: '2026-09-01',
    lastUpdated: '2026-09-08 09:30',
  },
  {
    id: 'item_trophy',
    sku: 'SKU-SPEC-TROPHY',
    name: 'Cúp Vàng Thử Thách (Gold Challenge Trophy)',
    description: 'Mở khóa phòng đấu trường thử thách từ vựng vô hạn cuối tuần và nhận rương báu.',
    category: 'chest',
    currency: 'coins',
    originalPrice: 1500,
    rarity: 'legendary',
    badge: 'BEST_VALUE',
    icon: '🏆',
    imageUrl: '/images/shop/icon4_clean.png',
    bgColorClass: 'bg-amber-50',
    previewAsset: '/images/shop/icon4_clean.png',
    status: 'active',
    stock: 50,
    purchaseLimitPerUser: 1,
    unitsSold: 28,
    totalRevenue: 42000,
    sinkPercent: 4.7,
    createdDate: '2026-09-02',
    lastUpdated: '2026-09-09 11:15',
  },
  {
    id: 'item_theme_neon',
    sku: 'SKU-THM-NEON',
    name: 'Giao Diện Dạ Quang (Night Glow Theme)',
    description: 'Bộ giao diện Night Glow tương phản cao bảo vệ mắt và hiệu ứng neon sống động.',
    category: 'theme',
    currency: 'gems',
    originalPrice: 120,
    rarity: 'legendary',
    badge: 'NEW',
    icon: '🌌',
    imageUrl: '/images/shop/badge10_clean.png',
    bgColorClass: 'bg-cyan-50',
    previewAsset: '/images/shop/badge10_clean.png',
    status: 'active',
    stock: 300,
    purchaseLimitPerUser: 1,
    unitsSold: 52,
    totalRevenue: 6240,
    sinkPercent: 20.0,
    createdDate: '2026-09-05',
    lastUpdated: '2026-09-10 15:40',
  },
  {
    id: 'item_frame_phoenix',
    sku: 'SKU-FRM-PHOENIX',
    name: 'Khung Phượng Hoàng Lửa (Phoenix Flame)',
    description: 'Khung đại diện rực cháy tái sinh dành cho người học giữ vững chuỗi trên 30 ngày.',
    category: 'avatar_frame',
    currency: 'gems',
    originalPrice: 85,
    rarity: 'legendary',
    badge: 'LIMITED',
    icon: '🔥',
    imageUrl: '/images/shop/badge3_clean.png',
    bgColorClass: 'bg-red-50',
    previewAsset: '/images/shop/badge3_clean.png',
    status: 'draft',
    stock: 100,
    purchaseLimitPerUser: 1,
    unitsSold: 0,
    totalRevenue: 0,
    sinkPercent: 0,
    createdDate: '2026-09-09',
    lastUpdated: '2026-09-10 10:45',
  },
  {
    id: 'item_deck_master',
    sku: 'SKU-DCK-TOEIC900',
    name: 'Deck TOEIC 900+ Master Vocab',
    description: 'Bộ 450 từ vựng nâng cao chuyên sâu mục tiêu TOEIC 900+ kèm ví dụ đề thi thật.',
    category: 'deck',
    currency: 'coins',
    originalPrice: 850,
    rarity: 'epic',
    icon: '💼',
    imageUrl: '/images/shop/badge12_clean.png',
    bgColorClass: 'bg-slate-50',
    previewAsset: '/images/shop/badge12_clean.png',
    status: 'active',
    stock: undefined,
    purchaseLimitPerUser: 1,
    unitsSold: 95,
    totalRevenue: 80750,
    sinkPercent: 9.0,
    createdDate: '2026-08-20',
    lastUpdated: '2026-09-08 14:00',
  },
];

export const INITIAL_FLASH_SALES: FlashSaleCampaign[] = [
  {
    id: 'sale-01',
    name: 'Weekend Streak Rescue (Cứu Chuỗi Cuối Tuần)',
    description: 'Giảm giá 20% cho vật phẩm Lá chắn chuỗi Streak Freeze giúp người học giữ vững thói quen.',
    discountPercent: 20,
    startDate: '2026-09-10 00:00',
    endDate: '2026-09-12 23:59',
    status: 'active',
    itemIds: ['item_streak_freeze', 'item_xp_booster'],
    purchaseLimitPerUser: 2,
    unitsSold: 420,
    revenueLift: 84000,
  },
  {
    id: 'sale-02',
    name: 'Royal Leaderboard Season Drop (Mùa Xếp Hạng Hoàng Kim)',
    description: 'Ưu đãi 15% cho Khung Rồng Vàng giới hạn mùa giải cao cấp.',
    discountPercent: 15,
    startDate: '2026-09-15 08:00',
    endDate: '2026-09-18 23:59',
    status: 'scheduled',
    itemIds: ['item_frame_goldencrown'],
    purchaseLimitPerUser: 1,
    unitsSold: 0,
    revenueLift: 0,
  },
  {
    id: 'sale-03',
    name: 'Summer Farewell Flash Drop (Chào Tạm Biệt Mùa Hè)',
    description: 'Chiến dịch xả kho toàn bộ vật phẩm chủ đề mùa hè với mức chiết khấu tới 40%.',
    discountPercent: 40,
    startDate: '2026-08-28 00:00',
    endDate: '2026-08-31 23:59',
    status: 'ended',
    itemIds: ['shop-11'],
    purchaseLimitPerUser: 1,
    unitsSold: 180,
    revenueLift: 54000,
  },
];

export const DEFAULT_GUARDRAIL_CONFIG: GuardrailConfig = {
  maxCoinsCapPerQuest: 1000,
  maxGemsCapPerQuest: 100,
  maxItemPriceCoins: 5000,
  maxItemPriceGems: 500,
  minItemPriceFloor: 10,
  dailyEarningCapCoins: 2500,
  inflationWarningThreshold: 1.35,
  emergencyShopMaintenance: false,
  lockStreakSaverSales: false,
};

export const INITIAL_GUARDRAIL_VIOLATIONS: GuardrailViolation[] = [
  {
    id: 'vio-01',
    timestamp: '2026-09-10 08:14:22',
    severity: 'medium',
    type: 'DAILY_EARN_SPIKE',
    description: 'Tài khoản learner_84920 hoàn thành 42 bài học trong 15 phút, tiệm cận trần kiếm 2,500 Coins/ngày.',
    targetId: 'user_84920',
    targetName: 'nguyen.minh@toeic.edu.vn',
    status: 'active',
  },
  {
    id: 'vio-02',
    timestamp: '2026-09-09 16:30:10',
    severity: 'low',
    type: 'PRICE_CEILING',
    description: 'Bản nháp Deck IELTS 8.0+ được nhập giá 6,000 Coins (vượt trần 5,000 Coins) - đã được hạ về 850 Coins.',
    targetId: 'shop-10',
    targetName: 'Deck IELTS Academic 8.0+',
    status: 'mitigated',
    mitigatedBy: 'Admin Lead',
    reason: 'Hạ giá niêm yết theo chuẩn Guardrail để phù hợp khả năng tích lũy của học viên',
  },
  {
    id: 'vio-03',
    timestamp: '2026-09-07 11:20:45',
    severity: 'high',
    type: 'REWARD_CAP',
    description: 'Nhiệm vụ tuần thử nghiệm được gán phần thưởng 1,500 Coins (vượt trần 1,000 Coins) - hệ thống tự động chặn.',
    targetId: 'mission_draft_77',
    targetName: 'Chuỗi Chinh Phục 500 Từ C1',
    status: 'whitelisted',
    mitigatedBy: 'Super Admin Hoàng',
    reason: 'Nhiệm vụ đặc biệt mùa thi chứng chỉ được Super Admin cấp quyền ngoại lệ',
  },
];

export const INITIAL_TRANSACTIONS: EconomyTransaction[] = [
  {
    id: 'tx-20260910-0941',
    timestamp: '2026-09-10 14:48:12',
    learnerId: 'lrn-9481',
    learnerName: 'Trần Hải Nam',
    learnerAvatar: '👨‍🎓',
    type: 'SINK_SPEND',
    currency: 'coins',
    amount: -200,
    source: 'SHOP_PURCHASE',
    itemId: 'item_streak_freeze',
    itemOrQuestName: 'Bảo Hiểm Chuỗi (Streak Freeze)',
    balanceBefore: 640,
    balanceAfter: 320,
    status: 'COMPLETED',
    deviceInfo: 'iPhone 15 Pro · iOS 17.5',
    clientVersion: 'snapVocab v2.4.1',
    note: 'Mua qua sự kiện Weekend Streak Rescue',
  },
  {
    id: 'tx-20260910-0940',
    timestamp: '2026-09-10 14:35:04',
    learnerId: 'lrn-4820',
    learnerName: 'Nguyễn Thị Thảo',
    learnerAvatar: '👩‍💼',
    type: 'FAUCET_EARN',
    currency: 'coins',
    amount: 150,
    source: 'STREAK_BONUS',
    itemOrQuestName: 'Cột Mốc Streak 14 Ngày Liên Tục',
    balanceBefore: 890,
    balanceAfter: 1040,
    status: 'COMPLETED',
    deviceInfo: 'Samsung Galaxy S24 · Android 14',
    clientVersion: 'snapVocab v2.4.0',
  },
  {
    id: 'tx-20260910-0939',
    timestamp: '2026-09-10 14:12:30',
    learnerId: 'lrn-3301',
    learnerName: 'Lê Hoàng Long',
    learnerAvatar: '🧑‍💻',
    type: 'SINK_SPEND',
    currency: 'gems',
    amount: -75,
    source: 'SHOP_PURCHASE',
    itemId: 'item_frame_goldencrown',
    itemOrQuestName: 'Khung Rồng Vàng (Golden Crown)',
    balanceBefore: 150,
    balanceAfter: 75,
    status: 'COMPLETED',
    deviceInfo: 'iPhone 14 · iOS 17.4',
    clientVersion: 'snapVocab v2.4.1',
    note: 'Trang bị thành công vào avatar cá nhân',
  },
  {
    id: 'tx-20260910-0938',
    timestamp: '2026-09-10 13:58:22',
    learnerId: 'lrn-7194',
    learnerName: 'Phạm Quỳnh Anh',
    learnerAvatar: '👩‍🎓',
    type: 'FAUCET_EARN',
    currency: 'coins',
    amount: 50,
    source: 'MISSION_REWARD',
    itemOrQuestName: 'Nhiệm Vụ Ngày: Ôn Tập 15 Từ Flashcard',
    balanceBefore: 310,
    balanceAfter: 360,
    status: 'COMPLETED',
    deviceInfo: 'Xiaomi 13 · Android 13',
    clientVersion: 'snapVocab v2.3.9',
  },
  {
    id: 'tx-20260910-0937',
    timestamp: '2026-09-10 13:40:15',
    learnerId: 'lrn-1082',
    learnerName: 'Vũ Đức Trọng',
    learnerAvatar: '👨‍🎨',
    type: 'SINK_SPEND',
    currency: 'coins',
    amount: -850,
    source: 'SHOP_PURCHASE',
    itemId: 'item_deck_master',
    itemOrQuestName: 'Deck TOEIC 900+ Master Vocab',
    balanceBefore: 1250,
    balanceAfter: 400,
    status: 'COMPLETED',
    deviceInfo: 'iPhone 13 Mini · iOS 16.6',
    clientVersion: 'snapVocab v2.4.1',
  },
  {
    id: 'tx-20260910-0936',
    timestamp: '2026-09-10 13:15:40',
    learnerId: 'lrn-84920',
    learnerName: 'Nguyễn Minh (Warning)',
    learnerAvatar: '🤖',
    type: 'FAUCET_EARN',
    currency: 'coins',
    amount: 2200,
    source: 'MISSION_REWARD',
    itemOrQuestName: 'Hoàn Thành Chuỗi 42 Bài Học Cấp Tốc',
    balanceBefore: 200,
    balanceAfter: 2400,
    status: 'FLAGGED',
    deviceInfo: 'Unknown Linux Emulator',
    clientVersion: 'snapVocab v2.1.0',
    note: 'Tốc độ hoàn thành bất thường (15 phút) - Đang bị giữ để kiểm tra chống bot',
  },
  {
    id: 'tx-20260910-0935',
    timestamp: '2026-09-10 12:50:11',
    learnerId: 'lrn-5521',
    learnerName: 'Đặng Mai Linh',
    learnerAvatar: '👩‍🔬',
    type: 'SINK_SPEND',
    currency: 'coins',
    amount: -200,
    source: 'SHOP_PURCHASE',
    itemId: 'item_xp_booster',
    itemOrQuestName: 'Nhân Đôi KN (XP Booster)',
    balanceBefore: 490,
    balanceAfter: 290,
    status: 'COMPLETED',
    deviceInfo: 'iPhone 15 · iOS 17.5',
    clientVersion: 'snapVocab v2.4.1',
  },
  {
    id: 'tx-20260910-0934',
    timestamp: '2026-09-10 12:22:19',
    learnerId: 'lrn-6632',
    learnerName: 'Bùi Gia Huy',
    learnerAvatar: '🧑‍🚀',
    type: 'FAUCET_EARN',
    currency: 'gems',
    amount: 20,
    source: 'CHEST_REWARD',
    itemOrQuestName: 'Rương Thăng Hạng Bạc (Silver League)',
    balanceBefore: 60,
    balanceAfter: 80,
    status: 'COMPLETED',
    deviceInfo: 'OPPO Reno 10 · Android 14',
    clientVersion: 'snapVocab v2.4.0',
  },
  {
    id: 'tx-20260910-0933',
    timestamp: '2026-09-10 11:45:00',
    learnerId: 'lrn-2940',
    learnerName: 'Hoàng Kim Oanh',
    learnerAvatar: '👩‍🏫',
    type: 'SINK_SPEND',
    currency: 'coins',
    amount: -650,
    source: 'SHOP_PURCHASE',
    itemId: 'item_frame_owl',
    itemOrQuestName: 'Khung Cú Đêm (Night Owl)',
    balanceBefore: 755,
    balanceAfter: 105,
    status: 'COMPLETED',
    deviceInfo: 'iPad Pro 11 · iPadOS 17.4',
    clientVersion: 'snapVocab v2.4.1',
  },
  {
    id: 'tx-20260910-0932',
    timestamp: '2026-09-10 11:10:33',
    learnerId: 'lrn-4019',
    learnerName: 'Đỗ Tuấn Kiệt',
    learnerAvatar: '👨‍🔧',
    type: 'FAUCET_EARN',
    currency: 'coins',
    amount: 100,
    source: 'ADMIN_ADJUSTMENT',
    itemOrQuestName: 'Đền bù sự cố gián đoạn AI Scan Server',
    balanceBefore: 150,
    balanceAfter: 250,
    status: 'COMPLETED',
    deviceInfo: 'Web Console',
    clientVersion: 'Admin System',
    note: 'Thao tác bởi Lead Operator kèm Ticket #TCK-892',
  },
  {
    id: 'tx-20260910-0931',
    timestamp: '2026-09-10 10:30:54',
    learnerId: 'lrn-9102',
    learnerName: 'Ngô Bảo Châu',
    learnerAvatar: '🧑‍🎓',
    type: 'SINK_SPEND',
    currency: 'coins',
    amount: -1500,
    source: 'SHOP_PURCHASE',
    itemId: 'item_trophy',
    itemOrQuestName: 'Cúp Vàng Thử Thách (Gold Challenge Trophy)',
    balanceBefore: 1730,
    balanceAfter: 230,
    status: 'COMPLETED',
    deviceInfo: 'iPhone 12 Pro · iOS 16.5',
    clientVersion: 'snapVocab v2.3.8',
  },
  {
    id: 'tx-20260910-0930',
    timestamp: '2026-09-10 09:55:18',
    learnerId: 'lrn-3811',
    learnerName: 'Dương Yến Nhi',
    learnerAvatar: '👩‍🎤',
    type: 'FAUCET_EARN',
    currency: 'coins',
    amount: 80,
    source: 'MISSION_REWARD',
    itemOrQuestName: 'Nhiệm Vụ Tuần: Học 50 Từ Thuộc Topic Du Lịch',
    balanceBefore: 420,
    balanceAfter: 500,
    status: 'COMPLETED',
    deviceInfo: 'Samsung Galaxy A54 · Android 14',
    clientVersion: 'snapVocab v2.4.0',
  },
];
