import {
  Mission,
  DailyCycleConfig,
  WeeklyMilestoneConfig,
  MissionGuardrailConfig,
  MissionViolation,
  LearnerMissionProgressSample,
} from './types';

export const INITIAL_MISSIONS: Mission[] = [
  // ----------------------------------------------------
  // DAILY MISSIONS POOL (5 MANDATORY + BONUS)
  // ----------------------------------------------------
  {
    id: 'ms-d-01',
    code: 'MS-D-01',
    title: 'Quét 3 đồ vật quanh bạn (AI Camera)',
    description: 'Sử dụng AI Camera nhận diện và lưu tối thiểu 3 từ vựng mới vào sổ tay.',
    type: 'daily',
    actionType: 'SCAN_OBJECT',
    targetCount: 3,
    unit: 'lượt scan có lưu từ',
    difficulty: 'easy',
    reward: { xp: 40, coins: 60 },
    weight: 95,
    status: 'active',
    targetAudience: 'all',
    isBonus: false,
    completionRate: 84.5,
    claimRate: 78.2,
    totalCompletedCount: 1420,
    totalClaimedCount: 1315,
    lastUpdated: '2026-09-09 10:30',
    updatedBy: 'Lead Admin Hoà',
    auditNotes: 'Nhiệm vụ signature của SnapVocab, gắn điều kiện F-GAME-11 chống spam ảnh trống',
  },
  {
    id: 'ms-d-02',
    code: 'MS-D-02',
    title: 'Ôn tập 15 thẻ từ vựng đến hạn (SRS)',
    description: 'Hoàn thành lượt ôn tập thuật toán lặp ngắt quãng trong ngày.',
    type: 'daily',
    actionType: 'REVIEW_SRS',
    targetCount: 15,
    unit: 'thẻ flashcard',
    difficulty: 'easy',
    reward: { xp: 35, coins: 50 },
    weight: 90,
    status: 'active',
    targetAudience: 'all',
    isBonus: false,
    completionRate: 79.1,
    claimRate: 72.8,
    totalCompletedCount: 1320,
    totalClaimedCount: 1215,
    lastUpdated: '2026-09-08 14:15',
    updatedBy: 'Admin Content',
  },
  {
    id: 'ms-d-03',
    code: 'MS-D-03',
    title: 'Học 5 từ mới trong chủ đề bất kỳ',
    description: 'Khám phá và ghi nhớ 5 từ vựng mới thuộc danh mục Topics & Decks.',
    type: 'daily',
    actionType: 'LEARN_NEW_WORDS',
    targetCount: 5,
    unit: 'từ mới',
    difficulty: 'medium',
    reward: { xp: 50, coins: 80 },
    weight: 85,
    status: 'active',
    targetAudience: 'all',
    isBonus: false,
    completionRate: 68.4,
    claimRate: 62.0,
    totalCompletedCount: 980,
    totalClaimedCount: 890,
    lastUpdated: '2026-09-07 09:00',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'ms-d-04',
    code: 'MS-D-04',
    title: 'Đạt điểm tối đa (100%) trong 1 bài Quiz',
    description: 'Vượt qua bài trắc nghiệm kiểm tra nhanh mà không mắc lỗi sai nào.',
    type: 'daily',
    actionType: 'QUIZ_PERFECT',
    targetCount: 1,
    unit: 'bài quiz 100%',
    difficulty: 'hard',
    reward: { xp: 60, coins: 100, gems: 1 },
    weight: 75,
    status: 'active',
    targetAudience: 'intermediate',
    isBonus: false,
    completionRate: 52.3,
    claimRate: 49.8,
    totalCompletedCount: 750,
    totalClaimedCount: 712,
    lastUpdated: '2026-09-06 16:40',
    updatedBy: 'Admin Gamification',
  },
  {
    id: 'ms-d-05',
    code: 'MS-D-05',
    title: 'Nghe luyện phát âm 10 từ chuẩn bản xứ',
    description: 'Nghe phát âm chuẩn US/UK bằng công nghệ TTS trong Content Studio hoặc Flashcard.',
    type: 'daily',
    actionType: 'LISTEN_AUDIO',
    targetCount: 10,
    unit: 'lượt nghe audio',
    difficulty: 'easy',
    reward: { xp: 30, coins: 40 },
    weight: 80,
    status: 'active',
    targetAudience: 'all',
    isBonus: false,
    completionRate: 88.2,
    claimRate: 82.5,
    totalCompletedCount: 1540,
    totalClaimedCount: 1440,
    lastUpdated: '2026-09-09 11:20',
    updatedBy: 'Admin Content',
  },
  {
    id: 'ms-d-06',
    code: 'MS-D-06',
    title: 'Nhiệm vụ thưởng thêm: Duy trì chuỗi Streak hôm nay',
    description: 'Hoàn thành ít nhất một hoạt động học tập để bảo toàn ngọn lửa Streak.',
    type: 'daily',
    actionType: 'MAINTAIN_STREAK',
    targetCount: 1,
    unit: 'ngày streak',
    difficulty: 'easy',
    reward: { xp: 45, coins: 70, gems: 1 },
    weight: 100,
    status: 'active',
    targetAudience: 'all',
    isBonus: true,
    completionRate: 91.5,
    claimRate: 85.0,
    totalCompletedCount: 1890,
    totalClaimedCount: 1755,
    lastUpdated: '2026-09-05 08:30',
    updatedBy: 'Lead Admin Hoà',
    auditNotes: 'Bonus Mission độc lập, không tính vào điều kiện mở rương Daily Chest',
  },
  {
    id: 'ms-d-07',
    code: 'MS-D-07',
    title: 'Hoàn tất 1 bài học thuộc nhóm từ C1 Advanced',
    description: 'Chinh phục danh mục từ vựng học thuật trình độ C1/C2.',
    type: 'daily',
    actionType: 'LEARN_NEW_WORDS',
    targetCount: 8,
    unit: 'từ C1',
    difficulty: 'hard',
    reward: { xp: 80, coins: 120, gems: 2 },
    weight: 40,
    status: 'draft',
    targetAudience: 'advanced',
    isBonus: false,
    completionRate: 38.0,
    claimRate: 35.0,
    totalCompletedCount: 210,
    totalClaimedCount: 195,
    lastUpdated: '2026-09-10 08:15',
    updatedBy: 'Content Specialist Mai',
    auditNotes: 'Đang chạy thử nghiệm trong sandbox trước khi đưa vào pool luân phiên',
  },
  {
    id: 'ms-d-08',
    code: 'MS-D-08',
    title: 'Quét 5 đồ vật thuộc chủ đề Nhà Bếp & Ẩm Thực',
    description: 'Thử thách đặc biệt mở rộng vốn từ gia dụng hàng ngày qua camera scan.',
    type: 'daily',
    actionType: 'SCAN_OBJECT',
    targetCount: 5,
    unit: 'đồ vật bếp',
    difficulty: 'medium',
    reward: { xp: 55, coins: 90 },
    weight: 60,
    status: 'scheduled',
    targetAudience: 'all',
    isBonus: false,
    validFrom: '2026-09-15 00:00',
    validTo: '2026-09-22 23:59',
    completionRate: 0,
    claimRate: 0,
    totalCompletedCount: 0,
    totalClaimedCount: 0,
    lastUpdated: '2026-09-09 15:30',
    updatedBy: 'LiveOps Campaign Lead',
  },

  // ----------------------------------------------------
  // WEEKLY MILESTONES & SPECIAL CHALLENGES
  // ----------------------------------------------------
  {
    id: 'ms-w-01',
    code: 'MS-W-01',
    title: 'Thu thập đủ 5 Activity Stamps trong tuần',
    description: 'Hoàn thành trọn vẹn 5/5 nhiệm vụ ngày trong ít nhất 5 ngày từ Thứ 2 tới Chủ Nhật.',
    type: 'weekly',
    actionType: 'MAINTAIN_STREAK',
    targetCount: 5,
    unit: 'activity stamps',
    difficulty: 'medium',
    reward: { xp: 200, coins: 350, gems: 5 },
    weight: 100,
    status: 'active',
    targetAudience: 'all',
    completionRate: 64.2,
    claimRate: 58.7,
    totalCompletedCount: 840,
    totalClaimedCount: 768,
    lastUpdated: '2026-09-01 00:00',
    updatedBy: 'Super Admin Hoàng',
  },
  {
    id: 'ms-w-02',
    code: 'MS-W-02',
    title: 'Tổng lượt ôn tập SRS đạt 100 thẻ từ',
    description: 'Duy trì trí nhớ dài hạn bằng việc ôn tập đều đặn 100 thẻ flashcard trong tuần.',
    type: 'weekly',
    actionType: 'REVIEW_SRS',
    targetCount: 100,
    unit: 'thẻ SRS',
    difficulty: 'medium',
    reward: { xp: 250, coins: 400, gems: 6 },
    weight: 90,
    status: 'active',
    targetAudience: 'all',
    completionRate: 59.8,
    claimRate: 54.1,
    totalCompletedCount: 720,
    totalClaimedCount: 651,
    lastUpdated: '2026-09-01 00:00',
    updatedBy: 'Admin Content',
  },
  {
    id: 'ms-w-03',
    code: 'MS-W-03',
    title: 'Khám phá và làm chủ 2 chủ đề từ vựng mới',
    description: 'Hoàn thành toàn bộ thẻ flashcard trong 2 Topics thuộc hệ thống Topics & Decks.',
    type: 'weekly',
    actionType: 'EXPLORE_TOPIC',
    targetCount: 2,
    unit: 'chủ đề hoàn tất',
    difficulty: 'hard',
    reward: { xp: 300, coins: 500, gems: 8 },
    weight: 80,
    status: 'active',
    targetAudience: 'all',
    completionRate: 46.5,
    claimRate: 42.0,
    totalCompletedCount: 560,
    totalClaimedCount: 505,
    lastUpdated: '2026-09-01 00:00',
    updatedBy: 'Admin Gamification',
  },
  {
    id: 'mission_draft_77',
    code: 'MS-W-04',
    title: 'Chuỗi Chinh Phục 500 Từ C1 (Thử Nghiệm Mùa Thi)',
    description: 'Nhiệm vụ tuần đặc biệt dành cho nhóm học viên ôn thi chứng chỉ IELTS/TOEIC cấp tốc.',
    type: 'weekly',
    actionType: 'LEARN_NEW_WORDS',
    targetCount: 500,
    unit: 'từ vựng C1',
    difficulty: 'hard',
    reward: { xp: 800, coins: 1500, gems: 25 },
    weight: 30,
    status: 'active',
    targetAudience: 'advanced',
    completionRate: 22.4,
    claimRate: 20.1,
    totalCompletedCount: 140,
    totalClaimedCount: 125,
    lastUpdated: '2026-09-07 11:20',
    updatedBy: 'Super Admin Hoàng',
    auditNotes: 'Cấp quyền ngoại lệ vượt trần 1,000 Coins (ID vio-03 trong Economy Guardrails)',
  },

  // ----------------------------------------------------
  // ACHIEVEMENTS & LIFETIME MILESTONES
  // ----------------------------------------------------
  {
    id: 'ms-ach-01',
    code: 'MS-ACH-01',
    title: 'Bậc Thầy Nhận Diện AI (100 Đồ Vật Thực Tế)',
    description: 'Sử dụng AI Camera quét thành công 100 đồ vật và lưu vào từ điển cá nhân.',
    type: 'achievement',
    actionType: 'SCAN_OBJECT',
    targetCount: 100,
    unit: 'đồ vật scan',
    difficulty: 'hard',
    reward: { xp: 500, coins: 800, gems: 20, badgeId: 'badge-ai-master' },
    weight: 50,
    status: 'active',
    targetAudience: 'all',
    completionRate: 18.5,
    claimRate: 18.0,
    totalCompletedCount: 420,
    totalClaimedCount: 410,
    lastUpdated: '2026-08-15 09:00',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'ms-ach-02',
    code: 'MS-ACH-02',
    title: 'Ngọn Lửa Bất Diệt (Streak 30 Ngày Liên Tục)',
    description: 'Học tập không gián đoạn liên tiếp 30 ngày trên ứng dụng SnapVocab.',
    type: 'achievement',
    actionType: 'MAINTAIN_STREAK',
    targetCount: 30,
    unit: 'ngày liên tục',
    difficulty: 'hard',
    reward: { xp: 600, coins: 1000, gems: 30, badgeId: 'badge-streak-30' },
    weight: 50,
    status: 'active',
    targetAudience: 'all',
    completionRate: 12.8,
    claimRate: 12.5,
    totalCompletedCount: 290,
    totalClaimedCount: 284,
    lastUpdated: '2026-08-15 09:00',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'ms-ach-03',
    code: 'MS-ACH-03',
    title: 'Kho Tàng Từ Vựng (Lưu Trữ 1,000 Từ Vựng)',
    description: 'Xây dựng kho từ điển cá nhân đạt mốc 1,000 thẻ từ phong phú.',
    type: 'achievement',
    actionType: 'LEARN_NEW_WORDS',
    targetCount: 1000,
    unit: 'thẻ từ vựng',
    difficulty: 'hard',
    reward: { xp: 1000, coins: 1000, gems: 50, badgeId: 'badge-vocab-titan' },
    weight: 50,
    status: 'active',
    targetAudience: 'all',
    completionRate: 8.4,
    claimRate: 8.2,
    totalCompletedCount: 185,
    totalClaimedCount: 181,
    lastUpdated: '2026-08-15 09:00',
    updatedBy: 'Super Admin Hoàng',
  },
  {
    id: 'ms-ach-04',
    code: 'MS-ACH-04',
    title: 'Thử Thách Flash Sale: Chiếm Lĩnh Shop Items (Archived)',
    description: 'Mua 5 vật phẩm bất kỳ trong cửa hàng Shop & Economy trong tuần lễ khai trương.',
    type: 'achievement',
    actionType: 'EXPLORE_TOPIC',
    targetCount: 5,
    unit: 'vật phẩm Shop',
    difficulty: 'medium',
    reward: { xp: 200, coins: 300 },
    weight: 10,
    status: 'archived',
    targetAudience: 'all',
    completionRate: 45.0,
    claimRate: 44.0,
    totalCompletedCount: 310,
    totalClaimedCount: 304,
    lastUpdated: '2026-09-01 10:00',
    updatedBy: 'Admin Gamification',
    auditNotes: 'Đã đóng sau chiến dịch khởi chạy M3',
  },
];

// ----------------------------------------------------
// DEFAULT DAILY RESET & CHEST CONFIGURATION
// ----------------------------------------------------
export const DEFAULT_DAILY_CYCLE_CONFIG: DailyCycleConfig = {
  resetTime: '00:00',
  timeZone: 'Asia/Ho_Chi_Minh (GMT+7)',
  requiredDailyCount: 5,
  maxBonusCount: 1,
  dailyChestReward: {
    coins: 150,
    xp: 50,
    gems: 2,
    chestName: 'Rương Kho Báu Hàng Ngày (Daily Chest)',
  },
  weightedRandomSeed: 'snap-liveops-v2-auto-rotate',
  autoRefreshPool: true,
};

// ----------------------------------------------------
// DEFAULT WEEKLY STAMP MILESTONES
// ----------------------------------------------------
export const DEFAULT_WEEKLY_CONFIG: WeeklyMilestoneConfig = {
  cycleName: 'Thứ 2 → Chủ Nhật (00:00 GMT+7)',
  totalStampsMax: 7,
  milestones: [
    {
      stampsRequired: 3,
      tier: 'bronze',
      chestName: 'Rương Đồng Cần Mẫn',
      reward: {
        coins: 250,
        xp: 100,
        gems: 3,
      },
      icon: '🥉',
    },
    {
      stampsRequired: 5,
      tier: 'silver',
      chestName: 'Rương Bạc Kiên Trì',
      reward: {
        coins: 500,
        xp: 200,
        gems: 6,
        exclusiveItem: 'Booster x1.5 XP (2 giờ)',
      },
      icon: '🥈',
    },
    {
      stampsRequired: 7,
      tier: 'gold',
      chestName: 'Rương Vàng Xuất Sắc',
      reward: {
        coins: 1000,
        xp: 400,
        gems: 15,
        exclusiveItem: 'Khung Avatar Hoàng Gia & 1 Vé Streak Freeze',
      },
      icon: '👑',
    },
  ],
};

// ----------------------------------------------------
// DEFAULT GUARDRAIL POLICY
// ----------------------------------------------------
export const DEFAULT_MISSION_GUARDRAILS: MissionGuardrailConfig = {
  maxCoinsCapPerQuest: 1000,
  maxGemsCapPerQuest: 100,
  maxDailyPoolCoinsOutput: 2500,
  requireSuperAdminForOverride: true,
  antiSpamScanRule: true, // F-GAME-11
  strictIdempotencyKey: true,
  notifyLearnerBeforeResetHours: 2,
};

// ----------------------------------------------------
// SAMPLE GUARDRAIL VIOLATIONS
// ----------------------------------------------------
export const INITIAL_MISSION_VIOLATIONS: MissionViolation[] = [
  {
    id: 'vio-quest-01',
    missionId: 'mission_draft_77',
    missionCode: 'MS-W-04',
    missionTitle: 'Chuỗi Chinh Phục 500 Từ C1 (Thử Nghiệm Mùa Thi)',
    severity: 'high',
    violationType: 'COIN_CAP_EXCEEDED',
    description: 'Cấu hình phần thưởng 1,500 Coins vượt trần trần an toàn 1,000 Coins (+50%).',
    timestamp: '2026-09-07 11:20:45',
    status: 'whitelisted',
    mitigatedBy: 'Super Admin Hoàng',
    reason: 'Đã duyệt ngoại lệ cho chiến dịch mùa thi chứng chỉ, kiểm soát đối tượng C1',
  },
  {
    id: 'vio-quest-02',
    missionId: 'ms-d-07',
    missionCode: 'MS-D-07',
    missionTitle: 'Hoàn tất 1 bài học thuộc nhóm từ C1 Advanced',
    severity: 'medium',
    violationType: 'ANTI_CHEAT_SUSPICION',
    description: 'Phát hiện tỷ lệ claim trong 15 phút đầu sau reset vượt mức 80% bất thường.',
    timestamp: '2026-09-08 00:18:22',
    status: 'mitigated',
    mitigatedBy: 'Lead Admin Hoà',
    reason: 'Đã kiểm tra log idempotency, do lượng học viên thức đêm cày bài đồng loạt',
  },
  {
    id: 'vio-quest-03',
    missionId: 'ms-ach-03',
    missionCode: 'MS-ACH-03',
    missionTitle: 'Kho Tàng Từ Vựng (Lưu Trữ 1,000 Từ Vựng)',
    severity: 'low',
    violationType: 'UNCLAIMED_EXPIRY_SPIKE',
    description: 'Mức thưởng 50 Gems tiệm cận trần cảnh báo (50/100 Gems), cần giám sát faucet.',
    timestamp: '2026-09-09 09:30:10',
    status: 'active',
  },
];

// ----------------------------------------------------
// SAMPLE LEARNER PROGRESS RECORDS
// ----------------------------------------------------
export const INITIAL_LEARNER_SAMPLES: LearnerMissionProgressSample[] = [
  {
    learnerId: 'lrn-9481',
    learnerName: 'Trần Hải Nam',
    avatar: '👨‍🎓',
    email: 'hainam.tran@gmail.com',
    currentStreakDays: 14,
    dailyCompleted: 5,
    dailyTotal: 5,
    dailyChestClaimed: true,
    weeklyStamps: 6,
    unclaimedCoinsAtRisk: 0,
    lastActiveTime: '2026-09-10 14:45',
    status: 'claimed_all',
    recentEventKey: 'EVT-CLAIM-D5-20260910-9481',
  },
  {
    learnerId: 'lrn-8832',
    learnerName: 'Nguyễn Thảo Linh',
    avatar: '👩‍💼',
    email: 'linh.nguyen@outlook.com',
    currentStreakDays: 7,
    dailyCompleted: 5,
    dailyTotal: 5,
    dailyChestClaimed: false,
    weeklyStamps: 4,
    unclaimedCoinsAtRisk: 150,
    lastActiveTime: '2026-09-10 13:20',
    status: 'unclaimed_risk',
    recentEventKey: 'EVT-COMPL-D5-20260910-8832',
  },
  {
    learnerId: 'lrn-7712',
    learnerName: 'Lê Minh Khôi',
    avatar: '🧑‍💻',
    email: 'khoi.le@tech.vn',
    currentStreakDays: 28,
    dailyCompleted: 4,
    dailyTotal: 5,
    dailyChestClaimed: false,
    weeklyStamps: 5,
    unclaimedCoinsAtRisk: 60,
    lastActiveTime: '2026-09-10 15:10',
    status: 'in_progress',
    recentEventKey: 'EVT-COMPL-D4-20260910-7712',
  },
  {
    learnerId: 'lrn-6401',
    learnerName: 'Phạm Quỳnh Anh',
    avatar: '👩‍🎨',
    email: 'quynhanh.p@gmail.com',
    currentStreakDays: 3,
    dailyCompleted: 2,
    dailyTotal: 5,
    dailyChestClaimed: false,
    weeklyStamps: 2,
    unclaimedCoinsAtRisk: 0,
    lastActiveTime: '2026-09-10 11:05',
    status: 'in_progress',
  },
  {
    learnerId: 'lrn-5520',
    learnerName: 'Hoàng Quốc Bảo',
    avatar: '🧑‍🚀',
    email: 'bao.hq@fastmail.com',
    currentStreakDays: 45,
    dailyCompleted: 5,
    dailyTotal: 5,
    dailyChestClaimed: true,
    weeklyStamps: 7,
    unclaimedCoinsAtRisk: 0,
    lastActiveTime: '2026-09-10 12:40',
    status: 'claimed_all',
    recentEventKey: 'EVT-CLAIM-W7-20260910-5520',
  },
  {
    learnerId: 'lrn-3910',
    learnerName: 'Đặng Tuấn Anh',
    avatar: '🕵️',
    email: 'tuananh.d@yahoo.com',
    currentStreakDays: 0,
    dailyCompleted: 5,
    dailyTotal: 5,
    dailyChestClaimed: false,
    weeklyStamps: 1,
    unclaimedCoinsAtRisk: 280,
    lastActiveTime: '2026-09-10 01:15',
    status: 'unclaimed_risk',
    recentEventKey: 'EVT-COMPL-D5-20260910-3910',
  },
];
