// ====================================================
// SNAPVOCAB AUDIT ACTIVITY LOG MOCK DATA
// Source of Truth: docs/design/design.md & docs/design/colors.js
// ====================================================

import { AuditLogEntry, AuditOperator } from './types';

export const AUDIT_OPERATORS: Record<string, AuditOperator> = {
  admin_hoang: {
    id: 'OP-01',
    name: 'Hoàng Minh Tuấn',
    role: 'SUPER_ADMIN',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    ipAddress: '113.161.44.12',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0.0.0',
  },
  editor_trang: {
    id: 'OP-02',
    name: 'Nguyễn Thu Trang',
    role: 'CONTENT_LEAD',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    ipAddress: '14.162.180.95',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_6) Safari/605.1.15',
  },
  support_anh: {
    id: 'OP-03',
    name: 'Trần Quỳnh Anh',
    role: 'SUPPORT_AGENT',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    ipAddress: '171.244.52.88',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/127.0.0.0',
  },
  support_minh: {
    id: 'OP-04',
    name: 'Lê Duy Minh',
    role: 'SUPPORT_AGENT',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    ipAddress: '27.72.101.44',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/128.0.0.0',
  },
  sentinel_bot: {
    id: 'OP-BOT',
    name: 'Sentinel Security Bot',
    role: 'AUTOMATED_SYSTEM',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    ipAddress: '10.0.8.1 (Internal VPC)',
    userAgent: 'SnapVocab-SentinelDaemon/v2.4.0',
  },
};

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'AUD-2026-0911-001',
    timestamp: '2026-09-11T08:42:15Z',
    domain: 'CONTENT_STUDIO',
    action: 'VOCAB_PUBLISHED',
    actionLabel: 'Phê duyệt & Xuất bản Thẻ từ vựng',
    severity: 'INFO',
    operator: AUDIT_OPERATORS.admin_hoang,
    targetEntity: {
      type: 'WORD',
      id: 'w-resilient',
      title: 'resilient (C1 - adjective)',
      navDeepLink: 'content-studio',
    },
    ticketId: 'TK-2026-0911-01',
    reason: 'Đã nghiệm thu định nghĩa tiếng Việt chuẩn, phiên âm IPA quốc tế và cấu hình giọng đọc TTS chuẩn US',
    details: 'Chuyển trạng thái thẻ từ IN_REVIEW sang PUBLISHED phục vụ phiên học Spaced Repetition hôm nay.',
    diff: {
      before: { status: 'review', verifiedAudio: false },
      after: { status: 'published', verifiedAudio: true, voice: 'en-US', speed: 1.0 },
    },
    canRollback: true,
    metadata: {
      executionTimeMs: 42,
      complianceValid: true,
      tamperHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      blockHeight: 10420,
    },
  },
  {
    id: 'AUD-2026-0911-002',
    timestamp: '2026-09-11T08:15:30Z',
    domain: 'AI_SCAN',
    action: 'AI_LABEL_CORRECTED',
    actionLabel: 'Sửa nhãn AI Scan & Lưu Dataset',
    severity: 'NOTICE',
    operator: AUDIT_OPERATORS.editor_trang,
    targetEntity: {
      type: 'SCAN',
      id: 'SCN-991',
      title: 'Báo cáo nhận diện ảnh "coffee cup ➔ mug"',
      navDeepLink: 'ai-queue',
    },
    ticketId: 'TK-2026-0911-02',
    reason: 'Active Learning loop §7.2: Người học phản hồi ảnh cốc sứ bị AI gán nhãn ly giấy mang đi.',
    details: 'Đã gán lại nhãn "mug", tính lại độ tin cậy và lưu ảnh crop vào tập fine-tuning Gemini Vision.',
    diff: {
      before: { predictedLabel: 'coffee cup', confidence: 0.72, fineTuned: false },
      after: { predictedLabel: 'mug', confidence: 0.98, fineTuned: true, rewardCoins: 15 },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 65,
      complianceValid: true,
      tamperHash: '4a6b2c89d9e0f123456789abcdef0123456789abcdef0123456789abcdef0123',
      blockHeight: 10419,
    },
  },
  {
    id: 'AUD-2026-0911-003',
    timestamp: '2026-09-11T07:50:12Z',
    domain: 'LIVEOPS_ECONOMY',
    action: 'GUARDRAIL_TRIGGERED',
    actionLabel: 'Kích hoạt Hàng rào An toàn Guardrail',
    severity: 'CRITICAL',
    operator: AUDIT_OPERATORS.sentinel_bot,
    targetEntity: {
      type: 'SYSTEM',
      id: 'GUARD-ECO-88',
      title: 'Nhiệm vụ "Cuối tuần bùng nổ"',
      navDeepLink: 'missions',
    },
    reason: 'Phát hiện cấu hình mức thưởng 1,500 Coins vượt trần an toàn kinh tế (Max Cap: 1,000 Coins) theo quy chuẩn §7.3.',
    details: 'Hệ thống tự động đình chỉ kích hoạt nhiệm vụ và gửi yêu cầu phê chuẩn đến Super Admin.',
    diff: {
      before: { targetReward: 1500, status: 'pending_launch' },
      after: { targetReward: 1000, status: 'blocked_by_guardrail', alertSent: true },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 18,
      guardrailRule: 'MAX_COINS_REWARD_CAP_1000',
      complianceValid: true,
      tamperHash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
      blockHeight: 10418,
    },
  },
  {
    id: 'AUD-2026-0911-004',
    timestamp: '2026-09-11T07:12:00Z',
    domain: 'LEARNERS_PEOPLE',
    action: 'STREAK_RECOVERED',
    actionLabel: 'Phục hồi Chuỗi Streak Học viên',
    severity: 'WARNING',
    operator: AUDIT_OPERATORS.support_anh,
    targetEntity: {
      type: 'LEARNER',
      id: 'USR-10829',
      title: 'Đặng Phương Thảo (Streak: 45 ngày)',
      navDeepLink: 'learners',
    },
    ticketId: 'TK-2026-7731',
    reason: 'Sự cố mất điện trung tâm dữ liệu gây ngắt phiên học lúc 23:50; đã xác minh qua log máy chủ.',
    details: 'Đã cấp bù chuỗi từ 0 lên 45 ngày kèm lời xin lỗi từ trung tâm chăm sóc học viên.',
    diff: {
      before: { currentStreak: 0, streakShields: 0 },
      after: { currentStreak: 45, streakShields: 1, compensatedGems: 20 },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 88,
      complianceValid: true,
      tamperHash: '9b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c',
      blockHeight: 10417,
    },
  },
  {
    id: 'AUD-2026-0911-005',
    timestamp: '2026-09-11T06:30:45Z',
    domain: 'SYSTEM_SECURITY',
    action: 'BULK_DATA_EXPORT',
    actionLabel: 'Trích xuất Dữ liệu Hàng loạt (CSV Export)',
    severity: 'SECURITY',
    operator: AUDIT_OPERATORS.admin_hoang,
    targetEntity: {
      type: 'SYSTEM',
      id: 'EXP-ROSTER-20260911',
      title: 'Danh bạ 1,280 học viên tích cực',
      navDeepLink: 'learners',
    },
    ticketId: 'TK-2026-EXP-01',
    reason: 'Phục vụ báo cáo kiểm toán số liệu FSRS retention quý 3 theo yêu cầu Ban Điều Hành.',
    details: 'Dữ liệu được mã hóa trước khi tải về; địa chỉ IP thao tác được gắn dấu vết watermark số.',
    diff: {
      before: { exportStatus: 'idle' },
      after: { exportStatus: 'completed', rowCount: 1280, checksum: 'sha256:d8a9e7' },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 310,
      complianceValid: true,
      tamperHash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
      blockHeight: 10416,
    },
  },
  {
    id: 'AUD-2026-0911-006',
    timestamp: '2026-09-11T05:40:00Z',
    domain: 'CONTENT_STUDIO',
    action: 'VOCAB_REVISED',
    actionLabel: 'Hiệu chỉnh Nghĩa & Thí dụ Ngữ cảnh',
    severity: 'INFO',
    operator: AUDIT_OPERATORS.editor_trang,
    targetEntity: {
      type: 'WORD',
      id: 'w-thermos',
      title: 'thermos (B1 - noun)',
      navDeepLink: 'content-studio',
    },
    ticketId: 'TK-2026-DICT-88',
    reason: 'Bổ sung ví dụ ngữ cảnh song ngữ Anh - Việt thực tế và hình ảnh thực tế đồ gia dụng.',
    details: 'Đã hoàn thiện ví dụ: "She poured steaming hot tea from the thermos into two cups."',
    diff: {
      before: { definitionVi: 'bình giữ nhiệt', examplesCount: 1 },
      after: { definitionVi: 'bình giữ nhiệt (nóng/lạnh)', examplesCount: 2, imageVerified: true },
    },
    canRollback: true,
    metadata: {
      executionTimeMs: 35,
      complianceValid: true,
      tamperHash: '3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d',
      blockHeight: 10415,
    },
  },
  {
    id: 'AUD-2026-0910-007',
    timestamp: '2026-09-10T22:15:10Z',
    domain: 'LEARNERS_PEOPLE',
    action: 'ACCOUNT_BANNED',
    actionLabel: 'Khóa Tài Khoản Vi Phạm Quy Chuẩn',
    severity: 'CRITICAL',
    operator: AUDIT_OPERATORS.sentinel_bot,
    targetEntity: {
      type: 'LEARNER',
      id: 'USR-10827',
      title: 'Lê Thu Hà (Status: suspended)',
      navDeepLink: 'learners',
    },
    ticketId: 'TK-2026-8812',
    reason: 'Phát hiện script macro tự động giải 200 flashcard trong 12 giây nhằm cày XP bảng xếp hạng Ruby.',
    details: 'Đã khóa tài khoản 30 ngày và tước bỏ toàn bộ điểm XP tuần gian lận.',
    diff: {
      before: { status: 'active', leagueTier: 'ruby' },
      after: { status: 'suspended', banDuration: '30d', strippedXp: 4800 },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 24,
      guardrailRule: 'ANTI_CHEAT_SPEED_ANOMALY',
      complianceValid: true,
      tamperHash: '5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f',
      blockHeight: 10414,
    },
  },
  {
    id: 'AUD-2026-0910-008',
    timestamp: '2026-09-10T20:30:00Z',
    domain: 'LIVEOPS_ECONOMY',
    action: 'SHOP_ITEM_UPDATED',
    actionLabel: 'Cập nhật Giá Flash Sale Cửa Hàng',
    severity: 'INFO',
    operator: AUDIT_OPERATORS.admin_hoang,
    targetEntity: {
      type: 'SHOP_ITEM',
      id: 'SHOP-BOOST-03',
      title: 'Streak Freeze Shield Pack (x3)',
      navDeepLink: 'shop',
    },
    reason: 'Kích hoạt chương trình Flash Sale cuối tuần hỗ trợ học viên trước kỳ thi TOEIC.',
    details: 'Giảm giá từ 120 Gems xuống 89 Gems, giới hạn mua 1 gói/học viên.',
    diff: {
      before: { priceGems: 120, badge: 'NONE' },
      after: { priceGems: 89, badge: 'HOT', limitPerUser: 1 },
    },
    canRollback: true,
    metadata: {
      executionTimeMs: 40,
      complianceValid: true,
      tamperHash: '7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b',
      blockHeight: 10413,
    },
  },
  {
    id: 'AUD-2026-0910-009',
    timestamp: '2026-09-10T18:45:22Z',
    domain: 'ISSUE_REPORTS',
    action: 'ISSUE_RESOLVED',
    actionLabel: 'Giải quyết Khiếu nại Sự cố Báo cáo',
    severity: 'INFO',
    operator: AUDIT_OPERATORS.support_minh,
    targetEntity: {
      type: 'TICKET',
      id: 'REP-2026-0908',
      title: 'Sự cố mất audio từ vựng "phenomenon"',
      navDeepLink: 'reports',
    },
    ticketId: 'TK-2026-9908',
    reason: 'Đã re-generate audio stream chuẩn Web Speech Synthesis US và sync Cloudflare CDN.',
    details: 'Đã gửi thông báo xác nhận đã sửa lỗi thành công tới học viên trên mobile.',
    diff: {
      before: { status: 'INVESTIGATING', audioValid: false },
      after: { status: 'RESOLVED', audioValid: true, resolvedDurationMins: 25 },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 52,
      complianceValid: true,
      tamperHash: '9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d',
      blockHeight: 10412,
    },
  },
  {
    id: 'AUD-2026-0910-010',
    timestamp: '2026-09-10T16:20:15Z',
    domain: 'SYSTEM_SECURITY',
    action: 'ROLE_ELEVATED',
    actionLabel: 'Cấp quyền Quản trị Lead Phân hệ',
    severity: 'SECURITY',
    operator: AUDIT_OPERATORS.admin_hoang,
    targetEntity: {
      type: 'SYSTEM',
      id: 'ADM-USER-02',
      title: 'Tài khoản: Nguyễn Thu Trang',
      navDeepLink: 'settings',
    },
    ticketId: 'TK-2026-SEC-44',
    reason: 'Bổ nhiệm vai trò Content Lead chịu trách nhiệm phê duyệt xuất bản từ điển CEFR B2-C2.',
    details: 'Kích hoạt quyền PUBLISH_OVERRIDE và BATCH_IMPORT_DICTIONARY kèm xác thực sinh trắc học.',
    diff: {
      before: { role: 'CONTENT_EDITOR', canPublish: false },
      after: { role: 'CONTENT_LEAD', canPublish: true, mfaEnabled: true },
    },
    canRollback: true,
    metadata: {
      executionTimeMs: 95,
      complianceValid: true,
      tamperHash: '1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f',
      blockHeight: 10411,
    },
  },
  {
    id: 'AUD-2026-0910-011',
    timestamp: '2026-09-10T14:10:00Z',
    domain: 'LIVEOPS_ECONOMY',
    action: 'CURRENCY_COMPENSATED',
    actionLabel: 'Cấp bù Tiền tệ Lỗi Thanh toán',
    severity: 'NOTICE',
    operator: AUDIT_OPERATORS.support_minh,
    targetEntity: {
      type: 'LEARNER',
      id: 'USR-10832',
      title: 'Nguyễn Duy Khang (Cấp bù 50 Gems)',
      navDeepLink: 'learners',
    },
    ticketId: 'TK-2026-6641',
    reason: 'Hệ thống billing trừ 2 lần do mạng lag khi mua Streak Freeze Chest trong sự kiện.',
    details: 'Đã hoàn bù 50 Gems vào ví người dùng và đóng ticket hỗ trợ khách hàng.',
    diff: {
      before: { balanceGems: 840 },
      after: { balanceGems: 890, compensationGranted: true },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 60,
      complianceValid: true,
      tamperHash: '3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b',
      blockHeight: 10410,
    },
  },
  {
    id: 'AUD-2026-0910-012',
    timestamp: '2026-09-10T11:05:40Z',
    domain: 'CONTENT_STUDIO',
    action: 'AUDIO_TTS_UPDATED',
    actionLabel: 'Cập nhật Giọng đọc AI & Tốc độ Audio',
    severity: 'INFO',
    operator: AUDIT_OPERATORS.editor_trang,
    targetEntity: {
      type: 'WORD',
      id: 'w-curious',
      title: 'curious (A2 - adjective)',
      navDeepLink: 'content-studio',
    },
    reason: 'Đổi voice từ en-GB sang en-US chuẩn tự nhiên và tinh chỉnh tốc độ đọc 0.95x theo feedback người học.',
    details: 'Đã kiểm tra qua Web Speech Synthesis API và sinh file audio đính kèm.',
    diff: {
      before: { voice: 'en-GB', speed: 1.0 },
      after: { voice: 'en-US', speed: 0.95, pitch: 1.0 },
    },
    canRollback: true,
    metadata: {
      executionTimeMs: 28,
      complianceValid: true,
      tamperHash: '5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
      blockHeight: 10409,
    },
  },
  {
    id: 'AUD-2026-0910-013',
    timestamp: '2026-09-10T09:00:15Z',
    domain: 'SYSTEM_SECURITY',
    action: 'ADMIN_LOGIN',
    actionLabel: 'Phiên Đăng Nhập Quản Trị Viên',
    severity: 'INFO',
    operator: AUDIT_OPERATORS.admin_hoang,
    targetEntity: {
      type: 'SYSTEM',
      id: 'AUTH-SESS-9081',
      title: 'Phiên làm việc Console Web Admin',
      navDeepLink: 'dashboard',
    },
    reason: 'Đăng nhập định kỳ bắt đầu ca làm việc quản trị LiveOps hệ thống.',
    details: 'Xác thực thành công với Passkey WebAuthn từ IP cố định văn phòng.',
    diff: {
      before: { sessionState: 'disconnected' },
      after: { sessionState: 'authenticated', mfaMethod: 'Passkey' },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 15,
      complianceValid: true,
      tamperHash: '7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f',
      blockHeight: 10408,
    },
  },
  {
    id: 'AUD-2026-0909-014',
    timestamp: '2026-09-09T17:35:10Z',
    domain: 'LEARNERS_PEOPLE',
    action: 'QUOTA_ADJUSTED',
    actionLabel: 'Tăng Hạn Mức Quota AI Camera Scan',
    severity: 'NOTICE',
    operator: AUDIT_OPERATORS.support_anh,
    targetEntity: {
      type: 'LEARNER',
      id: 'USR-10824',
      title: 'Nguyễn Quang Minh (Quota: +5 lượt)',
      navDeepLink: 'learners',
    },
    ticketId: 'TK-2026-1002',
    reason: 'Khuyến khích học viên tích cực hoàn thành chuỗi bài tập chụp ảnh thực tế môi trường văn phòng.',
    details: 'Nâng hạn mức từ 20 lượt lên 25 lượt/ngày có hiệu lực trong 30 ngày.',
    diff: {
      before: { dailyScanQuota: 20 },
      after: { dailyScanQuota: 25, bonusActive: true },
    },
    canRollback: true,
    metadata: {
      executionTimeMs: 44,
      complianceValid: true,
      tamperHash: '9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
      blockHeight: 10407,
    },
  },
  {
    id: 'AUD-2026-0909-015',
    timestamp: '2026-09-09T14:20:00Z',
    domain: 'CONTENT_STUDIO',
    action: 'DICTIONARY_IMPORTED',
    actionLabel: 'Nhập Từ Điển Chuyên Đề Hàng Loạt',
    severity: 'INFO',
    operator: AUDIT_OPERATORS.editor_trang,
    targetEntity: {
      type: 'WORD',
      id: 'TOPIC-OFFICE-45',
      title: 'Bộ từ vựng "Modern Workplace" (+45 từ)',
      navDeepLink: 'topics',
    },
    ticketId: 'TK-2026-IMPORT-03',
    reason: 'Bổ sung danh mục từ vựng văn phòng cho lộ trình ôn tập TOEIC 650+.',
    details: 'Đã xác thực định dạng CSV, tự động ánh xạ phiên âm IPA Oxford và tạo thẻ bài học.',
    diff: {
      before: { totalWordsInTopic: 0 },
      after: { totalWordsInTopic: 45, status: 'review_pending' },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 420,
      complianceValid: true,
      tamperHash: '1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d',
      blockHeight: 10406,
    },
  },
  {
    id: 'AUD-2026-0909-016',
    timestamp: '2026-09-09T10:15:30Z',
    domain: 'AI_SCAN',
    action: 'AI_DATASET_SAVED',
    actionLabel: 'Đóng gói Dataset Tinh Chỉnh Gemini Vision',
    severity: 'INFO',
    operator: AUDIT_OPERATORS.sentinel_bot,
    targetEntity: {
      type: 'SCAN',
      id: 'DS-VISION-202609',
      title: 'Tập dữ liệu phản hồi người dùng (+150 mẫu)',
      navDeepLink: 'ai-monitor',
    },
    reason: 'Định kỳ kết xuất dữ liệu sửa nhãn chính xác từ Active Learning feedback loop sang Cloud Storage.',
    details: 'Gói dữ liệu đã được gỡ bỏ siêu dữ liệu nhạy cảm (EXIF strip) và phân lớp bounding box.',
    diff: {
      before: { queueSize: 150 },
      after: { queueSize: 0, datasetVersion: 'v2.8-finetuned' },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 820,
      complianceValid: true,
      tamperHash: '3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f',
      blockHeight: 10405,
    },
  },
  {
    id: 'AUD-2026-0908-017',
    timestamp: '2026-09-08T16:50:11Z',
    domain: 'LEARNERS_PEOPLE',
    action: 'PASSWORD_RESET',
    actionLabel: 'Kích hoạt Đặt lại Mật khẩu Quản trị',
    severity: 'WARNING',
    operator: AUDIT_OPERATORS.support_anh,
    targetEntity: {
      type: 'LEARNER',
      id: 'USR-10835',
      title: 'Ngô Yến Nhi (Yêu cầu qua email hỗ trợ)',
      navDeepLink: 'learners',
    },
    ticketId: 'TK-2026-PWD-19',
    reason: 'Học viên bị mất thiết bị cũ và quên mật khẩu; đã xác minh danh tính qua số điện thoại đăng ký.',
    details: 'Đã tạo link reset an toàn dùng một lần (TTL 15 phút) gửi đến email đã xác minh.',
    diff: {
      before: { passwordResetAttempts: 3 },
      after: { passwordResetAttempts: 0, resetTokenGenerated: true },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 50,
      complianceValid: true,
      tamperHash: '5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b',
      blockHeight: 10404,
    },
  },
  {
    id: 'AUD-2026-0908-018',
    timestamp: '2026-09-08T11:40:00Z',
    domain: 'SYSTEM_SECURITY',
    action: 'SYSTEM_CONFIG_UPDATED',
    actionLabel: 'Cập nhật Cấu hình Spaced Repetition (FSRS)',
    severity: 'CRITICAL',
    operator: AUDIT_OPERATORS.admin_hoang,
    targetEntity: {
      type: 'SYSTEM',
      id: 'CFG-FSRS-GLOBAL',
      title: 'Thông số thuật toán ghi nhớ FSRS v4',
      navDeepLink: 'settings',
    },
    ticketId: 'TK-2026-FSRS-01',
    reason: 'Điều chỉnh Retention Target từ 88% lên 90% để nâng cao độ bền trí nhớ học viên chuẩn bị thi.',
    details: 'Cập nhật ma trận trọng số stability và request retention rate áp dụng toàn cầu.',
    diff: {
      before: { targetRetention: 0.88, maxIntervalDays: 180 },
      after: { targetRetention: 0.90, maxIntervalDays: 240 },
    },
    canRollback: true,
    metadata: {
      executionTimeMs: 120,
      complianceValid: true,
      tamperHash: '7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d',
      blockHeight: 10403,
    },
  },
  {
    id: 'AUD-2026-0907-019',
    timestamp: '2026-09-07T15:10:00Z',
    domain: 'CONTENT_STUDIO',
    action: 'VOCAB_ARCHIVED',
    actionLabel: 'Lưu trữ Thẻ Từ vựng Không còn dùng',
    severity: 'WARNING',
    operator: AUDIT_OPERATORS.editor_trang,
    targetEntity: {
      type: 'WORD',
      id: 'w-floppy-disk',
      title: 'floppy disk (A2 - noun)',
      navDeepLink: 'content-studio',
    },
    ticketId: 'TK-2026-ARCH-02',
    reason: 'Từ vựng ít xuất hiện trong đề thi TOEIC hiện đại; đưa về trạng thái Archived để tránh gây loãng bộ nhớ.',
    details: 'Thẻ được ẩn khỏi kho từ vựng đề xuất nhưng vẫn bảo lưu trong lịch sử ôn tập của các học viên cũ.',
    diff: {
      before: { status: 'published' },
      after: { status: 'archived', searchable: false },
    },
    canRollback: true,
    metadata: {
      executionTimeMs: 38,
      complianceValid: true,
      tamperHash: '9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f',
      blockHeight: 10402,
    },
  },
  {
    id: 'AUD-2026-0907-020',
    timestamp: '2026-09-07T09:30:20Z',
    domain: 'LIVEOPS_ECONOMY',
    action: 'SEASON_CONFIG_MODIFIED',
    actionLabel: 'Khai cuộc Mùa giải Leaderboard Mới',
    severity: 'INFO',
    operator: AUDIT_OPERATORS.admin_hoang,
    targetEntity: {
      type: 'SEASON',
      id: 'SEAS-2026-AUTUMN',
      title: 'Mùa giải "Chiến Thần Tốc Độ Thu 2026"',
      navDeepLink: 'seasons',
    },
    reason: 'Khởi động mùa giải bảng xếp hạng 14 ngày kèm danh hiệu độc quyền cho Top 3 giải Diamond.',
    details: 'Phần thưởng: 2,000 Coins, 250 Gems và huy hiệu động [Phượng Hoàng Bất Diệt].',
    diff: {
      before: { seasonState: 'upcoming' },
      after: { seasonState: 'active', registeredCohorts: 84 },
    },
    canRollback: false,
    metadata: {
      executionTimeMs: 145,
      complianceValid: true,
      tamperHash: '0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a',
      blockHeight: 10401,
    },
  },
];
