import { CardTemplate, DeckTemplateMapping } from './types';
import { CardViewModel } from '../flashcard/types';

export const INITIAL_SYSTEM_TEMPLATES: CardTemplate[] = [
  {
    id: 'tpl-sys-classic',
    code: 'CLASSIC',
    name: 'Classic Flip',
    nameVi: 'Lật Thẻ Kinh Điển',
    description: 'Thẻ flashcard truyền thống: mặt trước hiển thị Từ vựng (kèm phát âm & ảnh), mặt sau hiển thị Định nghĩa tiếng Việt, Từ loại và Ví dụ minh họa.',
    baseLayout: 'SINGLE_COLUMN',
    interactionType: 'FLIP',
    isSystem: true,
    isDefault: true,
    status: 'active',
    authorName: 'SnapVocab Core Team',
    authorRole: 'system',
    deckCount: 14,
    activeLearners: 8420,
    retentionRate: 88.6,
    tags: ['Mặc định', 'Phổ biến nhất', 'Toàn diện'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
    fields: [
      // FRONT
      {
        id: 'f-front-1',
        side: 'FRONT',
        fieldType: 'IMAGE',
        displayOrder: 1,
        isPrimary: false,
      },
      {
        id: 'f-front-2',
        side: 'FRONT',
        fieldType: 'WORD',
        displayOrder: 2,
        isPrimary: true,
      },
      {
        id: 'f-front-3',
        side: 'FRONT',
        fieldType: 'IPA',
        displayOrder: 3,
        isPrimary: false,
      },
      {
        id: 'f-front-4',
        side: 'FRONT',
        fieldType: 'AUDIO',
        displayOrder: 4,
        isPrimary: false,
        fieldConfig: { autoPlay: false },
      },
      // BACK
      {
        id: 'f-back-1',
        side: 'BACK',
        fieldType: 'MEANING',
        displayOrder: 1,
        isPrimary: true,
        fieldConfig: { showAll: true },
      },
      {
        id: 'f-back-2',
        side: 'BACK',
        fieldType: 'PART_OF_SPEECH',
        displayOrder: 2,
        isPrimary: false,
      },
      {
        id: 'f-back-3',
        side: 'BACK',
        fieldType: 'EXAMPLE',
        displayOrder: 3,
        isPrimary: false,
      },
    ],
  },
  {
    id: 'tpl-sys-reverse',
    code: 'REVERSE',
    name: 'Reverse Recall',
    nameVi: 'Lật Ngược (Nghĩa ➔ Từ)',
    description: 'Rèn luyện phản xạ chủ động (Active Recall): mặt trước đưa ra Định nghĩa tiếng Việt & Gợi ý ngữ cảnh, người học tự nhớ ra Từ tiếng Anh trước khi lật.',
    baseLayout: 'SINGLE_COLUMN',
    interactionType: 'FLIP',
    isSystem: true,
    isDefault: false,
    status: 'active',
    authorName: 'SnapVocab Core Team',
    authorRole: 'system',
    deckCount: 6,
    activeLearners: 3950,
    retentionRate: 84.2,
    tags: ['Active Recall', 'Luyện phản xạ'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-25T14:30:00Z',
    fields: [
      // FRONT
      {
        id: 'f-rev-front-1',
        side: 'FRONT',
        fieldType: 'MEANING',
        displayOrder: 1,
        isPrimary: true,
        fieldConfig: { showAll: true },
      },
      {
        id: 'f-rev-front-2',
        side: 'FRONT',
        fieldType: 'PART_OF_SPEECH',
        displayOrder: 2,
        isPrimary: false,
      },
      {
        id: 'f-rev-front-3',
        side: 'FRONT',
        fieldType: 'IMAGE',
        displayOrder: 3,
        isPrimary: false,
      },
      // BACK
      {
        id: 'f-rev-back-1',
        side: 'BACK',
        fieldType: 'WORD',
        displayOrder: 1,
        isPrimary: true,
      },
      {
        id: 'f-rev-back-2',
        side: 'BACK',
        fieldType: 'IPA',
        displayOrder: 2,
        isPrimary: false,
      },
      {
        id: 'f-rev-back-3',
        side: 'BACK',
        fieldType: 'AUDIO',
        displayOrder: 3,
        isPrimary: false,
        fieldConfig: { autoPlay: true },
      },
      {
        id: 'f-rev-back-4',
        side: 'BACK',
        fieldType: 'EXAMPLE',
        displayOrder: 4,
        isPrimary: false,
      },
    ],
  },
  {
    id: 'tpl-sys-listening',
    code: 'LISTENING',
    name: 'Audio Focus',
    nameVi: 'Nghe Nhận Diện Âm Thanh',
    description: 'Chuyên sâu luyện kỹ năng Nghe (Listening & Ear Training): mặt trước chỉ phát âm thanh chuẩn IPA và sóng âm thanh, mặt sau tiết lộ từ ngữ và nghĩa.',
    baseLayout: 'AUDIO_CENTER',
    interactionType: 'FLIP',
    isSystem: true,
    isDefault: false,
    status: 'active',
    authorName: 'SnapVocab Audio Lab',
    authorRole: 'system',
    deckCount: 4,
    activeLearners: 2840,
    retentionRate: 89.1,
    tags: ['Luyện nghe', 'Âm thanh US/UK', 'Ear Training'],
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-09-04T09:15:00Z',
    fields: [
      // FRONT
      {
        id: 'f-list-front-1',
        side: 'FRONT',
        fieldType: 'AUDIO',
        displayOrder: 1,
        isPrimary: true,
        fieldConfig: { autoPlay: true },
      },
      {
        id: 'f-list-front-2',
        side: 'FRONT',
        fieldType: 'PART_OF_SPEECH',
        displayOrder: 2,
        isPrimary: false,
      },
      // BACK
      {
        id: 'f-list-back-1',
        side: 'BACK',
        fieldType: 'WORD',
        displayOrder: 1,
        isPrimary: true,
      },
      {
        id: 'f-list-back-2',
        side: 'BACK',
        fieldType: 'IPA',
        displayOrder: 2,
        isPrimary: false,
      },
      {
        id: 'f-list-back-3',
        side: 'BACK',
        fieldType: 'MEANING',
        displayOrder: 3,
        isPrimary: false,
      },
      {
        id: 'f-list-back-4',
        side: 'BACK',
        fieldType: 'EXAMPLE',
        displayOrder: 4,
        isPrimary: false,
      },
    ],
  },
  {
    id: 'tpl-sys-image',
    code: 'IMAGE_VOCAB',
    name: 'Visual Flash',
    nameVi: 'Thị Giác & Trực Quan (Ảnh)',
    description: 'Tối ưu cho việc ghi nhớ bằng hình ảnh não phải: Mặt trước phóng lớn ảnh minh họa chất lượng cao kèm độ tin cậy AI, mặt sau giải thích từ vựng.',
    baseLayout: 'IMAGE_TOP',
    interactionType: 'FLIP',
    isSystem: true,
    isDefault: false,
    status: 'active',
    authorName: 'SnapVocab Design Studio',
    authorRole: 'system',
    deckCount: 5,
    activeLearners: 3410,
    retentionRate: 91.4,
    tags: ['Visual Learning', 'Ảnh AI', 'Não phải'],
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-09-02T16:20:00Z',
    fields: [
      // FRONT
      {
        id: 'f-img-front-1',
        side: 'FRONT',
        fieldType: 'IMAGE',
        displayOrder: 1,
        isPrimary: true,
      },
      {
        id: 'f-img-front-2',
        side: 'FRONT',
        fieldType: 'PART_OF_SPEECH',
        displayOrder: 2,
        isPrimary: false,
      },
      // BACK
      {
        id: 'f-img-back-1',
        side: 'BACK',
        fieldType: 'WORD',
        displayOrder: 1,
        isPrimary: true,
      },
      {
        id: 'f-img-back-2',
        side: 'BACK',
        fieldType: 'IPA',
        displayOrder: 2,
        isPrimary: false,
      },
      {
        id: 'f-img-back-3',
        side: 'BACK',
        fieldType: 'MEANING',
        displayOrder: 3,
        isPrimary: false,
      },
      {
        id: 'f-img-back-4',
        side: 'BACK',
        fieldType: 'AUDIO',
        displayOrder: 4,
        isPrimary: false,
        fieldConfig: { autoPlay: true },
      },
    ],
  },
  {
    id: 'tpl-sys-spelling',
    code: 'SPELLING',
    name: 'Type & Spell',
    nameVi: 'Gõ Chính Tả (Type-In)',
    description: 'Rèn luyện trí nhớ cơ bắp và chính tả: Mặt trước hiển thị nghĩa và phát âm kèm ô nhập chữ, người học gõ từ tiếng Anh và hệ thống so khớp đáp án.',
    baseLayout: 'SINGLE_COLUMN',
    interactionType: 'TYPE_IN',
    isSystem: true,
    isDefault: false,
    status: 'active',
    authorName: 'SnapVocab Pedagogy Team',
    authorRole: 'system',
    deckCount: 3,
    activeLearners: 1980,
    retentionRate: 93.8,
    tags: ['Chính tả', 'Tương tác cao', 'Type-In'],
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-09-06T11:00:00Z',
    fields: [
      // FRONT
      {
        id: 'f-spell-front-1',
        side: 'FRONT',
        fieldType: 'MEANING',
        displayOrder: 1,
        isPrimary: true,
      },
      {
        id: 'f-spell-front-2',
        side: 'FRONT',
        fieldType: 'IPA',
        displayOrder: 2,
        isPrimary: false,
      },
      {
        id: 'f-spell-front-3',
        side: 'FRONT',
        fieldType: 'AUDIO',
        displayOrder: 3,
        isPrimary: false,
        fieldConfig: { autoPlay: false },
      },
      {
        id: 'f-spell-front-4',
        side: 'FRONT',
        fieldType: 'PART_OF_SPEECH',
        displayOrder: 4,
        isPrimary: false,
      },
      // BACK
      {
        id: 'f-spell-back-1',
        side: 'BACK',
        fieldType: 'WORD',
        displayOrder: 1,
        isPrimary: true,
        fieldConfig: { strictMode: false, customPlaceholder: 'Nhập từ tiếng Anh...' },
      },
      {
        id: 'f-spell-back-2',
        side: 'BACK',
        fieldType: 'EXAMPLE',
        displayOrder: 2,
        isPrimary: false,
      },
    ],
  },
  {
    id: 'tpl-sys-context',
    code: 'CONTEXT',
    name: 'Cloze Context',
    nameVi: 'Ngữ Cảnh Ẩn Từ (Mask)',
    description: 'Phương pháp Cloze Deletion: Câu ví dụ được che mất từ chính bằng ký tự bí mật (___), người học chạm để hé lộ dần từng manh mối và đáp án.',
    baseLayout: 'SINGLE_COLUMN',
    interactionType: 'TAP_TO_REVEAL',
    isSystem: true,
    isDefault: false,
    status: 'active',
    authorName: 'SnapVocab Pedagogy Team',
    authorRole: 'system',
    deckCount: 2,
    activeLearners: 1650,
    retentionRate: 87.5,
    tags: ['Cloze Deletion', 'Ngữ cảnh', 'Tap-To-Reveal'],
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-09-08T08:45:00Z',
    fields: [
      // FRONT
      {
        id: 'f-ctx-front-1',
        side: 'FRONT',
        fieldType: 'EXAMPLE',
        displayOrder: 1,
        isPrimary: true,
        fieldConfig: { maskPattern: '___' },
      },
      {
        id: 'f-ctx-front-2',
        side: 'FRONT',
        fieldType: 'PART_OF_SPEECH',
        displayOrder: 2,
        isPrimary: false,
      },
      // BACK
      {
        id: 'f-ctx-back-1',
        side: 'BACK',
        fieldType: 'WORD',
        displayOrder: 1,
        isPrimary: true,
      },
      {
        id: 'f-ctx-back-2',
        side: 'BACK',
        fieldType: 'MEANING',
        displayOrder: 2,
        isPrimary: false,
      },
      {
        id: 'f-ctx-back-3',
        side: 'BACK',
        fieldType: 'AUDIO',
        displayOrder: 3,
        isPrimary: false,
        fieldConfig: { autoPlay: true },
      },
      {
        id: 'f-ctx-back-4',
        side: 'BACK',
        fieldType: 'IPA',
        displayOrder: 4,
        isPrimary: false,
      },
    ],
  },
];

export const INITIAL_CUSTOM_TEMPLATES: CardTemplate[] = [
  {
    id: 'tpl-cust-001',
    code: 'IELTS_ACADEMIC',
    name: 'IELTS Band 8 Booster',
    nameVi: 'Luyện Đề IELTS Academic 8.0+',
    description: 'Thiết kế bởi học viên Hoàng Long: Tập trung vào phát âm chuẩn, Collocation và ví dụ học thuật chuyên sâu.',
    baseLayout: 'TWO_COLUMN',
    interactionType: 'FLIP',
    isSystem: false,
    status: 'active',
    authorName: 'Hoàng Long (IELTS 8.0)',
    authorRole: 'learner',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    deckCount: 3,
    activeLearners: 1240,
    retentionRate: 89.2,
    tags: ['IELTS', 'Academic', 'Collocation'],
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-09-02T11:20:00Z',
    fields: [
      { id: 'fc-1-1', side: 'FRONT', fieldType: 'WORD', displayOrder: 1, isPrimary: true },
      { id: 'fc-1-2', side: 'FRONT', fieldType: 'IPA', displayOrder: 2, isPrimary: false },
      { id: 'fc-1-3', side: 'FRONT', fieldType: 'AUDIO', displayOrder: 3, isPrimary: false },
      { id: 'fc-1-4', side: 'BACK', fieldType: 'MEANING', displayOrder: 1, isPrimary: true },
      { id: 'fc-1-5', side: 'BACK', fieldType: 'EXAMPLE', displayOrder: 2, isPrimary: false },
      { id: 'fc-1-6', side: 'BACK', fieldType: 'PERSONAL_NOTE', displayOrder: 3, isPrimary: false },
    ],
  },
  {
    id: 'tpl-cust-002',
    code: 'BIZ_CLOZE',
    name: 'Business English Cloze',
    nameVi: 'Tiếng Anh Doanh Nghiệp & Đàm Phán',
    description: 'Thẻ gõ chính tả cho các từ ngữ hợp đồng và thương mại, yêu cầu so khớp chính xác từng ký tự.',
    baseLayout: 'SINGLE_COLUMN',
    interactionType: 'TYPE_IN',
    isSystem: false,
    status: 'active',
    authorName: 'Ngọc Mai (HR Manager)',
    authorRole: 'learner',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    deckCount: 2,
    activeLearners: 680,
    retentionRate: 92.1,
    tags: ['Business', 'HR', 'Type-In'],
    createdAt: '2026-08-18T14:15:00Z',
    updatedAt: '2026-09-05T09:10:00Z',
    fields: [
      { id: 'fc-2-1', side: 'FRONT', fieldType: 'MEANING', displayOrder: 1, isPrimary: true },
      { id: 'fc-2-2', side: 'FRONT', fieldType: 'AUDIO', displayOrder: 2, isPrimary: false },
      { id: 'fc-2-3', side: 'BACK', fieldType: 'WORD', displayOrder: 1, isPrimary: true, fieldConfig: { strictMode: true } },
      { id: 'fc-2-4', side: 'BACK', fieldType: 'EXAMPLE', displayOrder: 2, isPrimary: false },
    ],
  },
  {
    id: 'tpl-cust-003',
    code: 'KIDS_PICTURE',
    name: 'Kids Super Visual Vocab',
    nameVi: 'Từ Vựng Trẻ Em & Ảnh Hoạt Họa',
    description: 'Mẫu thiết kế nhiều hình ảnh lớn dành cho thiếu nhi và học sinh tiểu học, mặt sau phát âm tự động.',
    baseLayout: 'IMAGE_TOP',
    interactionType: 'FLIP',
    isSystem: false,
    status: 'active',
    authorName: 'Trường Tiểu học Ánh Dương',
    authorRole: 'learner',
    authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80',
    deckCount: 4,
    activeLearners: 1890,
    retentionRate: 94.5,
    tags: ['Kids', 'Flashcard Tranh', 'Vui nhộn'],
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-09-07T15:40:00Z',
    fields: [
      { id: 'fc-3-1', side: 'FRONT', fieldType: 'IMAGE', displayOrder: 1, isPrimary: true },
      { id: 'fc-3-2', side: 'FRONT', fieldType: 'WORD', displayOrder: 2, isPrimary: false },
      { id: 'fc-3-3', side: 'BACK', fieldType: 'MEANING', displayOrder: 1, isPrimary: true },
      { id: 'fc-3-4', side: 'BACK', fieldType: 'AUDIO', displayOrder: 2, isPrimary: false, fieldConfig: { autoPlay: true } },
    ],
  },
  {
    id: 'tpl-cust-004',
    code: 'MINIMAL_SPEED',
    name: 'Minimal Speed Drill',
    nameVi: 'Ôn Tập Tốc Độ Cao (Không Ảnh)',
    description: 'Mẫu thẻ tối giản không chứa hình ảnh để tránh gây xao nhãng khi ôn tập nhanh 50 từ/phút.',
    baseLayout: 'SINGLE_COLUMN',
    interactionType: 'FLIP',
    isSystem: false,
    status: 'flagged',
    authorName: 'Alex Tran',
    authorRole: 'learner',
    deckCount: 1,
    activeLearners: 210,
    retentionRate: 76.4,
    tags: ['Speed Drill', 'Cần rà soát'],
    createdAt: '2026-09-01T08:20:00Z',
    updatedAt: '2026-09-08T17:00:00Z',
    fields: [
      { id: 'fc-4-1', side: 'FRONT', fieldType: 'WORD', displayOrder: 1, isPrimary: true },
      { id: 'fc-4-2', side: 'BACK', fieldType: 'MEANING', displayOrder: 1, isPrimary: true },
    ],
  },
];

export const INITIAL_DECK_MAPPINGS: DeckTemplateMapping[] = [
  {
    deckId: 'deck-001',
    deckTitle: 'Oxford 3000 Core Vocabulary',
    deckTitleVi: '3000 Từ Vựng Tiếng Anh Cốt Lõi Oxford',
    deckIcon: '📚',
    currentTemplateId: 'tpl-sys-classic',
    currentTemplateName: 'Classic Flip',
    targetCefr: 'B1',
    noteCount: 3000,
    activeLearners: 4520,
    completionRate: 78.4,
    lastStudied: 'Vừa xong',
  },
  {
    deckId: 'deck-002',
    deckTitle: 'Business Meetings & Negotiation',
    deckTitleVi: 'Từ Vựng Cuộc Họp & Đàm Phán Doanh Nghiệp',
    deckIcon: '💼',
    currentTemplateId: 'tpl-sys-spelling',
    currentTemplateName: 'Type & Spell',
    targetCefr: 'B2',
    noteCount: 450,
    activeLearners: 1850,
    completionRate: 84.1,
    lastStudied: '5 phút trước',
  },
  {
    deckId: 'deck-003',
    deckTitle: 'IELTS Academic Writing & Speaking',
    deckTitleVi: 'Từ Vựng Học Thuật IELTS Chuyên Sâu',
    deckIcon: '🎓',
    currentTemplateId: 'tpl-sys-reverse',
    currentTemplateName: 'Reverse Recall',
    targetCefr: 'C1',
    noteCount: 820,
    activeLearners: 2430,
    completionRate: 72.8,
    lastStudied: '12 phút trước',
  },
  {
    deckId: 'deck-004',
    deckTitle: 'Daily Food, Nutrition & Cooking',
    deckTitleVi: 'Ẩm Thực, Dinh Dưỡng & Nấu Nướng',
    deckIcon: '🍳',
    currentTemplateId: 'tpl-sys-image',
    currentTemplateName: 'Visual Flash',
    targetCefr: 'A2',
    noteCount: 280,
    activeLearners: 1940,
    completionRate: 91.2,
    lastStudied: '18 phút trước',
  },
  {
    deckId: 'deck-005',
    deckTitle: 'Advanced Tech, AI & Data Science',
    deckTitleVi: 'Công Nghệ Cao, AI & Trí Tuệ Nhân Tạo',
    deckIcon: '🤖',
    currentTemplateId: 'tpl-sys-classic',
    currentTemplateName: 'Classic Flip',
    targetCefr: 'C1',
    noteCount: 520,
    activeLearners: 1670,
    completionRate: 80.5,
    lastStudied: '25 phút trước',
  },
  {
    deckId: 'deck-006',
    deckTitle: 'English Pronunciation & Ear Training',
    deckTitleVi: 'Luyện Nghe & Phát Âm Phản Xạ Nhanh',
    deckIcon: '🎧',
    currentTemplateId: 'tpl-sys-listening',
    currentTemplateName: 'Audio Focus',
    targetCefr: 'B1',
    noteCount: 360,
    activeLearners: 2840,
    completionRate: 89.1,
    lastStudied: '1 giờ trước',
  },
  {
    deckId: 'deck-007',
    deckTitle: 'Idioms & Cloze Deletion Master',
    deckTitleVi: 'Thành Ngữ & Ngữ Cảnh Ẩn Từ',
    deckIcon: '🧩',
    currentTemplateId: 'tpl-sys-context',
    currentTemplateName: 'Cloze Context',
    targetCefr: 'B2',
    noteCount: 310,
    activeLearners: 1290,
    completionRate: 75.3,
    lastStudied: '2 giờ trước',
  },
];

// Mẫu từ vựng để test trên Mobile Simulator
export const SAMPLE_TEST_WORDS: CardViewModel[] = [
  {
    id: 'vocab-test-apple',
    word: 'apple',
    phonetic: '/ˈæp.əl/',
    partOfSpeech: 'noun',
    cefr: 'A1',
    status: 'published',
    source: 'DICT',
    tags: ['fruit', 'kitchen', 'basic'],
    lastUpdated: '2026-09-08T14:20:00Z',
    media: {
      imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop&q=80',
      aiConfidence: 0.98,
    },
    audio: {
      sourceType: 'tts',
      voice: 'en-US',
      speed: 1.0,
      pitch: 1.0,
    },
    meanings: [
      {
        id: 'm-001',
        partOfSpeech: 'noun',
        definitionVi: 'quả táo (trái cây vỏ đỏ hoặc xanh, cùi giòn, vị ngọt hoặc chua)',
        definitionEn: 'a round fruit with firm, white flesh and a green, red, or yellow skin',
        examples: [
          {
            id: 'ex-1',
            en: 'She peeled an apple and sliced it into pieces.',
            vi: 'Cô ấy gọt vỏ một quả táo rồi cắt thành từng miếng nhỏ.',
          },
          {
            id: 'ex-2',
            en: 'An apple a day keeps the doctor away.',
            vi: 'Mỗi ngày một quả táo giúp tránh xa bác sĩ.',
          },
        ],
      },
    ],
    auditHistory: [],
  },
  {
    id: 'vocab-test-resilient',
    word: 'resilient',
    phonetic: '/rɪˈzɪl.jənt/',
    partOfSpeech: 'adjective',
    cefr: 'C1',
    status: 'published',
    source: 'DICT',
    tags: ['academic', 'psychology', 'c1'],
    lastUpdated: '2026-09-07T11:15:00Z',
    media: undefined, // Test trường hợp không có ảnh -> graceful fallback
    audio: {
      sourceType: 'tts',
      voice: 'en-US',
      speed: 1.0,
      pitch: 1.0,
    },
    meanings: [
      {
        id: 'm-002',
        partOfSpeech: 'adjective',
        definitionVi: 'kiên cường, có khả năng phục hồi nhanh chóng sau khó khăn',
        definitionEn: 'able to withstand or recover quickly from difficult conditions',
        examples: [
          {
            id: 'ex-3',
            en: 'The community remained resilient in the face of economic hardship.',
            vi: 'Cộng đồng vẫn kiên cường đối mặt với khó khăn kinh tế.',
          },
        ],
      },
    ],
    auditHistory: [],
  },
  {
    id: 'vocab-test-thermos',
    word: 'thermos',
    phonetic: '/ˈθɜː.məs/',
    partOfSpeech: 'noun',
    cefr: 'B1',
    status: 'published',
    source: 'SCAN',
    tags: ['household', 'scan', 'object'],
    lastUpdated: '2026-09-05T16:00:00Z',
    media: {
      imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
      aiConfidence: 0.94,
    },
    audio: {
      sourceType: 'tts',
      voice: 'en-GB',
      speed: 1.0,
      pitch: 1.0,
    },
    meanings: [
      {
        id: 'm-003',
        partOfSpeech: 'noun',
        definitionVi: 'bình giữ nhiệt (dùng để giữ nước nóng hoặc đồ uống lạnh)',
        definitionEn: 'a container that keeps liquids hot or cold',
        examples: [
          {
            id: 'ex-4',
            en: 'He poured hot coffee from the thermos into his mug.',
            vi: 'Anh ấy rót cà phê nóng từ bình giữ nhiệt vào cốc của mình.',
          },
        ],
      },
    ],
    auditHistory: [],
  },
];
